### ISSUE TITLE
Caps lock freezes the whole system (k70 lux) [macOS Sierra)

### ISSUE THREAD

**Issue by ckb-next-bot** [ckb-next/ckb-next#1]
<a href="https://github.com/ahmadfiroz"><img src="https://avatars1.githubusercontent.com/u/3663724?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ahmadfiroz](https://github.com/ahmadfiroz)**
_Friday Jan 13, 2017 at 21:45 GMT_
_Originally opened as https://github.com/mattanger/ckb-next/issues/23_

----

Tried some of the ways found in google but nothing works actually. Uninstalling CKB works good except the indicator lights ( which was also not working correctly with ckb)

**Comment by Viktini** [comment]
Any updates on this issue? I'm running High Sierra on a Hackintosh and this issue doesn't seem to occur anymore on my K65 RGB LUX, though changing the settings does stop the indicators from working until reboot. (no slowdowns or crashes though).

**Comment by tatokis** [comment]
@Viktini Absolutely no idea, we didn't change anything, so it is possible a macOS update fixed the freezing issue.

Regarding the indicators not working, I haven't investigated, and it's not high on the priority list, but I don't remember it being an issue last time I tested.
Anyone wanting to work on this, feel free.

**Comment by ZirconiumX** [comment]
We're going to close this, since there's no new information and the update seems to have fixed it.
