### ISSUE TITLE
Can't start ckb-next-daeon for experiments.

### ISSUE THREAD

**Issue by LordImmaculate** [ckb-next/ckb-next#1001]
### Describe your situation in detail.

When i try to run ckb-next in experiment mode, I get this error:
`sudo: ckb-next-daemon: command not found`

### Additional Details

Add any additional details here.
I'm using openSUSE TW 20231010, with KDE Plasma 5.27.8
I installed ckb-next using `sudo zypper install ckb-next`
It runs without errors if i start it normally, but it only detects one device because the rest is unsupported.

### Generated Report (if applicable)

Drag your generated report here if it's applicable.

**Comment by Misoder** [comment]
Same here, also on openSUSE TW and KDE Plasma. Command `ckb-next-daemon` is not found and when I try to edit the daemon [as stated in this guide](https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#enabling-experimental-support-on-boot) it fails:
```
▶ sudo systemctl status ckb-next-daemon 
x ckb-next-daemon.service - Corsair Keyboards and Mice Daemon
     Loaded: loaded (/usr/lib/systemd/system/ckb-next-daemon.service; disabled; preset: disabled)
    Drop-In: /etc/systemd/system/ckb-next-daemon.service.d
             `-override.conf
     Active: failed (Result: exit-code) since Thu 2023-10-19 21:38:41 CEST; 2s ago
   Duration: 31ms
    Process: 15999 ExecStart=/usr/bin/ckb-next-daemon --enable-experimental (code=exited, status=203/EXEC)
   Main PID: 15999 (code=exited, status=203/EXEC)
        CPU: 31ms

Oct 19 21:38:41 localhost.localdomain systemd[1]: ckb-next-daemon.service: Scheduled restart job, restart counter is at 5.
Oct 19 21:38:41 localhost.localdomain systemd[1]: ckb-next-daemon.service: Start request repeated too quickly.
Oct 19 21:38:41 localhost.localdomain systemd[1]: ckb-next-daemon.service: Failed with result 'exit-code'.
Oct 19 21:38:41 localhost.localdomain systemd[1]: Failed to start Corsair Keyboards and Mice Daemon.

```
