### ISSUE TITLE
ckb-next terminates when keyboard unplugs

### ISSUE THREAD

**Issue by Roald-Andresen** [ckb-next/ckb-next#1004]
### Enhancement Details

Well, not really unplugs, but...  keyboard is connected through a USB-switch, and when I switch away from the machine, the ckb-next program terminates.  When I switch back, I have to start it manually.
If this is a design decision, I can see reasons why.
I would like to suggest having a settings option where the user can select to have ckb-next up an running independent off plugged-in devices.  Default setting can easily be Off for this setting.

Btw.: Great program!

:-) Roald

### Additional Details

Add any additional details here.

**Comment by tatokis** [comment]
This should not be happening. It is probably crashing for some reason. If you run `ckb-next` in a terminal when this happens, what is the output?
Does  `coredumpctl show -1 ckb-next ckb-next.real`  return anything?

Also, what distro and version are you using? (And also what version of ckb-next.)
