### ISSUE TITLE
New Release with Cosair K100 Support

### ISSUE THREAD

**Issue by officiallymarky** [ckb-next/ckb-next#1009]
### Enhancement Details

Can you release a new tag with main so Corsair K100 is supported without having to build from Github please?

### Additional Details

Add any additional details here.

**Comment by gravityfargo** [comment]
Without a report, maintainers cannot know which specific device you're referring to. Three varieties are already listed on the wiki, and probably more exist. This issue is a new device request for the master branch, not an enhancement. 

Possibly related to:
#651
#907
ed70884
