### ISSUE TITLE
NIGHTSABRE WIRELESS RGB Gaming Mouse

### ISSUE THREAD

**Issue by Niklasw99** [ckb-next/ckb-next#1015]
### What kind of device is it?

Mouse

### What is the name of the device?

NIGHTSABRE WIRELESS RGB Gaming Mouse

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/gaming-mouse/ch-931b011-na/nightsabre-wireless-rgb-gaming-mouse-ch-931b011-na

### Additional Details

Add any additional details here.
It works like a mouse. 

### Generated Report

Report:
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/13341267/ckb-next-dev-detect-report.gz)

the mouse "works" there are seemingly no issues with the useage in genereal only when it's on a low dpi mode from the Corsair Presets on the mouse allready.

**Comment by egberts** [comment]
If you can load  up Debug linux kernel and run `usbmon`, you can contribute to finding these scan codes that your device emits by following steps in https://github.com/ckb-next/ckb-next/pull/656#issuecomment-729265011
