### ISSUE TITLE
DARKSTAR support request

### ISSUE THREAD

**Issue by konzserwas** [ckb-next/ckb-next#1029]
### What kind of device is it?

Mouse

### What is the name of the device?

DARKSTAR WIRELESS RGB MMO Gaming Mouse (EU)

### Link to Corsair's Product Page

https://www.corsair.com/eu/en/p/gaming-mouse/ch-931a011-eu/darkstar-wireless-rgb-mmo-gaming-mouse-eu-ch-931a011-eu

### Additional Details

Add any additional details here.

### Generated Report

[ckb-next-report-1704529661.gz](https://github.com/ckb-next/ckb-next/files/13848870/ckb-next-report-1704529661.gz)

**Comment by gravityfargo** [comment]
Please plug the mouse in via USB and disconnect the wireless dongle, then regenerate the report and submit a new issue. Thanks!
