### ISSUE TITLE
Accessibility scroll zoom

### ISSUE THREAD

**Issue by WatermelonDriveway** [ckb-next/ckb-next#103]
Not sure if this is a feature request or a bug fix.

![screen shot 2018-02-19 at 11 29 36 pm](https://user-images.githubusercontent.com/8306685/36408708-ca0cda82-15cc-11e8-97ef-888609acfa3f.png)

This "use scroll gesture with modifier keys to zoom" feature doesn't work with CKB

**Comment by tatokis** [comment]
This will most likely be fixed in the next release by the karabiner backend.
There are available builds for you to try http://ckb-next.info/mac/ckb-next_v0.3.0-62-g68fedda_10.11-SDK.dmg
