### ISSUE TITLE
Corsair iCUE H150i RGB ELITE Liquid CPU Cooler

### ISSUE THREAD

**Issue by MysteriousRSA** [ckb-next/ckb-next#1033]
### What kind of device is it?

AIO Coolers

### What is the name of the device?

iCUE H150i RGB ELITE Liquid CPU Cooler

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/cpu-coolers/cw-9060060-ww/icue-h150i-rgb-elite-liquid-cpu-cooler-cw-9060060-ww

### Generated Report

[ckb-next-report-1705587736.gz](https://github.com/ckb-next/ckb-next/files/13977732/ckb-next-report-1705587736.gz)

**Comment by gravityfargo** [comment]
While the name of this cooler is different from the H150i ELITE CAPELLIX as requested in #1002 the product ids are the same. I have annotated this in the wiki.
