### ISSUE TITLE
Conflict with OpenRgb

### ISSUE THREAD

**Issue by MatthiasDillen** [ckb-next/ckb-next#1041]
### Describe your situation in detail.

I'm using openrgb to control all my rgb devices with the same profile, but when ckb-next is running my mouse doesnt get detected anymore in Openrgb. Would it be possible to configure the button mapping only in ckb-next and leave the rgb for Openrgb?
Wanted to try writing to the mouse memory and then just exit ckb-next, but that doesnt seem possible on Linux (or ckb-next in general?). Another option would be dual booting windows to be able to write the mapping to the memory and then use Linux without ckb-next so openrgb can detect the mouse again. But having 2 os's running on my pc seems a bit overkill for some button mapping.

### Additional Details

Mouse: Corsair Scimitar Elite rgb

### Generated Report (if applicable)

Drag your generated report here if it's applicable.

**Comment by Ravenslofty** [comment]
Duplicate of #887; see the explanation there for why this isn't that simple.
