### ISSUE TITLE
adding scuf envision pro support

### ISSUE THREAD

**Issue by MrSlightlyDamp** [ckb-next/ckb-next#1051]
### What kind of device is it?

Keyboard

### What is the name of the device?

scuf envision pro 

### Link to Corsair's Product Page

https://scufgaming.com/pc-controllers/scuf-envision-pro-steelgray

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.
[ckb-next-report-1712458340.gz](https://github.com/ckb-next/ckb-next/files/14895614/ckb-next-report-1712458340.gz)

**Comment by gravityfargo** [comment]
This is not a Corsair device.

**Comment by NightSprinter** [comment]
> Isn't it though? Corsair acquired SCUF back in 2019. The controller only works with the iCUE software.

Indeed it is, as much as Elgato is after Corsair bought them.

**Comment by ksteckert** [comment]
> > Isn't it though? Corsair acquired SCUF back in 2019. The controller only works with the iCUE software.
> 
> Indeed it is, as much as Elgato is after Corsair bought them.

Yes, but perhaps even more so.  You don't *NEED* iCUE to use StreamDeck products, although they do have integration between the two.  The SCUF controller, however, REQUIRES the iCUE software for any configuration changes on the SCUF device.  There is no standalone software for managing SCUF controllers apart from Corsair's iCUE.

**Comment by gravityfargo** [comment]
> Isn't it though? Corsair acquired SCUF back in 2019. The controller only works with the iCUE software.

You're right, sorry about that. The issue is that ckb-next doesn't seem to recognize any of it as per the report. Could you run 

```shell
sudo lsusb --verbose > devices.txt    
```

and upload the devices.txt after?

**Comment by maybesheforgot** [comment]
> > Isn't it though? Corsair acquired SCUF back in 2019. The controller only works with the iCUE software.
> 
> You're right, sorry about that. The issue is that ckb-next doesn't seem to recognize any of it as per the report. Could you run
> 
> sudo lsusb --verbose > devices.txt    
> 
> and upload the devices.txt after?

here's mine [devices.txt](https://github.com/user-attachments/files/22675289/devices.txt)
