### ISSUE TITLE
Update PPAs to ubuntu noble?

### ISSUE THREAD

**Issue by queenbiscuit311** [ckb-next/ckb-next#1056]
### Enhancement Details

Ubuntu 24.04 Noble Numbat came out recently. Not urgent since official upgrades from mantic to noble still haven't been enabled, but but the PPAs provided in the installation instructions still only have packages for mantic. unless someone on ubuntu 24.04 already had ckb-next installed before upgrading from a previous ubuntu version, they wouldn't be able to install it by simply adding either of the ppas because they don't have release files for ubuntu noble.

**Comment by tatokis** [comment]
Yeah, sorry about that. I just added the release and it should build soon (even though the version strings are still incorrect, and apt will still prefer the one from the main repos).
I added the git package too, but that will be built when there's a new commit.
