### ISSUE TITLE
Mouse M75 support

### ISSUE THREAD

**Issue by tomdevin** [ckb-next/ckb-next#1064]
### What kind of device is it?

Mouse

### What is the name of the device?

M75

### Link to Corsair's Product Page

https://www.corsair.com/de/de/p/gaming-mouse/ch-931d011-eu/m75-wireless-lightweight-rgb-gaming-mouse-white-eu-ch-931d011-eu

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
Please generate a report and attach it. I am closing this for now.

> In the ckb-next application, go to the Settings tab of the user interface and click the Generate Report button. Alternatively, run ckb-next-dev-detect in a terminal.

**Comment by tomdevin** [comment]
Hi, sorry that I come back to you just now. Find attached the generated report. Thank you in advance!

[ckb-next-report-1730100850.gz](https://github.com/user-attachments/files/17538934/ckb-next-report-1730100850.gz)
