### ISSUE TITLE
HS60 Pro Surround support

### ISSUE THREAD

**Issue by AhsanSarwar45** [ckb-next/ckb-next#1066]
### What kind of device is it?

Headphone

### What is the name of the device?

HS60 PRO SURROUND

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/gaming-headsets/ca-9011213-na/hs60-pro-surround-gaming-headset-carbon-ca-9011213-na

### Generated Report

[ckb-next-dev-detect-report.gz](https://github.com/user-attachments/files/15747345/ckb-next-dev-detect-report.gz)

**Comment by gravityfargo** [comment]
Hi, your attached report does not have any devices listed. Please make sure your device is plugged in and rerun the report.
