### ISSUE TITLE
DARK CORE RGB PRO Gaming Mouse & Gaming K95 RGB PLATINUM Keyboard Connection Issue.

### ISSUE THREAD

**Issue by Tim-Rambo** [ckb-next/ckb-next#1070]
### Describe your situation in detail.

OS: GarudaOS(Arch Based) / Version | 0.6.0-1.1 / DE Plasma

The application don't run when I try to run it. Below is me using this sudo _ckb-next-daemon --enable-experimental_ command to run CKB with some sort of output. No application tray icon.

### Additional Details

**LOG**
ckb-next-daemon 0.6.0
[I] You have enabled support for experimental devices in a ckb-next stable release. It is recommended to use the latest code from git.
[I] Root controller ready at /dev/input/ckb0
[E] patchkeys (keymap_patch.c:139): Could not find profswitch in base keymap. Not patching profswitch for mouse.
[E] patchkeys (keymap_patch.c:139): Could not find profswitch in base keymap. Not patching profswitch for mouse.
[I] Connecting CORSAIR DARK CORE RGB PRO Gaming Dongle at /dev/input/ckb1
[I] Connecting CORSAIR DARK CORE RGB PRO Gaming Mouse at /dev/input/ckb2
[I] Connecting Corsair Gaming K95 RGB PLATINUM Keyboard at /dev/input/ckb3
[I] Starting input thread for /dev/input/ckb2
[I] Found EP 0x82 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/ep_82
[I] Found EP 0x84 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.1/ep_84
[I] Found EP 0x83 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.2/ep_83
[I] Found EP 0x81 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.3/ep_81
[W] bragi_process_notification (bragi_notification.c:36): ckb2: Unknown bragi notification for dev 2
[W] bragi_process_notification (bragi_notification.c:36): ckb2: Unknown bragi notification for dev 2
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x15. Device said it's not supported.
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x16. Device said it's not supported.
[I] Starting input thread for /dev/input/ckb1
[I] Found EP 0x82 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/ep_82
[I] Found EP 0x84 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.1/ep_84
[I] Found EP 0x83 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.2/ep_83
[I] Starting input thread for /dev/input/ckb3
[I] Found EP 0x81 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.3/ep_81
[I] Found EP 0x85 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.4/ep_85
[I] Found EP 0x86 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.5/ep_86
[I] Found EP 0x81 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/ep_81
[I] ckb2: Pairing id: 2b f1 01 04 6a 22 55 82
[I] Setup finished for /dev/input/ckb2
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x15. Device said it's not supported.
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x16. Device said it's not supported.
[I] Received identification packet: 0e 01 00 00 01 01 00 01 29 03 03 03 1c 1b 2d 1b 01 01 00 01 c0 ff 40 01 0300 00 00 02 40 02 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[I] Setup finished for /dev/input/ckb3
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x2. Device said it's not supported.
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x44. Device said it's not supported.
[I] ckb1: Pairing id: 2b f1 01 04 6a 22 55 82
[I] Setup finished for /dev/input/ckb1

**Comment by gravityfargo** [comment]
Please generate a report and attach it.

> In the ckb-next application, go to the Settings tab of the user interface and click the Generate Report button. Alternatively, run ckb-next-dev-detect in a terminal.
