### ISSUE TITLE
HS45 Headphones

### ISSUE THREAD

**Issue by manic-vermin** [ckb-next/ckb-next#1071]
### Enhancement Details

Please add support for HS45 headphones. Current issues: quieter audio than windows, lower quality than windows, static when changing audio levels, and lack of surround sound. 

### Additional Details
Thank you for this contribution, you are doing gods work.
Add any additional details here.

**Comment by gravityfargo** [comment]
Please submit a [New Device Request](https://github.com/ckb-next/ckb-next/issues/new?assignees=&labels=new-device&projects=&template=new-device-request.yml) with the required information.
