### ISSUE TITLE
Add a random color option on heat animation

### ISSUE THREAD

**Issue by maignialolivier** [ckb-next/ckb-next#1075]
### Enhancement Details

I added possibility to chose random color on heat animation. So on each key press, animation will have a random color.

### Additional Details

From de9fe21b93d1fc8cc8e1bc7a3925a42855f1bcb1 Mon Sep 17 00:00:00 2001
From: Olivier Maignial <olivier.maignial@hotmail.com>
Date: Sun, 14 Jul 2024 19:36:38 +0200
Subject: [PATCH] Add a random color option on heatmap animation

---
 src/animations/heat/main.c | 23 +++++++++++++++++++++--
 1 file changed, 21 insertions(+), 2 deletions(-)

diff --git a/src/animations/heat/main.c b/src/animations/heat/main.c
index 6386d63..960f35f 100644
--- a/src/animations/heat/main.c
+++ b/src/animations/heat/main.c
@@ -28,6 +28,7 @@ void ckb_info(){
     // Effect parameters
     CKB_PARAM_AGRADIENT("color", "Fade color:", "", "ffffffff");
     CKB_PARAM_BOOL("random", "Random Brightness", 0);
+    CKB_PARAM_BOOL("randColor", "Random Color", 0);
 	CKB_PARAM_LONG("ffade", "Frames to fade", "frames", 30, 10, 1000);
 	CKB_PARAM_DOUBLE("pressestofull", "Presses to full", "keypresses", 10.f, 1.f, 100.f);
 
@@ -49,10 +50,12 @@ void ckb_info(){
 
 ckb_gradient animcolor = { 0 };
 int randomBright = 0;
+int randomColor = 0;
 long ffade = 30;
 double pressestofull = 10.f;
 
 typedef struct{
+	ckb_gradient animcolor;
 	unsigned int usages;
 	int pressed;
 	double timing;
@@ -73,6 +76,7 @@ void ckb_init(ckb_runctx* context){
 void ckb_parameter(ckb_runctx* context, const char* name, const char* value){
     CKB_PARSE_AGRADIENT("color", &animcolor){}
 	CKB_PARSE_BOOL("random", &randomBright){}
+	CKB_PARSE_BOOL("randColor", &randomColor){}
     CKB_PARSE_LONG("ffade", &ffade){}
 	CKB_PARSE_DOUBLE("pressestofull", &pressestofull){}
 }
@@ -81,6 +85,21 @@ void anim_add(int index){
 	anims[index].usages += ffade;
 	anims[index].pressed = 1;
 	anims[index].timing = 0.f;
+
+	anims[index].animcolor = animcolor;
+
+	if (randomColor)
+	{
+		unsigned char r = (unsigned char) rand() % 255;
+		unsigned char g = (unsigned char) rand() % 255;
+		unsigned char b = (unsigned char) rand() % 255;
+		for (int i=0 ; i < CKB_GRAD_MAX ; ++i)
+		{
+			anims[index].animcolor.r[i] = r;
+			anims[index].animcolor.g[i] = g;
+			anims[index].animcolor.b[i] = b;
+		}
+	}
 }
 
 void anim_remove(int index){
@@ -124,9 +143,9 @@ int ckb_frame(ckb_runctx* context){
 			continue;
 		float a, r, g, b;
 		if(randomBright)
-			ckb_grad_color(&a, &r, &g, &b, &animcolor, ((float)(rand() % 1024))/10.f);
+			ckb_grad_color(&a, &r, &g, &b, &anims[i].animcolor, ((float)(rand() % 1024))/10.f);
 		else
-			ckb_grad_color(&a, &r, &g, &b, &animcolor, (float)fmin(anims[i].usages,full)*100.f/full);
+			ckb_grad_color(&a, &r, &g, &b, &anims[i].animcolor, (float)fmin(anims[i].usages,full)*100.f/full);
 		ckb_alpha_blend(keys+i, a, r, g, b);
     }
     return 0;
-- 
2.34.1

**Comment by gravityfargo** [comment]
Thank you for taking the time to contribute! Please open a pull request with your submission rather than code in an issue. If, for some reason, you really need to use a patch (preferably not), use [git format-patch](https://git-scm.com/docs/git-format-patch) to create a file.

Great work!
