### ISSUE TITLE
K70 Pro Mini Wireless support for RGB control

### ISSUE THREAD

**Issue by Stevenzocker** [ckb-next/ckb-next#1077]
### What kind of device is it?

Keyboard

### What is the name of the device?

K70 Pro MINI Wireless

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/keyboards/ch-9189010-na/k70-pro-mini-wireless-60-mechanical-cherry-mx-red-switch-keyboard-with-rgb-backlighting-black-ch-9189010-na

### Additional Details

it would be wonderful to have working lighting drivers for this product 
USB id 1b1bc:1ba6

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
Hi,
Please [generate](https://github.com/ckb-next/ckb-next/wiki/Troubleshooting#generate-a-report) and submit a report by attaching it to this issue or opening another.

**Comment by constambeys** [comment]
[ckb-next-report-1728136861.gz](https://github.com/user-attachments/files/17266465/ckb-next-report-1728136861.gz)
