### ISSUE TITLE
Add support for K65 PRO MINI RGB

### ISSUE THREAD

**Issue by Voltherthorn** [ckb-next/ckb-next#1080]
### What kind of device is it?

Keyboard

### What is the name of the device?

K65 PRO MINI RGB

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/keyboards/ch-91a401a-na/k65-pro-mini-rgb-65-optical-mechanical-gaming-keyboard-ch-91a401a-na

### Additional Details

German Layout would be wonderful.

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
Hi,
Please [generate a report](https://github.com/ckb-next/ckb-next/wiki/Troubleshooting#generate-a-report) and attach it here or open a new issue.
