### ISSUE TITLE
Cannot find devices

### ISSUE THREAD

**Issue by kelpc100** [ckb-next/ckb-next#1092]
### Describe your situation in detail.

I am having trouble finding my devices. I am using the K70 RGB Pro Keyboard and Scrimtar RGB Elite Wireless Mouse, but the devices will not show up. I have tried unplugging/plugging back in, restarting the program, restarting my computer, reinstalling ckb-next, and re installing linux but the devices will not show up in ckb-next. I am using Linux Mint 22 cinnamon, and tried downloading via the command line (v 0.6.0) and software manager (v 0.6.0). I have used lusb to check if my devices are showing up, and they appear as normally, yet no luck with the software. Any help would be appreciated.

### Additional Details

Add any additional details here.

### Generated Report (if applicable)

Drag your generated report here if it's applicable.

**Comment by DreiPixel** [comment]
they not supported yet.
https://github.com/ckb-next/ckb-next/pull/1030
https://github.com/ckb-next/ckb-next/pull/997

**Comment by kelpc100** [comment]
Ok, thank you.
