### ISSUE TITLE
Corsair K55 Core RGB

### ISSUE THREAD

**Issue by imnotamessiah** [ckb-next/ckb-next#1093]
### What kind of device is it?

Keyboard

### What is the name of the device?

Corsair K55 Core RGB

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/keyboards/ch-9226c65-na/k55-core-rgb-mechanical-gaming-keyboard-black-ch-9226c65-na?srsltid=AfmBOoqVwHQHwM7vkOe99ETf9n7EByk2SrLTYiDELlcqH_h0FNSA_ULm

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.
HI, I am new to this, please let me know what do you need, thanks!

**Comment by gravityfargo** [comment]
Please [generate a report](https://github.com/ckb-next/ckb-next/wiki/Troubleshooting#generate-a-report) and attach it to this issue or open a new request.
