### ISSUE TITLE
Corsair K57 Keyboard

### ISSUE THREAD

**Issue by BugZappa** [ckb-next/ckb-next#1099]
### What kind of device is it?

Keyboard

### What is the name of the device?

SKU: CH-925C015-NA

### Link to Corsair's Product Page

https://www.corsair.com/lm/en/p/keyboards/ch-925c015-na/k57-rgb-wireless-gaming-keyboard-na-ch-925c015-na

### Additional Details

Add any additional details here.
Keyboard has G keys which serve no purpose without it's respective software. 
Please consider adding support for this keyboard.

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
Hi, please generate a report and open a new issue. The instructions are outlined in the template.
