### ISSUE TITLE
output usb

### ISSUE THREAD

**Issue by felbus** [ckb-next/ckb-next#112]
attached output from corsair-re for k63
[1b45.txt](https://github.com/ckb-next/ckb-next/files/1770584/1b45.txt)

**Comment by felbus** [comment]
[ckb-dev-detect-report.txt](https://github.com/ckb-next/ckb-next/files/1770592/ckb-dev-detect-report.txt)

**Comment by ZirconiumX** [comment]
This probably should have gone in the K63 Wireless issue.
