### ISSUE TITLE
[arch] Strafe RGB setting mode programmatically not working

### ISSUE THREAD

**Issue by t03i** [ckb-next/ckb-next#122]
As indicated by the documentation, I am trying to set the mode of my Strafe RGB programmatically using: 
```
echo 'active' > /dev/input/ckb1/cmd
echo 'mode 2 switch' > /dev/input/ckb1/cmd
```
The keyboard is clearly activated indicated by the numlock light, which somehow turns off.
However, the keyboard just flickers shortly without actually changing anything.
This is especially strange, since changing the mode using the GUI works flawlessly.

I am using the prebuild and up-to-date ckb-next-git package on my Arch-Linux installation.

ckb-next-dev-detect-report:
[data.txt](https://github.com/ckb-next/ckb-next/files/1823251/data.txt)

**Comment by tatokis** [comment]
I don't think the strafe supports multiple modes.
That said, the GUI needs to not be running to switch between modes that way.

**Comment by ZirconiumX** [comment]
Don't be confused between "modes", which are hardware colour settings that
work when ckb-next is off, and "profiles", which are software colour
settings controlled by the GUI.

Your keyboard only supports a single mode; while profiles are controlled by
the GUI alone.

I'm not happy with that arrangement, but for now, that's how it is.

**Comment by t03i** [comment]
That was my error. Thank you for pointing it out! 
I'll have to find a manual solution then, thanks.

**Comment by ZirconiumX** [comment]
When I get home, I'll clarify the wording of that document for you.
