### ISSUE TITLE
Uninstalling old version

### ISSUE THREAD

**Issue by blakethepatton** [ckb-next/ckb-next#132]
![screenshot from 2018-03-28 15-18-06](https://user-images.githubusercontent.com/1137743/38059958-7f435f42-329d-11e8-9b0a-5fdd7c80e8ca.png)

I've installed this new copy, unfortunately the old copy still shows up in my launcher menu. How can I remove the previous version (from before the consolidated ckb-next repo)?

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#uninstallation-of-ckb-next--030
