### ISSUE TITLE
Build from source fails Mac OS 10.13.3

### ISSUE THREAD

**Issue by ekrof** [ckb-next/ckb-next#141]
Hello I'm having trouble building from the latest source with the following error message: 

```
CMake Error at cmake/modules/DeployQt5.cmake:216:
  Parse error.  Expected a command name, got unquoted argument with text
  "//".
Call Stack (most recent call first):
  src/gui/CMakeLists.txt:491 (include)
```

I tried to go back to the stable 0.29 but there was a driver mismatch because of my previously installed newer builds. Attached are my CMakeOutput.log and CmakeError.log files

[CMakeError.log](https://github.com/ckb-next/ckb-next/files/1887767/CMakeError.log)
[CMakeOutput.log](https://github.com/ckb-next/ckb-next/files/1887768/CMakeOutput.log)

**Comment by tatokis** [comment]
My apologies. It appears that in the process of trying to fix something else I broke this.
Try reverting https://github.com/ckb-next/ckb-next/commit/9ac819ef86290572f139039c414214cb68f071bc

**Comment by tatokis** [comment]
Should be fixed now

**Comment by ekrof** [comment]
Thanks dude you're awesome
