### ISSUE TITLE
Caps Lock Light Doesn't Turn Off (Minor)

### ISSUE THREAD

**Issue by SlidingHorn** [ckb-next/ckb-next#152]
# Bug Report

## Devices information
K95 RGB Keyboard

## What is the program's current behavior?
Caps lock light turns on, Caps lock is on.   Turning Caps lock off works, but the light remains on

## What would you like it to do instead?
Turn off the caps lock light when caps lock is turned off

### Source
built from source (long way) on Ubuntu Studio 18.04

### Why didn't you upload the device detect report
It didn't work

**Comment by ZirconiumX** [comment]
Can you give us more information about the dev-detect report? "It didn't work" is not very helpful.

**Comment by tatokis** [comment]
Unfortunately, no one has been able to reproduce this.
