### ISSUE TITLE
New device?         CORSAIR K63 Wireless Mechanical Gaming Keyboard:            Product ID: 0x1b45

### ISSUE THREAD

**Issue by dartoledo** [ckb-next/ckb-next#159]
I have what it looks like a new device:
USB Devices:
        CORSAIR K63 Wireless Mechanical Gaming Keyboard:

          Product ID: 0x1b45
I fixed locally by updating https://github.com/ckb-next/ckb-next/blob/d7181772039d6fd193c4d498b538c2ad75e24ea5/src/daemon/usb.h
0x1b45 -> 0x1b40

**Comment by ZirconiumX** [comment]
We already know about this; we've been working on it in the `wireless`
branch, which can light up a Dark Core. At the moment it doesn't yet light
up a K63WL, but we think we can do it soon.

**Comment by dartoledo** [comment]
Wireless branch? cool ! thank you use that then.

**Comment by ZirconiumX** [comment]
If you could join us in IRC (the blue Freenode button) in a few hours,
that'd help us light up the keyboard, since we don't have any hardware of
our own.

**Comment by dartoledo** [comment]
ok joined, fyi it lights up when using wireless branch

**Comment by ZirconiumX** [comment]
Yeah, but as far as I know you can't set custom animations for the keyboard
in the GUI. There's also no battery status indicator because we haven't
figured that out yet.

On 21 Apr 2018 09:26, "dartoledo" <notifications@github.com> wrote:

ok joined, fyi it lights up when using wireless branch

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ckb-next/ckb-next/issues/159#issuecomment-383277666>,
or mute the thread

**Comment by dartoledo** [comment]
let me add connect logs here: 
OS Version:
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

USB Devices:
        CORSAIR K63 Wireless Mechanical Gaming Keyboard:

          Product ID: 0x1b45
          Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
          Version: 1.02
          Serial Number: xxxx
          Speed: Up to 12 Mb/sec
          Manufacturer: CORSAIR
          Location ID: 0x00300000 / 1
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0

--
--
        CORSAIR K63 Wireless USB Receiver:

          Product ID: 0x1b50
          Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
          Version: 1.02
          Serial Number: xxxx
          Speed: Up to 12 Mb/sec
          Manufacturer: CORSAIR
          Location ID: 0x14d00000 / 1
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0
          Built-In: Yes

Daemon log:
    ckb-next: Corsair RGB driver 0.2.9-185-g8531096
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-185-g8531096
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.3.0-pre
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.3.0-pre
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-173-gb0a01d6
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-173-gb0a01d6
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-170-g37ee879
[I] Root controller ready at /var/run/ckb0
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-170-g37ee879
[I] Root controller ready at /var/run/ckb0
[I] Connecting CORSAIR K63 Wireless Mechanical Gaming  at /var/run/ckb1
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[I] Starting input thread for /var/run/ckb1
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] _usbrecv (via firmware.c:24): Too many send/recv failures. Dropping.
[W] _start_dev (device.c:41): Unable to load firmware version/poll rate
[I] Setup finished for /var/run/ckb1
[I] Registering EventTap for modifier keys.
[I] Registering EventTap for modifier keys.

[I] Caught signal 15
[I] Disconnecting /var/run/ckb1
[I] Removed device path /var/run/ckb1
[I] Stopping input thread for /var/run/ckb1
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-200-g8d2a2db
[I] Root controller ready at /var/run/ckb0
[I] Connecting CORSAIR K63 Wireless Mechanical Gaming  at /var/run/ckb1
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[W] add_hid (usb_mac.c:847): Tried to set up ifhid[0] for device ckb1, but it was already set up. Skipping...
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[I] Registering EventTap for modifier keys.
[I] Registering EventTap for modifier keys.
[I] Disconnecting /var/run/ckb1
[I] Removed device path /var/run/ckb1
[F] closeusb (usb.c:783): Error destroying interrupt cond 22
[F] closeusb (usb.c:787): Error destroying interrupt mutex 22
[I] Removed device path /var/run/ckb1
[F] closeusb (usb.c:783): Error destroying interrupt cond 22
[F] closeusb (usb.c:787): Error destroying interrupt mutex 22
[I] Removed device path /var/run/ckb1
[F] closeusb (usb.c:783): Error destroying interrupt cond 22
[F] closeusb (usb.c:787): Error destroying interrupt mutex 22
[E] iterate_devices_hid (usb_mac.c:876): Failed to create device plugin: e00002be
[W] add_hid (usb_mac.c:847): Tried to set up ifhid[0] for device ckb1, but it was already set up. Skipping...

[I] Caught signal 15
[I] Closing root controller
[I] Removed device path /var/run/ckb0
    ckb-next: Corsair RGB driver 0.2.9-200-g8d2a2db
[I] Root controller ready at /var/run/ckb0
[I] Connecting CORSAIR K63 Wireless Mechanical Gaming  at /var/run/ckb1
[W] iterate_devices_hid (usb_mac.c:893): Failed to open device: e00002c5
[W] iterate_devices_usb (usb_mac.c:759): Unable to seize USB handle, continuing anyway...
[I] Connecting CORSAIR K63 Wireless Mechanical Gaming  at /var/run/ckb2
[I] Starting input thread for /var/run/ckb1
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] os_usbsend (via firmware.c:24): Got return value 0xe000404f
[E] _usbrecv (via firmware.c:24): Too many send/recv failures. Dropping.
[W] _start_dev (device.c:41): Unable to load firmware version/poll rate
[I] Setup finished for /var/run/ckb1
[I] Registering EventTap for modifier keys.
[I] Registering EventTap for modifier keys.

GUI log:
Path to settings: "/Users/darwin.toledo/Library/Preferences/com.ckb-next.ckb-next.plist"
Looking for old settings in: "/Users/darwin.toledo/Library/Preferences/com.ckb.ckb.plist"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/heat"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/pinwheel"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/rain"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/random"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
Scanning  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/wave"
Starting  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/random"
Starting  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
No GPG detected, signature verification disabled
Downloaded new firmware list. 31 entries found.
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Starting  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Starting  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/wave"
Starting  "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"
Can't find valid firmware version for device 6981 "6981"

**Comment by ZirconiumX** [comment]
@tatokis would have to judge if the mutex errors are okay or not, but the
GUI firmware errors are to be expected (we don't currently support wireless
firmware update, because the dongle and the keyboard need to be updated
simultaneously, and have multiple sections).

With no disrespect, Mac is a little awkward for us to develop on; do you
have access to a Linux installation?

**Comment by dartoledo** [comment]
Yeah no worries. Sorry no, I can do virtualbox with linux  at most.
