### ISSUE TITLE
Bug after linux start up

### ISSUE THREAD

**Issue by Mymetique** [ckb-next/ckb-next#163]
Hello,

I'm having an issue with my corsair keyboard using ckb-next. I'm using arch linux and since last week I'm encountering issues after a full system upgrade.

My system is Arch 4.16.5 and ckb-next has been installed from AUR .

What is the issue :

Since the day I started using ckb-next I had random input hangs after plugin in the corsair keyboard, meaning, sometimes it will detect the keyboard and work flawlessly, sometimes no input at all will be registered (nor internal keyboard, nor external keyboard, nor trackpad), the only choice is to hard reboot then.

But now, since the latest upgrade last week I can only use my three input devices if I booted my computer with the corsair keyboard plugged in. Which is not very handful when I work remotely with my laptop. 

Thank you for your help 
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1960086/ckb-next-dev-detect-report.gz)

**Comment by ZirconiumX** [comment]
Could you [join us in IRC?](http://webchat.freenode.net/?channels=%23ckb-next&uio=d4)
