### ISSUE TITLE
Fix removal instructions

### ISSUE THREAD

**Issue by nazar-pc** [ckb-next/ckb-next#164]
On [wiki page](https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#uninstallation-of-ckb-next--030) `sudo rm /usr/share/applications/ckb.desktop` should be changed to `sudo rm /usr/local/share/applications/ckb.desktop`, since this is the correct path (in my case at least) for that file.

**Comment by tatokis** [comment]
Sure enough
```
tatokis@tatokis-PC:~$ sudo strace -f -e open xdg-desktop-menu install --novendor 'ckb.desktop' 2>&1 | grep "ckb.*desktop"
[..]
[pid 18781] open("/usr/local/share//applications/ckb.desktop", O_WRONLY|O_CREAT|O_EXCL, 0700) = 4
```
Going through the history[1] shows that it's been like that for a long time. Good catch.

[1] https://github.com/ckb-next/ckb-next/commits/old/quickinstall
