### ISSUE TITLE
Macro is ignored when pressing additional key.

### ISSUE THREAD

**Issue by Sur3** [ckb-next/ckb-next#166]
Bug-report:
Hi when putting some single key events on the side keys of my corsair scimitar I can use them while keeping right mouse button pressed, but when having some macros on the sidekeys they are ignored while right mouse button is pressed. It would be great if macros could always execute when the button is pressed regardless of other buttons.

My ckb-next version 0.2.9.

**Comment by Sur3** [comment]
Problem still exists in 0.4.0

**Comment by tatokis** [comment]
Unfortunately no one has really worked on it

**Comment by tosirius** [comment]
Having the same issue here too. Just installed today too. ckb-next 0.4.2 using a scimitar and a K70 rapidfire.

**Comment by tatokis** [comment]
I fixed this in master, will be in the next release
