### ISSUE TITLE
K63 Keyboard Wired or Wireless showing no device connected

### ISSUE THREAD

**Issue by DavidChuks** [ckb-next/ckb-next#171]
I am not able to find my keyboard on the ckb application. It is not finding it at all.

I have attached my .gz report. 

Some help will be appreciated. Thanks.

I have also read other issues and none seem to resolve my issue.

Running Mac OS 10.13.4

Thanks.

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1987788/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
K63 Wireless is not supported yet.
You can follow https://github.com/ckb-next/ckb-next/pull/158 for updates

**Comment by DavidChuks** [comment]
But is K63 wired supported?

**Comment by ZirconiumX** [comment]
The original wired-only K63 is supported, yes.

**Comment by DavidChuks** [comment]
oh it's the wired only version that is supported? wow..thanks for that reply. I was oblivious to that fact

**Comment by tatokis** [comment]
Yes, the wireless K63 has a different protocol. It doesn't matter how it's connected to the computer.

**Comment by DavidChuks** [comment]
Please add that clarification to the list of supported devices so people like me don't get confused. Great job guys. Now I know :(

**Comment by DavidChuks** [comment]
Just came back here to say all the best in your exams! I am having mine too and I know how tough it can be. And hey you haven't disappointed me...you are doing great! keep it up @ZirconiumX
