### ISSUE TITLE
[BUG] K95 not being detected by Mac upon re-connection

### ISSUE THREAD

**Issue by dibstern** [ckb-next/ckb-next#172]
# Bug report

## General information
This is a problem with the program not detecting my keyboard being connected when the keyboard has been disconnected and reconnected.

### Device Information
Currently running Mac OS High Sierra 10.13.4 on a old 2014 Retina Macbook Pro.
K95 Platinum connected to computer via a TP-Link USB 3.0 7-Port Hub with 2 Charging Ports, which is then hooked up to a USB 3.0 extension cord that is connected to a USB-port of the MacBook.

### Source
Pre-built package for macOS, ckb-next 3.0.

## Logs & crash reports

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1990385/ckb-next-dev-detect-report.gz)

## What is the program's current behaviour?
I turn the laptop on with the keyboard connected and it works perfectly. I unplug my laptop and work elsewhere. I come back, plug my USB hub back in, and ckb-next doesn't detect that my K95 is connected. This persists even if I restart the software. I have to restart my laptop to fix the problem.

## What is the expected behaviour of the program?
It should detect that my K95 keyboard has been connected when I reconnect the keyboard.

**Comment by ZirconiumX** [comment]
This might be #155.
