### ISSUE TITLE
A Stop Job is running for Keyboards and Mice

### ISSUE THREAD

**Issue by RomainGsd** [ckb-next/ckb-next#173]
Keyboard : K70
OS : Arch Linux KDE 5.12

My issue is that when I shutdown my computer I got this alarm : "A stop job is running for Corsair Keyboard and Mice", which run during +/-1 minute before really shutdown.

**Comment by tatokis** [comment]
Make sure you run the latest git version. If you still get this, then it's a duplicate of #168, with my guess being that you have a K70 Rapidfire.
