### ISSUE TITLE
Jerky mouse in DXX Rebirth

### ISSUE THREAD

**Issue by tatokis** [ckb-next/ckb-next#174]
Mouse locks into vertical axis when trying to mouselook diagonally on DXX Rebirth.
Possibly an SDL1 issue, or evdev-related. Should try on other SDL1 games.
Should also be tested on a libinput system too.

**Comment by tatokis** [comment]
To make matters even more confusing, an older build of SRB2 using SDL2.0.5 has trouble registering vertical mouse input.
Switching to libinput has no effect.

**Comment by ZirconiumX** [comment]
I really hope this isn't another udev issue. That would suck.
