### ISSUE TITLE
failed to start ckb-next-daemon.service

### ISSUE THREAD

**Issue by qwFaTE** [ckb-next/ckb-next#175]
Hi,
sorry if this is something obvious, but I'm quite new to linux as a whole and need ckb-next for my glaive to actually work. That's all I want it for really.

I'm running MX Linux, which I believe is debian based (but I'm not sure), and after installing the program and running it, it tells me that the daemon isn't running and gives me this command: "sudo systemctl start ckb-next-daemon" to start it once. I gave it a go and I get this message: 

"Failed to start ckb-next-daemon.service: Unknown unit: ckb-next-daemon.service
See system logs and 'systemctl status ckb-next-daemon.service' for details."

I'm guessing the daemon doesn't even exist on my system.

I'm a noob to this stuff and I'd appreciate any help given, all I want is for my mouse to work. Thanks!

**Comment by ZirconiumX** [comment]
That sounds like it didn't install properly; how did you install it?

**Comment by qwFaTE** [comment]
I built from source, following the Ubuntu 16.04+ method in the "Linux Installation" section of this github project. It was the only method I could see that seemed to work for my system.

**Comment by ZirconiumX** [comment]
If you ran `./quickinstall` from the terminal, then paste the output of the
script.

If you tried to do something like double-click the script, then it won't be
able to install the daemon and you'll need to run it from a terminal.

**Comment by qwFaTE** [comment]
Oh right, in that case the build log is:
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- ckb-next version: 0.3.0-9-g33c256d (Non-release)
-- Performing Test C_COMPILER_SUPPORTS_-Og
-- Performing Test C_COMPILER_SUPPORTS_-Og - Success
-- Performing Test CXX_COMPILER_SUPPORTS_-Og
-- Performing Test CXX_COMPILER_SUPPORTS_-Og - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so
-- Checking for module 'libudev'
--   Found libudev, version 232
-- Found UDEV: /lib/x86_64-linux-gnu/libudev.so  
-- Searching for running ckb and/or ckb-next GUI
-- NOTE:
    Privileged access is required for operations upon the daemon at
    configure time as it is owned by root. If this is unacceptable,
    disable SAFE_INSTALL and prepare the filesystem manually.
CMake Warning at src/daemon/CMakeLists.txt:406 (message):
  No supported system service detected.

      Supported services are: systemd, launchd, OpenRC, upstart.


-- Found QuaZip: /usr/lib/x86_64-linux-gnu/libquazip5.so  
-- Found PulseAudioSimple: /usr/lib/x86_64-linux-gnu/libpulse-simple.so  
-- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Generating binary.qrc
-- Importing ckb-next-key.gpg
-- Generating image.qrc
-- Importing ckb-next.png
-- Importing icon_blank.png
-- Importing icon_mode.png
-- Importing icon_mode1.png
-- Importing icon_mode1_hardware.png
-- Importing icon_mode2.png
-- Importing icon_mode2_hardware.png
-- Importing icon_mode3.png
-- Importing icon_mode3_hardware.png
-- Importing icon_plus.png
-- Importing icon_profile.png
-- Importing icon_profile_hardware.png
-- Importing overlay_glaive.png
-- Importing overlay_harpoon.png
-- Importing overlay_katar.png
-- Importing overlay_m65.png
-- Importing overlay_polaris.png
-- Importing overlay_sabre.png
-- Importing overlay_scimitar.png
-- Generating and importing ckb-next.desktop
-- Generating and importing ckb-next.autostart.desktop
-- Importing demoprofile.conf
-- Generating text.qrc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/euan/ckb-next/build
Scanning dependencies of target random
Scanning dependencies of target wave
Scanning dependencies of target pinwheel
Scanning dependencies of target KissFFT
Scanning dependencies of target heat
Scanning dependencies of target ripple
Scanning dependencies of target gradient
Scanning dependencies of target ckb-next-daemon
[  2%] Building C object src/animations/CMakeFiles/heat.dir/heat/main.c.o
[  2%] Building C object src/animations/CMakeFiles/random.dir/random/main.c.o
[  3%] Building C object src/animations/CMakeFiles/pinwheel.dir/pinwheel/main.c.o
[  4%] Building C object src/animations/CMakeFiles/gradient.dir/gradient/main.c.o
[  5%] Building C object src/animations/CMakeFiles/ripple.dir/ripple/main.c.o
[  6%] Building C object src/animations/CMakeFiles/wave.dir/wave/main.c.o
[  7%] Building C object src/libs/kissfft/CMakeFiles/KissFFT.dir/kiss_fft.c.o
[  8%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/command.c.o
[ 10%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device.c.o
[ 11%] Linking C executable ../../bin/pinwheel
[ 12%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device_keyboard.c.o
[ 14%] Linking C executable ../../bin/heat
[ 14%] Linking C executable ../../bin/random
[ 14%] Built target pinwheel
[ 15%] Linking C executable ../../bin/gradient
[ 16%] Building C object src/libs/kissfft/CMakeFiles/KissFFT.dir/kiss_fftr.c.o
[ 17%] Linking C executable ../../bin/wave
[ 17%] Built target heat
[ 17%] Built target random
[ 17%] Built target gradient
[ 19%] Linking C executable ../../bin/ripple
[ 20%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device_mouse.c.o
Scanning dependencies of target rain
Scanning dependencies of target ckb-next_autogen
[ 20%] Built target wave
[ 21%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device_vtable.c.o
[ 22%] Automatic MOC, UIC and RCC for target ckb-next
[ 23%] Building C object src/animations/CMakeFiles/rain.dir/rain/main.c.o
[ 23%] Built target ripple
Generating MOC source EWIEGA46WW/moc_animadddialog.cpp
[ 24%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/devnode.c.o
[ 25%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/dpi.c.o
[ 28%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/keymap.c.o
[ 28%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/input.c.o
[ 29%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/firmware.c.o
[ 30%] Linking C static library libKissFFT.a
[ 31%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led.c.o
[ 31%] Built target KissFFT
[ 32%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led_keyboard.c.o
[ 33%] Linking C executable ../../bin/rain
[ 34%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/keymap_patch.c.o
[ 35%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led_mouse.c.o
Generating MOC source EWIEGA46WW/moc_animscript.cpp
[ 35%] Built target rain
Scanning dependencies of target mviz
[ 37%] Building C object src/animations/mviz/CMakeFiles/mviz.dir/main.c.o
Generating MOC source EWIEGA46WW/moc_animsettingdialog.cpp
[ 38%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led_mousepad.c.o
[ 39%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/main.c.o
Generating MOC source EWIEGA46WW/moc_ckbsettingswriter.cpp
[ 40%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/notify.c.o
[ 41%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/usb.c.o
[ 43%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/profile.c.o
[ 43%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/profile_keyboard.c.o
[ 44%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/profile_mouse.c.o
/home/euan/ckb-next/src/animations/mviz/main.c: In function 'ckb_parameter':
/home/euan/ckb-next/src/animations/mviz/main.c:71:33: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
  CKB_PARSE_BOOL("power", &power);
                                 ^
/home/euan/ckb-next/src/animations/mviz/main.c: In function 'ckb_frame':
/home/euan/ckb-next/src/animations/mviz/main.c:141:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(unsigned int i = lowi; i <= highi; i++)
                                ^~
/home/euan/ckb-next/src/animations/mviz/main.c:140:16: warning: unused variable 'height' [-Wunused-variable]
   unsigned int height = context->height;
                ^~~~~~
Generating MOC source EWIEGA46WW/moc_colorbutton.cpp
[ 46%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/usb_linux.c.o
Generating MOC source EWIEGA46WW/moc_extrasettingswidget.cpp
[ 47%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/input_linux.c.o
Generating MOC source EWIEGA46WW/moc_fwupgradedialog.cpp
[ 48%] Linking C executable ../../../bin/mviz
Generating MOC source EWIEGA46WW/moc_gradientbutton.cpp
[ 48%] Built target mviz
Generating MOC source EWIEGA46WW/moc_gradientdialog.cpp
[ 49%] Linking C executable ../../bin/ckb-next-daemon
[ 49%] Built target ckb-next-daemon
Generating MOC source EWIEGA46WW/moc_gradientdialogwidget.cpp
Generating MOC source EWIEGA46WW/moc_kb.cpp
Generating MOC source EWIEGA46WW/moc_kbanim.cpp
Generating MOC source EWIEGA46WW/moc_kbanimwidget.cpp
Generating MOC source EWIEGA46WW/moc_kbbind.cpp
Generating MOC source EWIEGA46WW/moc_kbbindwidget.cpp
Generating MOC source EWIEGA46WW/moc_kbfirmware.cpp
Generating MOC source EWIEGA46WW/moc_kblight.cpp
Generating MOC source EWIEGA46WW/moc_kblightwidget.cpp
Generating MOC source EWIEGA46WW/moc_kbmanager.cpp
Generating MOC source EWIEGA46WW/moc_kbmode.cpp
Generating MOC source EWIEGA46WW/moc_kbperf.cpp
Generating MOC source EWIEGA46WW/moc_kbprofile.cpp
Generating MOC source EWIEGA46WW/moc_kbprofiledialog.cpp
Generating MOC source EWIEGA46WW/moc_kbwidget.cpp
Generating MOC source EWIEGA46WW/moc_keyaction.cpp
Generating MOC source EWIEGA46WW/moc_keywidget.cpp
Generating MOC source EWIEGA46WW/moc_kperfwidget.cpp
Generating MOC source EWIEGA46WW/moc_macroreader.cpp
Generating MOC source EWIEGA46WW/moc_mainwindow.cpp
Generating MOC source EWIEGA46WW/moc_modeselectdialog.cpp
Generating MOC source EWIEGA46WW/moc_mperfwidget.cpp
Generating MOC source EWIEGA46WW/moc_rebindwidget.cpp
Generating MOC source EWIEGA46WW/moc_rlistwidget.cpp
Generating MOC source EWIEGA46WW/moc_settingswidget.cpp
Generating MOC compilation mocs_compilation.cpp
Generating UIC header include/ui_animadddialog.h
Generating UIC header include/ui_animsettingdialog.h
Generating UIC header include/ui_extrasettingswidget.h
Generating UIC header include/ui_fwupgradedialog.h
Generating UIC header include/ui_gradientdialog.h
Generating UIC header include/ui_kbanimwidget.h
Generating UIC header include/ui_kbbindwidget.h
Generating UIC header include/ui_kblightwidget.h
Generating UIC header include/ui_kbprofiledialog.h
Generating UIC header include/ui_kblightwidget.h
Generating UIC header include/ui_kbwidget.h
Generating UIC header include/ui_kperfwidget.h
Generating UIC header include/ui_mainwindow.h
Generating UIC header include/ui_modeselectdialog.h
Generating UIC header include/ui_mperfwidget.h
Generating UIC header include/ui_rebindwidget.h
/home/euan/ckb-next/src/gui/rebindwidget.ui: Warning: The name 'layoutWidget' (QWidget) is already in use, defaulting to 'layoutWidget2'.
Generating UIC header include/ui_settingswidget.h
Generating RCC source EJRQKI7XPS/qrc_binary.cpp
Generating RCC source EJRQKI7XPS/qrc_image.cpp
Generating RCC source EJRQKI7XPS/qrc_text.cpp
[ 49%] Built target ckb-next_autogen
Scanning dependencies of target ckb-next
[ 50%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/animadddialog.cpp.o
[ 51%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/ckbsettingswriter.cpp.o
[ 53%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/animscript.cpp.o
[ 55%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/animsettingdialog.cpp.o
[ 55%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/ckbsettings.cpp.o
[ 57%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/colorbutton.cpp.o
[ 57%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/autorun.cpp.o
[ 58%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/colormap.cpp.o
[ 59%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/extrasettingswidget.cpp.o
[ 60%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/fwupgradedialog.cpp.o
[ 61%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/gradientbutton.cpp.o
[ 62%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/gradientdialog.cpp.o
[ 64%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/gradientdialogwidget.cpp.o
[ 65%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbanim.cpp.o
[ 66%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbanimwidget.cpp.o
[ 67%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbbind.cpp.o
[ 68%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbbindwidget.cpp.o
[ 69%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kb.cpp.o
[ 70%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbfirmware.cpp.o
[ 71%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kblight.cpp.o
[ 73%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kblightwidget.cpp.o
[ 74%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbmanager.cpp.o
[ 75%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbmode.cpp.o
[ 76%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbperf.cpp.o
[ 77%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbprofile.cpp.o
[ 78%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbprofiledialog.cpp.o
[ 79%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kbwidget.cpp.o
[ 80%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/keyaction.cpp.o
[ 82%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/keymap.cpp.o
[ 83%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/keywidget.cpp.o
[ 84%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/kperfwidget.cpp.o
[ 85%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/macroreader.cpp.o
[ 86%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/main.cpp.o
[ 87%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/mainwindow.cpp.o
[ 88%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/modeselectdialog.cpp.o
[ 89%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/mperfwidget.cpp.o
[ 91%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/rebindwidget.cpp.o
[ 92%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/rlistwidget.cpp.o
[ 93%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/settingswidget.cpp.o
[ 94%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/media_linux.cpp.o
[ 95%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/ckb-next_autogen/mocs_compilation.cpp.o
[ 96%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/ckb-next_autogen/EJRQKI7XPS/qrc_binary.cpp.o
[ 97%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/ckb-next_autogen/EJRQKI7XPS/qrc_text.cpp.o
[ 98%] Building CXX object src/gui/CMakeFiles/ckb-next.dir/ckb-next_autogen/EJRQKI7XPS/qrc_image.cpp.o
[100%] Linking CXX executable ../../bin/ckb-next
[100%] Built target ckb-next
[ 26%] Built target ckb-next-daemon
[ 30%] Built target KissFFT
[ 32%] Built target pinwheel
[ 34%] Built target random
[ 37%] Built target heat
[ 39%] Built target gradient
[ 41%] Built target ripple
[ 43%] Built target wave
[ 46%] Built target rain
[ 48%] Built target mviz
[ 49%] Automatic MOC, UIC and RCC for target ckb-next
[ 49%] Built target ckb-next_autogen
[100%] Built target ckb-next
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/ckb-next-daemon
-- Up-to-date: /etc/udev/rules.d/99-ckb-daemon.rules
-- Installing: /usr/lib/cmake/ckb-next/Animation/AnimationTargets.cmake
-- Up-to-date: /usr/lib/cmake/ckb-next/Animation/AnimationConfig.cmake
-- Installing: /usr/lib/cmake/ckb-next/Animation/AnimationConfigVersion.cmake
-- Installing: /usr/local/libexec/ckb-next-animations/gradient
-- Installing: /usr/local/libexec/ckb-next-animations/heat
-- Installing: /usr/local/libexec/ckb-next-animations/pinwheel
-- Installing: /usr/local/libexec/ckb-next-animations/rain
-- Installing: /usr/local/libexec/ckb-next-animations/random
-- Installing: /usr/local/libexec/ckb-next-animations/ripple
-- Installing: /usr/local/libexec/ckb-next-animations/wave
-- Installing: /usr/local/libexec/ckb-next-animations/mviz
-- Installing: /usr/local/bin/ckb-next
-- Installing: /usr/local/share/applications/ckb-next.desktop
-- Up-to-date: /usr/local/share/icons/hicolor/512x512/apps/ckb-next.png
Done.
Thank you for installing ckb-next!

**Comment by ZirconiumX** [comment]
>CMake Warning at src/daemon/CMakeLists.txt:406 (message):

No supported system service detected.

>  Supported services are: systemd, launchd, OpenRC, upstart.


The script couldn't detect that you were using systemd.

This sounds like a distro quirk, I'll have to investigate.

**Comment by qwFaTE** [comment]
Alright thanks man. :)

**Comment by ZirconiumX** [comment]
As a temporary workaround, if you look in the `build/bin` folder, you'll
find `ckb-next-daemon`. Run `sudo nohup ./ckb-next-daemon`, and your Glaive
should work. The `nohup` is so that you can close the terminal without
breaking your mouse.

**Comment by qwFaTE** [comment]
Awesome! Thanks for the help dude, I really appreciate it!

**Comment by ZirconiumX** [comment]
We've been in your shoes, so we know the importance of being helpful. It's
the least we can do to thank you for using CKB.

On 14 May 2018 12:43, "qwFaTE" <notifications@github.com> wrote:

Awesome! Thanks for the help dude, I really appreciate it!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ckb-next/ckb-next/issues/175#issuecomment-388788397>,
or mute the thread

**Comment by tatokis** [comment]
Can you run `ls /run`, `ls /run/systemd` and post the output?
Also, please use markdown quotes for quote blocks.

**Comment by qwFaTE** [comment]
Okay, so I got this from running ls /run:

> acpid.pid      console-setup       lightdm         rpcbind          sm-notify.pid
acpid.socket   crond.pid           lightdm.pid     rpcbind.lock     systemd
acpi_fakekey   crond.reboot        lock            rpcbind.pid      systemd-shim-state
agetty.reload  cups                motd.dynamic    rpcbind.sock     tlp
alsa           dbus                mount           rpc_pipefs       udev
atd.pid        dhclient6-eth0.pid  network         rpc.statd.pid    udisks2
avahi-daemon   dhclient-eth0.pid   NetworkManager  rsyslogd.pid     user
blkid          haveged.pid         ntpd.pid        samba            utmp
cgmanager      initctl             openvpn         sendsigs.omit.d
cgmanager.pid  initramfs           resolvconf      shm


And this from ls /run/systemd/:

> inhibit  seats  sessions  users

Hopefully that's helpful, though I'm not sure what markdown quotes are exactly, so sorry if I got that wrong.

**Comment by ZirconiumX** [comment]
Markdown quotes use ` (backticks) around them.

GitHub has a guide here:
https://guides.github.com/features/mastering-markdown/

**Comment by tatokis** [comment]
I pushed a commit that should fix this https://github.com/ckb-next/ckb-next/commit/7fe024e81cad4641abe2a9445a7d877c49a973c7 .

Can you try quickinstall with the new code, reboot, and then see if it works on boot?

**Comment by qwFaTE** [comment]
It still doesn't seem to work.

**Comment by ZirconiumX** [comment]
```
-- systemd detected
-- Generating and importing ckb-next-daemon.service (systemd)
Failed to retrieve unit: No such method 'GetUnit'
Failed to get unit file state for ckb-daemon.service: Unknown error 1349259488
Failed to retrieve unit: No such method 'GetUnit'
enabled
```
Now, ckb-next uses systemd to generate a config file, but MX Linux uses a fake systemd, which appears to not support this feature, so we need a different approach. It probably involves us writing a sysvinit script, which is going to be fun (it was deprecated for a reason).

**Comment by qwFaTE** [comment]
Oh man, sorry about this! Didn't think it'd need this much work. D:

Thanks very much though. :)

**Comment by OvermindDL1** [comment]
Huh, did some reading about mxlinux and I'm really not liking a few things about it...

However, it looks like you can setup real systemd in it, instructions at:  https://mxlinux.org/wiki/system/systemd

There only argument against it is that it is 'not the unix way', yeah sure but `init` being simple is what gave us the horrors of sysvinit, systemd is much faster, more capable, actually supports modern hardware things like, oh, hotswapping USB natively (which ckb uses via udev) among others, things that are *very* hard or impossible to tack-on to sysvinit...

I'm not a fan of this distro it seems...  >.>

**Comment by tatokis** [comment]
@OvermindDL1 I don't think this is the right thread for this.
That said, I am working on a script.
Also, for a distro that has a manual that says "systemd installations are not officially supported", I wouldn't suggest doing something like this to someone who is pretty new to this.

**Comment by tatokis** [comment]
@qwFaTE Please try with the latest code.

**Comment by OvermindDL1** [comment]
Heh, sorry yeah, I was just curious why it seemed to have some systemd commands but was not systemd, it appears they made a systemd-shim(s?) thing, which seems completely point defeating to me...  But as I found out how to setup actual systemd I figured linking that might be useful (with a disclaimer about their disclaimer).  They state it is not officially supported because the dev's of that distro do not like systemd for non-technical reasons.

**Comment by qwFaTE** [comment]
@tatokis Amazing man, works perfectly!

Thanks for this, I'm really sorry for the extra work you had to go through for this. It's really appreciated.

Have a great day! :)

**Comment by ZirconiumX** [comment]
I'm so glad it works. We were dreading having to write an init script, but it doesn't seem to be too painful.

Take care, and have a good day yourself!

**Comment by robabby** [comment]
Apologies for reviving a dead issue, and happy to create a new ticket if you prefer, but I just came across this issue on Ubuntu 18.04.2.  I had this library working just fine until I had to re-install my OS due to upgrading my Video Card.  Now the install is failing with this error.  

I attempted the following the recommendation, but there is no `build/bin` folder, just `build/src`:
> As a temporary workaround, if you look in the `build/bin` folder, you'll find `ckb-next-daemon`. Run `sudo nohup ./ckb-next-daemon`, and your Glaive should work. The `nohup` is so that you can close the terminal without breaking your mouse.

Here is my install log:
```
➜  ckb-next git:(master) sudo ./quickinstall                                                                                                          
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- ckb-next version: 0.4.0-9-gfd509f5 (Non-release)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so
-- Checking for module 'libudev'
--   Found libudev, version 237
-- Found UDEV: /lib/x86_64-linux-gnu/libudev.so  
-- Searching for running ckb and/or ckb-next GUI
-- NOTE:
    Privileged access is required for operations upon the daemon at
    configure time as it is owned by root. If this is unacceptable,
    disable SAFE_INSTALL and prepare the filesystem manually.
-- systemd detected
-- Generating and importing ckb-next-daemon.service (systemd)
inactive
Failed to get unit file state for ckb-daemon.service: No such file or directory
inactive
Failed to get unit file state for ckb-next-daemon.service: No such file or directory
-- Found QuaZip: /usr/lib/x86_64-linux-gnu/libquazip5.so  
-- Found PulseAudioSimple: /usr/lib/x86_64-linux-gnu/libpulse-simple.so  
-- Found PulseAudio: /usr/lib/x86_64-linux-gnu/libpulse.so  
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:27 (message):
  The imported target "Qt5::Gui" references the file

     "/usr/lib/x86_64-linux-gnu/libEGL.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:50 (_qt5_Gui_check_file_exists)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:72 (_qt5gui_find_extra_libs)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:184 (include)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:101 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  src/gui/CMakeLists.txt:72 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/rob/Workbench/ckb-next/build/CMakeFiles/CMakeOutput.log".
See also "/home/rob/Workbench/ckb-next/build/CMakeFiles/CMakeError.log".
An error occurred,
press enter to exit.
```

**Comment by ZirconiumX** [comment]
By the looks of it you need to install EGL from wherever you're getting
your drivers.

**Comment by robabby** [comment]
@ZirconiumX My video card drivers?  I installed the Nvidia drivers from source.

**Comment by ZirconiumX** [comment]
Definitely do not do that on Ubuntu. Use one of the Ubuntu provided
packages instead.

**Comment by robabby** [comment]
@ZirconiumX I tried that, but had a hell oif a time getting them to work with the newer RTX card.  It was a real pain the butt.

**Comment by ZirconiumX** [comment]
Using the graphics-drivers PPA?

**Comment by robabby** [comment]
@ZirconiumX yes.  Wound up having to follow this guide:
https://medium.com/@avinchintha/how-to-install-nvidia-drivers-and-cuda-10-0-for-rtx-2080-ti-gpu-on-ubuntu-16-04-18-04-ce32e4edf1c0

**Comment by ZirconiumX** [comment]
Honestly Ubuntu problems are not my forté, that's @tatokis's department,
but he's currently asleep. Either way the build is failing because your
graphics drivers are not properly installed, not because of any issue on
our end.

**Comment by robabby** [comment]
@ZirconiumX Whelp, that is good to know that the problem is straightforward.  Thank you for your time.

Given the hellish time I had getting this new card working, I did not install the CUDA package for the card because frankly I was pretty tired fo the graphics issues and was happy enough when things started working and looking correct.  Would installing the CUDA packages resolve this issue?

**Comment by ZirconiumX** [comment]
Well, the main use of EGL is actually Wayland, so that's what you'll be
looking for.

**Comment by robabby** [comment]
In case anyone comes here after me, I was able to get the Nvidia PPA drivers working following the **How to Install the Latest Version Of Nvidia Drivers** of this article:

https://www.linuxbabe.com/ubuntu/install-nvidia-driver-ubuntu-18-04

`ckb-next` is up and running just fine :+1:

**Comment by phpbbireland** [comment]
After following the install guidelines using git (22nd May 2019) my MX build appears to work fine with one small little issue... 

***Booting/Shutdown:***  A start job (and stop job) for Corsair Keyboard / Mouse timed out... takes an extra minute and a half to boot and shut down due to time out but everything else appears to work perfectly...

**Log:** Timed out waiting for device /dev/disk/by-uuid/edf401fd-blahblah ...

**Comment by gmgrigsby** [comment]
Apologies for posting in this old thread, but facing the same issue on my wife's computer running MX Linux 23.3. Was the final solution to enable Systemd for qwFaTE or is there now a script available that will work with SysV init?

Thanks in advance.
