### ISSUE TITLE
How to upgrade to ckb-next daemon?

### ISSUE THREAD

**Issue by octillery143** [ckb-next/ckb-next#177]
# Before you proceed

- Read the [wiki](https://github.com/ckb-next/ckb-next/wiki).
- Try the latest code by building the software manually.
- Search in

---

# Devices information

Open a terminal and execute:
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
```

Upload `ckb-next-dev-detect-report.gz` with this issue.

---

# New device support request

Upload:
  * Linux:
    * `ckb-next-dev-detect-report.gz` from the section above
  * macOS:
    * `ckb-next-dev-detect-report.gz` from the section above
    * full USB bus dump by following [the instructions](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# Feature request

## Any other notes & comments?

---

# Bug report

## Logs & crash reports

Upload:
 * `ckb-next-dev-detect-report.gz` from the section above
 * any additional crash reports you've managed to gather

## What is the program's current behavior?
does not detect my mouse (M65 RGB PRO)
## What is the expected behavior of the program?
to access RGB settings and macros for my mouse
## Any other notes & comments?
I get a warning saying to update ckb-next-daemon and a driver mismatch.
---

# Something else

**Comment by tatokis** [comment]
Sorry, what?

**Comment by octillery143** [comment]
im new, but it says to upgrade ckb-next-daemon with a warning about a driver mismatch.

**Comment by octillery143** [comment]
(beta-0.2.6)

**Comment by tatokis** [comment]
Which operating system are you running?
Which OS version?
How did you install ckb?
How did you install ckb-next?
Have you tried rebooting?

Next time please describe your issue better, your setup, and what steps you have taken.

**Comment by octillery143** [comment]
im running macOS high sierra 10.13.4
i did not installed ckb, i installed ckb-next with the pre-made package that was provided
and i did try rebooting

**Comment by octillery143** [comment]
ill try again.

**Comment by tatokis** [comment]
The latest version is 0.3.0, so uninstall any old versions you had installed. And install https://github.com/ckb-next/ckb-next/releases/download/v0.3.0/ckb-next_v0.3.0.dmg

**Comment by octillery143** [comment]
Thank you, i did and rebooted and now its working.

**Comment by MordicusEtCubitus** [comment]
Here is my file to support my new device : ironclaw mouse wireless, connected on usb port using cable at the moment of building the report

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/4365243/ckb-next-dev-detect-report.gz)
