### ISSUE TITLE
Fedora 27 issue with ckb daemon not starting

### ISSUE THREAD

**Issue by AngelusDulcis** [ckb-next/ckb-next#178]
Logs are attached, I think I saw a closed issue with this earlier but the latest version doesn't resolve it for me. 
systemctl start ckb-next-daemon
Job for ckb-next-daemon.service failed because the control process exited with error code.

systemctl enable ckb-next-daemon
Failed to enable unit: Unit /run/systemd/generator.late/ckb-next-daemon.service is transient or generated.

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2013066/ckb-next-dev-detect-report.gz)

![ckbnope](https://user-images.githubusercontent.com/19696869/40176517-3d465b50-59a1-11e8-97af-055bff45112f.png)

**Comment by tatokis** [comment]
Try `sudo rm /etc/init.d/ckb-next-daemon.sh` and see if that makes it start

**Comment by AngelusDulcis** [comment]
systemctl start ckb-next-daemon
Failed to start ckb-next-daemon.service: Access denied
See system logs and 'systemctl status ckb-next-daemon.service' for details.

systemctl status ckb-next-daemon.service
Failed to get properties: Access denied


enable ckb-next-daemon
Failed to enable unit: Unit /run/systemd/generator.late/ckb-next-daemon.service is transient or generated.

**Comment by tatokis** [comment]
Use sudo systemctl if you aren't doing so. Need to be root.

**Comment by AngelusDulcis** [comment]
I'm in a root session, I'm sorry I should have clarified that.

**Comment by tatokis** [comment]
Try the latest code from master with quickinstall. That should fix it.
Make sure /etc/init.d/ckb-next-daemon.sh doesn't exist both before and after.

**Comment by AngelusDulcis** [comment]
There was the magic, installed it again rebooted and we're up right as rain. Thank you @tatokis !
