### ISSUE TITLE
A startup job is running for corsair keyboard and mice

### ISSUE THREAD

**Issue by Crait1** [ckb-next/ckb-next#179]
Hello everyone, 

I installed ckb-next, everything works fine. (Great job btw). Anyways, when I want to shutdown my pc, I always get "A startup job is running for corsair keyboard and mice (time pased/1:30min)". I have the corsair k70 rgb rapidfire keyboard. However, when I use bios mode, everythings works fine (no startup job), but the rgb doesn't work anymore. 
Thanks for the answers in advance.

**Comment by tatokis** [comment]
Please drop by on IRC again. Sorry, missed you, however this issue is a duplicate.
