### ISSUE TITLE
RGB settings not going the way it wanted

### ISSUE THREAD

**Issue by octillery143** [ckb-next/ckb-next#180]
# Before you proceed

- Read the [wiki](https://github.com/ckb-next/ckb-next/wiki).
- Try the latest code by building the software manually.
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
- File unrelated issues separately.
- Use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to format the message.
- There are 3 types of issues: new device, feature, bug. Use only one. Delete redundant sections before sending.
bug
---

# Devices information

Open a terminal and execute:
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
```

Upload `ckb-next-dev-detect-report.gz` with this issue.

---

# New device support request

Upload:
  * Linux:
    * `ckb-next-dev-detect-report.gz` from the section above
  * macOS:
    * `ckb-next-dev-detect-report.gz` from the section above
    * full USB bus dump by following [the instructions](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# Feature request

## Any other notes & comments?

---

# Bug report

### Source
 Prebuilt package

## Logs & crash reports

Upload:
 * `ckb-next-dev-detect-report.gz` from the section above
 * any additional crash reports you've managed to gather

## What is the program's current behavior?
RGB settings differ from whats on the screen
## What is the expected behavior of the program?
RGB lighting should be same as whats on the screen
## Any other notes & comments?
my Corsair m65 pro rgb color scheme is red, while on screen its mint and purple.
i run a Mac Mini MacOS high sierra 10.13.4
---

# Something else
also, if you can can you tell me how to work the macros for my mouse? it only runs one key at a time instead of complex key presses.

**Comment by ZirconiumX** [comment]
This has been left unanswered because we couldn't tell what it is you're asking us.
