### ISSUE TITLE
"No Devices connected" everytime the computer gets put into sleep.

### ISSUE THREAD

**Issue by BillBurns1** [ckb-next/ckb-next#184]
So first off, when this works it is a fantastic program!! Thank you. The problem i am running into is whenever i put my Mac Mini running OS 10.13.4 into sleep mode, ckb-next stops, working telling me there are no devices. i have tried restarting and reinstalling. Reinstall works until computer goes into sleep mode, at least i think sleep mode is the problem. I am using a Corsair Strafe RGB. When it says no devoce connected my WASD and left, right, up and down arrows are white and the rest of the keyboard is red, the corsair logo is yellow, the num lock, caps lock and scroll lock are off and will not come on by pressing however still work. Hope this is all you guys need to sus out whats going on, thanks in advance,
Bill

**Comment by tatokis** [comment]
Open a terminal and execute:
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
```

Then upload `ckb-next-dev-detect-report.gz`

**Comment by BillBurns1** [comment]
I'm really sorry but i don't know how to do all that? could you elaborate?

**Comment by BillBurns1** [comment]
Never mind, googles a good thing!! here you go.
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2064254/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
Can you install this version, reboot, and see if the problem persists?
http://ckb-next.info/mac/ckb-next_v0.3.0-19-g80f672f-old-media-mac.dmg

**Comment by breckenedge** [comment]
I also had this problem. The updated .dmg worked. Here's my device report: [ckb-next-dev-detect-report.txt](https://github.com/ckb-next/ckb-next/files/2077315/ckb-next-dev-detect-report.txt)

**Comment by ark4peace** [comment]
@tatokis I had the same problem (program "loosing" the devices), installed the dmg, and it works now.

**Comment by Xalior** [comment]
I can confirm I had this problem with a K70 Lux under Sierra, the build above fixed it, but introduced other issues (random mouseclicks not noticed by finder) but the build in https://github.com/ckb-next/ckb-next/issues/186#issuecomment-394566227 seems to have solved both that, and this bug.

I still, sometimes, have to reboot to get my animations & input back, but that has only happened to me once on build 31 so far...

-Dx

**Comment by ZirconiumX** [comment]
We have plans to release 0.3.1 soon after exams. Build 31 uses Karabiner as
its input backend, because Mac OS X has become a difficult platform for
userspace input.

**Comment by ZirconiumX** [comment]
Since 0.3.1 has been out for a year, closing as stale.
