### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by hevanaa** [ckb-next/ckb-next#190]
Not sure how to update the wiki in this project, but here is a change I would like to have.

On https://github.com/ckb-next/ckb-next/wiki/Linux-Installation, change from

- Fedora 24-26, CentOS/RHEL 7 (maintained by @hevanaa):

  - [johanh/ckb](https://copr.fedorainfracloud.org/coprs/johanh/ckb/) - based on master branch

to 

- Fedora, CentOS/RHEL (maintained by @hevanaa):

  - [johanh/ckb](https://copr.fedorainfracloud.org/coprs/johanh/ckb/) - based on the latest GitHub release

**Comment by tatokis** [comment]
Done
