### ISSUE TITLE
Disable keyboard binding on ckb-next for macOS

### ISSUE THREAD

**Issue by ExtremeProgrammerPro** [ckb-next/ckb-next#192]
Hi there, I have a question about keyboard binding. Is there any way I can use ckb-next without it binding to my keyboard? Maybe a flag I don't know about? I am asking because it is causing several problems on macOS (such as issue #138 as well as others) and I had no problems before installing ckb-next. I don't need the features that the software provides as I am mainly using it to control my Corsair MM800 mousepad. Can I use this application alongside the standard mac keyboard functionality? I have a Corsair K70R keyboard. Thanks in advance.

**Comment by tatokis** [comment]
It's not possible, no.
However, all of these issues will be resolved in the next release with the karabiner backend.
