### ISSUE TITLE
macOS console getting hammered with errors non stop

### ISSUE THREAD

**Issue by kchen13** [ckb-next/ckb-next#193]
While the program works fine my console is non stop writing logs of an error. I'm not sure what is causing this. Seems to have something to do with com.apple.coreaudio and ckb. These 3 errors below just constantly keep writing to the console logs.

default	06:22:20.393704 -0400	ckb-next	HALC_ProxyObject.cpp:419:GetPropertyData:  HALC_ProxyObject::GetPropertyData ('bcvl', 'glob', 0): bad property size for DI32

error	06:22:20.393740 -0400	ckb-next	HALC_ShellObject.cpp:401:GetPropertyData:  HALC_ShellObject::GetPropertyData: call to the proxy failed, Error: 561211770 (!siz)

error	06:22:20.393756 -0400	ckb-next	HALPlugIn.cpp:292:ObjectGetPropertyData:  HALPlugIn::ObjectGetPropertyData: got an error from the plug-in routine, Error: 561211770 (!siz)

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2127252/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
This has been fixed in master by https://github.com/ckb-next/ckb-next/commit/93f34db7b48934e2e49473ad169e5536670ad539 .
There's a build in #183 that doesn't have this issue, but the fix will be in the next release.

**Comment by kchen13** [comment]
Thanks a lot, that indeed fixed my problems. Sorry I couldn't find that solutions myself, didn't even think of it being a mute button issue.

**Comment by tatokis** [comment]
No worries
