### ISSUE TITLE
Strafe/K70 MK.2

### ISSUE THREAD

**Issue by ZirconiumX** [ckb-next/ckb-next#196]
We caught these well in advance, and we have the USB IDs already, but it seems these are [finally rolling out to market](https://www.kitguru.net/peripherals/briony-hannam/corsair-strafe-rgb-mk-2-keyboard-review/).

With that in mind:
- The Strafe MK.2 can probably use the existing Strafe GUI image.
- The K70 MK.2 will need a new GUI config, or possibly we can hack one as needed.

And, as always: **we need testers**.

**Comment by drahenshaw** [comment]
As someone who is interested in using the new MK.2 for Mac, what is the best way to help / test for these projects?

**Comment by tatokis** [comment]
You can start off by running ckb-next-dev-detect, attaching the report, and joining us on our IRC room.

**Comment by platypython** [comment]
I have the K70 MK.2. Attached is a report.
[ckb-next-report-1532721718.gz](https://github.com/ckb-next/ckb-next/files/2237094/ckb-next-report-1532721718.gz)

**Comment by tatokis** [comment]
@platypython Can you also run USB Prober and send the report? Once you do, I will add support for the device and give you code to test.

You can follow this. https://superuser.com/questions/781982/how-can-i-install-usb-prober-from-the-developer-sdk-on-mac-os-x#814339

As a sidenote, do NOT install any of the kexts included in usb prober as that will ruin your system.

**Comment by tatokis** [comment]
I have added support for the K70 RGB MK2 (and possibly the SE) in the mk2 branch.
It would be appreciated if someone could test it and make sure both logo lights function normally.

**Comment by ZirconiumX** [comment]
@k70rgbmk2 conveniently happens to have just that keyboard. Now we just need to check a Strafe.

**Comment by platypython** [comment]
I see the two new logo lights in the keyboard layout, but they aren't working for me to toggle.

**Comment by tatokis** [comment]
Is this from the master branch?

**Comment by platypython** [comment]
mk2 branch

**Comment by tatokis** [comment]
Try creating a new profile in the GUI

**Comment by tatokis** [comment]
Do switch to master too, mk2 is out of date.

**Comment by platypython** [comment]
All fixed. Works great, K70 RGB MK2 fully functional.

**Comment by tatokis** [comment]
CC @k70rgbmk2. Logo should be working now. You probably need to create new profiles. Sorry

**Comment by Wisssard** [comment]
I have a corsair strafe mk 2. Here's the file
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2259805/ckb-next-dev-detect-report.gz)

**Comment by ZirconiumX** [comment]
@Wisssard Can you try again with the `mk2` branch?

**Comment by Wisssard** [comment]
still dosn't work

[ckb-next-report-1533419486.gz](https://github.com/ckb-next/ckb-next/files/2259842/ckb-next-report-1533419486.gz)

**Comment by ZirconiumX** [comment]
Actually, despite what you might think, it is almost working:
```
Aug 04 23:50:38.724265 wiz-pc ckb-next-daemon[28233]:     ckb-next: Corsair RGB driver 0.3.1-unknown
Aug 04 23:50:38.724515 wiz-pc ckb-next-daemon[28233]: [I] Root controller ready at /dev/input/ckb0
Aug 04 23:50:38.829761 wiz-pc ckb-next-daemon[28233]: [I] Connecting CORSAIR STRAFE RGB MK.2 Mechanical Gaming Keyboard at /dev/input/ckb1
Aug 04 23:50:38.989685 wiz-pc ckb-next-daemon[28233]: [I] Starting input thread for /dev/input/ckb1
Aug 04 23:50:39.105300 wiz-pc ckb-next-daemon[28233]: [E] getfwversion (firmware.c:27): Bad input header
Aug 04 23:50:39.105300 wiz-pc ckb-next-daemon[28233]: [W] _start_dev (device.c:43): Unable to load firmware version/poll rate
Aug 04 23:50:39.105389 wiz-pc ckb-next-daemon[28233]: [I] Setup finished for /dev/input/ckb1
```
But the GUI doesn't currently have a layout for the Strafe Mk.2, so the GUI comes up as empty.

I think I need to add it to `IS_V3_OVERRIDE` for the daemon to work properly, which is a five-minute fix.

**Comment by Wisssard** [comment]
cool thanks

**Comment by Wisssard** [comment]
![ss-2018-08-05-00-30-50](https://user-images.githubusercontent.com/42100494/43680955-dc07934c-9846-11e8-92bf-dc876c2b4e68.png)
Is it supposed to be like this?

**Comment by ZirconiumX** [comment]
It will be like that for the moment. The Strafe Mk.2 needs its own unique
GUI layout to use all of the lights. As a compromise, if you run `sed -i
"s/strafe_mk2/k70mk2/" /dev/input/ckb1/features` then the GUI will show the
keyboard as a K70 Mk.2, which is close enough for now.

Would you mind taking another ckb-next-dev-detect?

**Comment by Wisssard** [comment]
i did the command and after trying to change the lightning it no longer responds to key presses.

**Comment by Wisssard** [comment]
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2259875/ckb-next-dev-detect-report.gz)

**Comment by ZirconiumX** [comment]
So, it appears that Corsair are somehow seriously fucking over CKB. This is
going to require you to come join us in IRC, because something is seriously
wrong here.

**Comment by ZirconiumX** [comment]
At the top of the readme is a blue button that says "#irc: freenode". Click
it and it'll put you on a Web client that connects to our IRC channel. Note
there's a short delay of about 30 seconds before you can talk because we've
been under a spambot attack.

**Comment by Wisssard** [comment]
ok im in

**Comment by tatokis** [comment]
Sure!
