### ISSUE TITLE
Incorrect max DPI for certain mice

### ISSUE THREAD

**Issue by tatokis** [ckb-next/ckb-next#197]
Some mice like the glaive have a max DPI (16000) > 12000, which is the current hardcoded maximum.

Maybe we can read the max dpi from the device somehow (hidden in 0x0e01?), or at least make a list in the daemon with hardcoded maximums for each device to be exposed for the GUI.

**Comment by ZirconiumX** [comment]
The M65 Pro goes up to 16k too.

**Comment by tatokis** [comment]
I have added a hardcoded list of max DPIs in the daemon which the GUI then reads.
https://github.com/ckb-next/ckb-next/commit/fb96df0b809d0b2d1dca12d79aeacfeae4164011

Please test the `device-dpi` branch and report if the max DPI is set correctly for your mouse.

**Comment by tatokis** [comment]
Merged to master
