### ISSUE TITLE
Random SIGSEGVs (QSocketNotifier::setEnabled())

### ISSUE THREAD

**Issue by ckb-next-bot** [ckb-next/ckb-next#2]
<a href="https://github.com/fgblomqvist"><img src="https://avatars3.githubusercontent.com/u/649260?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fgblomqvist](https://github.com/fgblomqvist)**
_Sunday Jan 29, 2017 at 20:24 GMT_
_Originally opened as https://github.com/mattanger/ckb-next/issues/47_

----

This error happened in the same way in the original ckb as well (the latest one available there). Upgraded to ckb-next last week (like Jan 26) but it didn't go away.

Let me know if there are any logs I can provide you with. It just happens randomly, but every day for sure.

**Comment by ZirconiumX** [comment]
Since this is an old bug, we're going to close it. If you can reproduce it, we'd welcome a reply.
