### ISSUE TITLE
sabre mouse

### ISSUE THREAD

**Issue by deanbolt** [ckb-next/ckb-next#204]
i downloaded latest version and i played around with the settings now and my left click will only work sometimes, won't switch tabs etc how do i hard reset it back to the way it came out the box, i reset everything on ckb-next and it won't fix ive tried unplugging plugging back in with both clicks pushed in and still won't fix it. please help

**Comment by ZirconiumX** [comment]
Did it do this before you installed ckb?

**Comment by ZirconiumX** [comment]
Also, what OS are you on?

**Comment by deanbolt** [comment]
high seria and no it didn't do it before hand

**Comment by deanbolt** [comment]
ive unistalled ckb and its still doing it.

**Comment by ZirconiumX** [comment]
Did you reboot?

**Comment by tatokis** [comment]
Try installing this version, make sure you **allow system software**  in Security and Privacy **after** installation, and then reboot.

http://ckb-next.info/mac/ckb-next_v0.3.0-62-g68fedda_10.11-SDK.dmg

**Comment by deanbolt** [comment]
ok ill try that now

**Comment by deanbolt** [comment]
thank u so much tatokis my mouse seems to be working now, i will try and set colors etc later and ill let u know

**Comment by deanbolt** [comment]
my mouse is currently all black, does save to hardware push the change?

**Comment by tatokis** [comment]
Save to hardware is for when ckb-next isn't running. All changes should be reflected instantly without saving.
Assuming brightness is set to 100%, you might want to run 
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
```
in a terminal and upload the report to see why it's not working.

**Comment by deanbolt** [comment]
okay ive set the colors we looking good!

**Comment by tatokis** [comment]
Glad to hear it
