### ISSUE TITLE
K65 rapidfire doesnt function with driver installed.

### ISSUE THREAD

**Issue by holytoast** [ckb-next/ckb-next#210]
# Bug report

### Source

# Something else
The keyboard instantly stops working when you install this driver on my macbook pro 13" 2017 touchbar even with reboots replugs ect the LEDs do work however and i can change them then save them to the kyboards memory then uninstall the software and then the keyboard works again just fine.

**Comment by ZirconiumX** [comment]
# Devices information

Open a terminal and execute:
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
```

Upload `ckb-next-dev-detect-report.gz` with this issue.

---

Can you please run this? It's part of the bug script.

**Comment by Oschly** [comment]
I have a similar problem but with K70 RGB Rapidfire (mx Speed) on Mojave so I've uninstalled ckb-next, but I put here this report.
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2341815/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
@Oschly Install the latest version and generate a report while the problem is happening. You might have to use another keyboard to do it.
