### ISSUE TITLE
K63

### ISSUE THREAD

**Issue by AlimovRoostam** [ckb-next/ckb-next#211]
Hi for Corsair k 63 work?

**Comment by ZirconiumX** [comment]
The wired K63 works fine. Wireless K63 doesn't, but is in progress.

**Comment by AlimovRoostam** [comment]
Ubuntu 18.04

./quickinstall
./quickinstall: line 28: cmake: command not found
An error occurred,
press enter to exit.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#build-from-source

```
sudo apt-get install build-essential cmake libudev-dev qt5-default zlib1g-dev libappindicator-dev libpulse-dev libquazip5-dev
```

**Comment by danilodequeiroz** [comment]
I am connected by wired but still doesn't work, do I need to compile from the wireless branch?

**Comment by ZirconiumX** [comment]
The "wireless" branch supports the *wired* K63 wireless. We haven't yet figured out how the dongle communicates to CUE.
