### ISSUE TITLE
Maintainer to support other Linux distributions

### ISSUE THREAD

**Issue by cristiansteib** [ckb-next/ckb-next#218]
I can contribute with the platform Ubuntu 18.04, to make deb package.
mail: cristiansteib@gmail.com

**Comment by ZirconiumX** [comment]
What ckb-next needs is not packaging maintainers but developers.

**Comment by cristiansteib** [comment]
@ZirconiumX ok, I can contribute, I'm a developer, if you think i can be helpful send me information to the mail.

**Comment by ZirconiumX** [comment]
We do all of our talk either on GitHub, or in the Freenode IRC channel
#ckb-next. Do note there is currently a 25 second delay before you can talk
because Freenode is under a spambot attack.
