### ISSUE TITLE
Windows lock and mute key color dosn't change

### ISSUE THREAD

**Issue by Wisssard** [ckb-next/ckb-next#220]
I've been using my strafe mk.2 for a couple of days and I realized I can't change the color of the mute button or the windows lock key. They show up as black on the ckb-next gui ,but even though i try to change them nothing changes. Switching between profiles causes it to become the correct color on the gui ,but the correct color is not displayed on the keyboard.

https://i.imgur.com/dtxeNr7.jpg
https://i.imgur.com/VicVSwF.png
https://i.imgur.com/3zsdClG.png
https://i.imgur.com/ZBwqVFE.png
 
[ckb-next-report-1533650115.gz](https://github.com/ckb-next/ckb-next/files/2266651/ckb-next-report-1533650115.gz)

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2266630/ckb-next-dev-detect-report.gz)

**Comment by ZirconiumX** [comment]
First off, is pulseaudio installed? The mute key requires pulseaudio and uses pulseaudio's mute status.

**Comment by Wisssard** [comment]
Yes but i mean the color dosn't change

**Comment by ZirconiumX** [comment]
@tatokis also mentioned that the Performance Tab overrides the colour of the Winlock and Mute keys because otherwise it wouldn't display winlock or mute.

**Comment by Wisssard** [comment]
oh ok sorry for the trouble

**Comment by ZirconiumX** [comment]
Don't be. If you enable winlock, does the light show up on your keyboard? If not, that's a bug. Same for mute, if you have pulseaudio installed and enabled.
