### ISSUE TITLE
[bug] Macro keys not working on system boot

### ISSUE THREAD

**Issue by zimmertr** [ckb-next/ckb-next#226]
# Devices information

> idVendor           0x1b1c Corsair
> idProduct          0x1b11 K95 RGB Mechanical Gaming Keyboard

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2280434/ckb-next-dev-detect-report.gz)

# Bug report

### Source
  * ckb-next package in AUR

## What is the program's current behavior?

Macro keys are not working on system boot. `ckb-next-daemon.service` is both enabled and starts successfully. The keyboard works in all other ways as expected. After launching `ckb-next` graphical program, macro keys begin to work immediately and continue to do so until the next system boot. 

## What is the expected behavior of the program?

Macro keys work on system boot after enabling `ckb-next-daemon.service` without the need to launch the graphical program. 

## Any other notes & comments?

```
Dir: /home/tj/temp 
Usr: tj - Sat 11, 11:03AM > cat /etc/*release*
Arch Linux release
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```
```
Dir: /home/tj/temp 
Usr: tj - Sat 11, 11:03AM > uname -a 
Linux jupiter 4.17.14-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 9 11:56:50 UTC 2018 x86_64 GNU/Linux
```

**Comment by tatokis** [comment]
The program is written in such a way that the GUI needs to run in order for the macro keys to work.

**Comment by zimmertr** [comment]
Thanks for clarifying. Closing this now.
