### ISSUE TITLE
Lighting percentages are linked between multiple devices

### ISSUE THREAD

**Issue by ThoreauHenry** [ckb-next/ckb-next#235]
Current hardware is K95 RGB Platinum & M65 Pro RGB.

ckb-next software is a git clone of August 21, 2018.

When altering the LED lighting percentages on the app, each device is linked together.  If I lower the mouse, the keyboard is lowered as well.  If I disable the LED for the mouse, the keyboard will go black.  

Device segmentation doesn't seem to be applied.

Thanks for your time.

![screen](https://user-images.githubusercontent.com/36612660/44386106-8af12a80-a4ef-11e8-88ae-49be358c9876.jpg)

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2305173/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
That is intentional, since you can't control the brightness on a mouse or a polaris/st100 on the devices themselves.
If you want to disable this, you can go to Settings->More settings and check `Set brightness per-mode`.
