### ISSUE TITLE
DEB & PPA

### ISSUE THREAD

**Issue by BloodyIron** [ckb-next/ckb-next#236]
Hey,

Any chance we can get .DEB packaged versions of this please?

Also, can we get a repo/PPA setup for this? I'd love to keep getting updates for this, just from my package manager :D

Please?

**Comment by ZirconiumX** [comment]
Well, as of #206, we have a Docker container that can create .debs, but no way to run it on a new commit.

**Comment by tatokis** [comment]
Regarding PPAs, someone tried creating one, but failed to maintain it.
I'll look into it again in the future and try to set mine up again.

**Comment by BloodyIron** [comment]
Thanks folks! I'd love if we could get this going! :)

**Comment by dameikle** [comment]
I've updated my PPA with the latest build but it needs me to keep the repositories in sync.  If the team were up for it, we could move in the debian folder from my fork and then schedule daily and release builds automatically in launchpad so we have a constantly up-to-date PPA.

Shall I submit a PR for the debian package information?

**Comment by ZirconiumX** [comment]
At the moment ckb-next is on pause due to both main developers burning out
on it.

**Comment by dameikle** [comment]
Sorry to hear that and hope the break helps everyone. It's a great tool and much appreciated.

I have started to use it a lot again as I am back working daily with Corsair kit, so will try to see where I can help.

**Comment by BloodyIron** [comment]
@ZirconiumX hope some RnR helps!

@dameikle thanks for your help! I think your work will help streamline getting this into people's hands :D

**Comment by tatokis** [comment]
Thank you. I will have a look at some point. The PPAs are greatly appreciated.

> I will see if I can get this accepted in Ubuntu.

Please no. I don't want an ancient version of ckb-next being used 4 years from now, especially with how often Corsair is releasing new devices, or how they break their protocol.

**Comment by dameikle** [comment]
> Please no. I don't want an ancient version of ckb-next being used 4 years from now, especially with how often Corsair is releasing new devices, or how they break their protocol.

No worries, won't do that then :)

**Comment by BloodyIron** [comment]
Okay, so @dameikle any chance you can update the PPAs with the 0.4.0 version? The daily PPA isn't exactly daily any more.

Alternatively we could try too get ckb-next mainlined into Ubuntu's main repos, so that everyone can get it!

Please?

**Comment by tatokis** [comment]
> The daily PPA isn't exactly daily any more.

That's partly my fault for not reviewing the PR related to this.

>Alternatively we could try too get ckb-next mainlined into Ubuntu's main repos, so that everyone can get it!

Please no.

**Comment by BloodyIron** [comment]
What's wrong with this utility going main-repo exactly? Build it so less people can use it? That's silly.

STEAM's in the main repos...

Any word on when we can get latest release on current PPAs then? :)

**Comment by BloodyIron** [comment]
So, what would it take to get deb releases here? I literally have money burning a hole in my pocket to get a M65 RGB Elite, but from what I'm seeing 0.3.2 doesn't support it, and I want my package manager to be aware of ckb-next being installed, etc.

I prefer the idea of a PPA, but if we could get releases on here to have DEB packaging that would be appreciated!

Please? :)

**Comment by ZirconiumX** [comment]
If you want an M65 Elite to be supported, first we need an M65 Elite to
support. We can't test on hardware we don't have, and it's not like Corsair
help us in any way.

**Comment by BloodyIron** [comment]
@ZirconiumX 

1. ckb-next 0.4.0 lists M65 RGB Elite as added : https://github.com/ckb-next/ckb-next/releases
2. I'm talking about asking for a deb package for 0.4.0, which is not available in any PPA I can find (including the daily one)
3. If we could get deb packages for future versions that too would be appreciated
4. Latest version in the PPAs is 0.3.2, which does not list that mouse as supported/working

So, not sure where you get the idea it's not supported, because the info available outlines it is for 0.4.0.

**Comment by BloodyIron** [comment]
@dameikle any chance we can get 0.41 and 0.42, plus Ubuntu 19.10 added to your PPA please? :)
