### ISSUE TITLE
Strafe RGB MK.2 Problem

### ISSUE THREAD

**Issue by EricGao888** [ckb-next/ckb-next#241]
Does the latest version of ckb-next support Strafe RGB MK.2? It shows no devices connected.

**Comment by ZirconiumX** [comment]
Yes, it does.

Can you please upload a ckb report, like it tells you to do?

**Comment by aydex** [comment]
[ckb-next-report-1535370215.gz](https://github.com/ckb-next/ckb-next/files/2323709/ckb-next-report-1535370215.gz)
Having the same issue as @EricGao888, report attached

**Comment by tatokis** [comment]
Try this http://ckb-next.info/mac/ckb-next_v0.3.1-41-gb25a611_10.11-SDK.dmg

**Comment by aydex** [comment]
Works for me. Thank you!

**Comment by ZirconiumX** [comment]
Can we close this, then?

**Comment by tatokis** [comment]
I'd like to leave it open until the next release, so that people can more easily see it.

**Comment by EricGao888** [comment]
@tatokis I've tried a lot but only the method you provide works for me! Much appreciation!

**Comment by tatokis** [comment]
It'll be fixed in the next release. Apologies for that.

**Comment by MikaelAbehsera** [comment]
@tatokis I'm on a k70 rapidF RGB and my x seems to decide its own colors and does not listen, this just started lately, and also ckb stops recognizing my keyboard after couple of times of disconnecting it, I have now downloaded the ckb above and can note back to you if anything has been fixed, thanks for making this software your a lifesaver!

**Comment by Vermyndax** [comment]
FYI this also fixed my issue (using macOS Mojave).

**Comment by ZirconiumX** [comment]
v0.3.2 is out, so I'm closing this.
