### ISSUE TITLE
K70 RGB "No Device Found"

### ISSUE THREAD

**Issue by GarlandKey** [ckb-next/ckb-next#242]
Just did a fresh install of Arch Linux and installed ckb-next-git from the aur.  When I open the ckb ui, it tells me that my K70 RGB is not detected.

![image](https://user-images.githubusercontent.com/3108516/44667659-061b7a80-a9e1-11e8-9fe8-f7ce39525d54.png)

I've enabled the daemon and it's running correctly:

    # systemctl status ckb-next-daemon
    ● ckb-next-daemon.service - Corsair Keyboards and Mice Daemon
        Loaded: loaded (/usr/lib/systemd/system/ckb-next-daemon.service; enabled; vendor preset:
        Active: active (running) since Mon 2018-08-27 10:01:17 CDT; 7min ago
    Main PID: 843 (ckb-next-daemon)
            Tasks: 1 (limit: 4915)
    Memory: 888.0K
    CGroup: /system.slice/ckb-next-daemon.service
            └─843 /usr/bin/ckb-next-daemon

I've tried unplugging it and holding down the Esc key while plugging it back in. This reset the lighting but it's still not showing up. I also just noticed that the Scroll Lock light is blinking.

[ckb-next-report-1535382107.gz](https://github.com/ckb-next/ckb-next/files/2324407/ckb-next-report-1535382107.gz)

**Comment by GarlandKey** [comment]
@ZirconiumX Derp!  Thank you - that was it!

**Comment by ZirconiumX** [comment]
Hang on, is the scroll lock still flashing?

**Comment by GarlandKey** [comment]
@ZirconiumX It isn't flashing anymore. Once I flipped with back switch from BIOS to 1, everything immediately worked. The scroll lock is no longer flashing.
