### ISSUE TITLE
Remove unnecessary dependencies for building daemon

### ISSUE THREAD

**Issue by pearsonk** [ckb-next/ckb-next#244]
The cmake build structure has some unnecessary dependencies that have to be on the build host for building the daemon in isolation
- QT5
- QuaZip

Wrapping these into a feature that could be disabled when unnecessary would remove the need to have packages on the build host that are ultimately unnecessary for the target component.

**Comment by tatokis** [comment]
It's supposed to be like that, but I never had the time to go fix it. The no gui flag should disable those.

Due to its nature, it's on the bottom of the priority list for me, so patches are welcome.
