### ISSUE TITLE
After unplugging k70 rgb rapid once ckb does not recognize 

### ISSUE THREAD

**Issue by MikaelAbehsera** [ckb-next/ckb-next#250]
After unplugging my keyboard I have to reinstall the software to get it to recognize my keyboard again. sometimes it will only happen after five times of unplugging and replug it and sometimes it happens after one time.  
MacBook Pro on 10.13.6 high Sierra
Early 2015 model

**Comment by MikaelAbehsera** [comment]
@tatokis Ill try, it happens every time I unplug and replug.

**Comment by ZirconiumX** [comment]
Closing as stale.
