### ISSUE TITLE
Looking for testers for a non-RGB version of Strafe kbd (1b1c:1b44)

### ISSUE THREAD

**Issue by nsneck** [ckb-next/ckb-next#253]
If there are owners of the Strafe 1b1c:1b44 out there, could you confirm if it suffers from [this](https://github.com/mattanger/ckb-next/issues/240) issue like the other NRGB variant of said kbd?

If it does, applying [this patch](https://github.com/nsneck/linux/commit/b20ffc3ff5548a911472fcec40de68baf9005744) with the device ID changed to 44 _may_ fix the issue, and it should be fixed (worked around? shrug) upstream in Linux itself.

**Comment by ZirconiumX** [comment]
If you don't give more information than a "title says it all" type message, then I'm just going to close this and people will probably never see it.

**Comment by ZirconiumX** [comment]
Since it's been over a year and there haven't been any responses, I'm going to close this. Feel free to file a new issue if you still need testers, but I'm assuming this is stale.
