### ISSUE TITLE
CKB-next keybinding options missing.

### ISSUE THREAD

**Issue by davidbdeath** [ckb-next/ckb-next#267]
I have the driver now working but after 30 minutes I have yet to find a way to bind for example "control+up" or "Command+[". These are basic keyboard commands on MacOS.

**Comment by tatokis** [comment]
It's not obvious for mouse-only users, but have a look at https://github.com/ckb-next/ckb-next/issues/243#issuecomment-416373008

**Comment by davidbdeath** [comment]
I see so there is no lcmd, it's lwin. Is there a list of inputs somewhere?

**Comment by tatokis** [comment]
It's lwin because that's the physical key on corsair keyboards.
You can find a list of inputs here. It's the ones on the left. https://github.com/ckb-next/ckb-next/blob/master/src/daemon/keymap.c#L9
