### ISSUE TITLE
Can't find the animation directory after latest update.

### ISSUE THREAD

**Issue by bicarbonate** [ckb-next/ckb-next#276]
I have not tried to build from source.. I'm unsure of what will happen since I'm using the copr build. And mentioning that.. I'm not sure where to correct post this issue..

### Source

copr build on F28

## What is the program's current behavior?

The <insert name> script could not be loaded. Please check your animation directory.

## What is the expected behavior of the program?

Loads animations correctly.

## Any other notes & comments?

---

# Something else

**Comment by tatokis** [comment]
Try running `ls /usr/libexec/ckb-next-animations/` and paste the output

**Comment by BumblingCoder** [comment]
I see the same issue. On my machine running that ls command gives
`gradient  heat  mviz  pinwheel  rain  random  ripple  wave`

In the application settings dialog it says that it is looking for the animations scripts in `/usr//usr/libexec/ckb-next-animations`, which seems to be the problem.

**Comment by tatokis** [comment]
@hevanaa Can you please look into this?

**Comment by bicarbonate** [comment]
Awesome, thank you. Updated and now I'm Rainbow again.

**Comment by bicarbonate** [comment]
Issue resolved.

**Comment by bicarbonate** [comment]
Crap sorry.

**Comment by ssrebelious** [comment]
Having the same issue here after update to 0.4.0. I'm using [rpm for OpenSUSE Leap 15](https://build.opensuse.org/package/show/hardware/ckb-next). Is there a way to set correct path manually?

**Comment by hevanaa** [comment]
You could notify them that their spec needs to be corrected. It should have "-DCMAKE_INSTALL_LIBEXECDIR=libexec", not "-DCMAKE_INSTALL_LIBEXECDIR=%{_libexecdir}"

**Comment by Espionage724** [comment]
> Having the same issue here after update to 0.4.0. I'm using [rpm for OpenSUSE Leap 15](https://build.opensuse.org/package/show/hardware/ckb-next). Is there a way to set correct path manually?

I submitted a bug report here about it: https://bugzilla.opensuse.org/show_bug.cgi?id=1135528

**Comment by bmwiedemann** [comment]
> You could notify them that their spec needs to be corrected. It should have "-DCMAKE_INSTALL_LIBEXECDIR=libexec", not "-DCMAKE_INSTALL_LIBEXECDIR=%{_libexecdir}"

This is not how it is supposed to work, because on openSUSE, it would have to be DCMAKE_INSTALL_LIBEXECDIR=lib
that is why we have these macros to abstract away the distribution differences.
