### ISSUE TITLE
Driver inconsistently recognizing keyboard on macOS Mojave

### ISSUE THREAD

**Issue by washedgram** [ckb-next/ckb-next#278]
# Before you proceed

- Read the [wiki](https://github.com/ckb-next/ckb-next/wiki).
- Try the latest code by building the software manually.
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
- File unrelated issues separately.
- Use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to format the message.
- There are 3 types of issues: new device, feature, bug. Use only one. Delete redundant sections before sending.

---

# Devices information

Open a terminal and execute:
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2503950/ckb-next-dev-detect-report.gz)

```

Upload `ckb-next-dev-detect-report.gz` with this issue.

---

# New device support request

Upload:
  * Linux:
    * `ckb-next-dev-detect-report.gz` from the section above
  * macOS:
    * `ckb-next-dev-detect-report.gz` from the section above
    * full USB bus dump by following [the instructions](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# Feature request

## Any other notes & comments?

---

# Bug report

## General information

Program very inconsistently recognizes keyboard on two different computers, both running macOS mojave 10.14. Sometimes the keyboard won't even be recognized by the computer itself after having installed ckb-next 

## Logs & crash reports

Upload:
 * `ckb-next-dev-detect-report.gz` from the section above
 * any additional crash reports you've managed to gather

## Any other notes & comments?

---

# Something else

**Comment by washedgram** [comment]
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2503960/ckb-next-dev-detect-report.gz)

not sure if this got uploaded the first time

**Comment by tatokis** [comment]
Try updating to 0.3.2 and see if that changes anything.

**Comment by washedgram** [comment]
How exactly do I update again?

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/releases/download/v0.3.2/ckb-next_v0.3.2.dmg
Install that, and maybe reboot afterwards.

**Comment by washedgram** [comment]
Fixed it. Thanks!

**Comment by washedgram** [comment]
Having the same issue again. I think it’s happening after I unplug from Mac and use on windows then try to use on Mac again. Should I submit a support ticket again?

**Comment by tatokis** [comment]
Please generate another report and attach it to this issue
