### ISSUE TITLE
not detecting mouse after a reboot

### ISSUE THREAD

**Issue by imageschool** [ckb-next/ckb-next#282]
# Before you proceed

- Read the [wiki](https://github.com/ckb-next/ckb-next/wiki).
- Try the latest code by building the software manually.
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
- File unrelated issues separately.
- Use [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to format the message.
- There are 3 types of issues: new device, feature, bug. Use only one. Delete redundant sections before sending.

---

# Devices information

Open a terminal and execute:
```
curl https://raw.githubusercontent.com/ckb-next/ckb-next/master/ckb-next-dev-detect 2>/dev/null | bash
```

Upload `ckb-next-dev-detect-report.gz` with this issue.

---

# New device support request

Upload:
  * Linux:
    * `ckb-next-dev-detect-report.gz` from the section above
  * macOS:
    * `ckb-next-dev-detect-report.gz` from the section above
    * full USB bus dump by following [the instructions](https://github.com/mattanger/ckb-next/issues/31#issuecomment-285380447)

---

# Feature request

## Any other notes & comments?

---

# Bug report

### Source
**ckb-next.0.3.2.dmg (in releasees)**

## Logs & crash reports

Upload:
 * `ckb-next-dev-detect-report.gz` from the section above
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2521575/ckb-next-dev-detect-report.gz)

 * any additional crash reports you've managed to gather

## Any other notes & comments?

---

# Something else

Every time I do a restart, it does not detect my mouse (corsair m65) anymore.
If I re-install the package, then it detects again.
(Using Macbook Pro 2018, 10.13.6 High sierra)

**Comment by imageschool** [comment]
I am a new user, so I have only checked with the current version!

However... weirdly it works just fine again even after a restart.

I will just observe a few more days and let you know here!!

P.s thank you very much for a great piece of software

**Comment by ollieatkinson** [comment]
Can you tell us if the `daemon` had started?

```sh
$ sudo launchctl list | grep org.ckb-next.daemon
```

**Comment by ZirconiumX** [comment]
I'm going to close this as stale, since nothing more has been said for over a year.
