### ISSUE TITLE
Corsair K95 RGB Platinum Cannot Find 'FN' on macOS

### ISSUE THREAD

**Issue by JimBartlett** [ckb-next/ckb-next#284]
# Devices information
K95 RGB Platinum
# Bug report

## General information
I would like to allocate to my 'insert' key the keycode for 'fn' so that I can use it in conjunction with my F1-F15 keys which I have set up to be the defaults as per a Mac keyboard. E.g. F1 = brightness down, F4 = Launchpad etc. All of these functions are working. I even have the correct keycaps with the mac functions on them.
I have also removed ckb-next and used the stand-alone version of Karabiner Elements and I can assign 'fn' to the Insert key. By pressing this 'fn' and an F(x) key it reverts the Function key to the default.
Have I missed something, or have you forgotten to put the 'fn' code in this build.  
### Source
I built this version ckb-next 0.3.2-6-gfe933d1 using the quickinstall script
## Logs & crash reports
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2522459/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
I'm confused at what the problem is.
Can you not bind it to "Function" under modifiers?
![2964b959e281](https://user-images.githubusercontent.com/6003656/47618774-b855e800-dadf-11e8-99ab-bb45e49b51d1.jpg)


>Have I missed something, or have you forgotten to put the 'fn' code in this build.

https://github.com/ckb-next/ckb-next/blob/eb106ffb90c73a374d93a73f6b9310a424f3c463/src/daemon/input_mac.c#L189-L192

**Comment by JimBartlett** [comment]
Yes, I can bind it to that 'function' under Modifiers, but it does nothing. Have a look at the Karabiner Elements. They specifically call it 'fn' and it works. A real mac keyboard has an 'fn' key, and that is the functionality I'm looking for, but can't find. If the 'Function' modifier key is the direct replacement of 'fn' then it's not working for me.

**Comment by JimBartlett** [comment]
Hi. I'm hoping I can get further help on getting this Function key modifier working on my K95P RGB running ckb-next 0.3.2-8-g6c83cdf installed by the ./Quickinstall method on macOS Mojave 10.14.1

I have downloaded a Key Code app that shows what key has been entered. Here is the results of my testing:

1. With ckb-next **disabled,** when I press the 'Insert' key I get this:
<img width="351" alt="ckb_next disabled insert key" src="https://user-images.githubusercontent.com/32009758/47886370-b26c5800-de8d-11e8-99a0-903fe775a438.png">
Selecting the  ⓘ gives me these for both the Key Down/Up events respectively
NX_SECONDARYFNMASK / kCGEventFlagMaskSecondaryFn / NSFunctionKeyMask = 8388608 / 0x800000
NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced = 256 / 0x100

2. With ckb-next enabled and the 'Insert' key using the 'Function' modifier, I get the following
<img width="353" alt="ckb_next enabled insert key" src="https://user-images.githubusercontent.com/32009758/47886501-987f4500-de8e-11e8-91fc-48a8b666f3da.png">
Selecting the  ⓘ gives me these for the Key Down/Up events respectively
NX_SECONDARYFNMASK / kCGEventFlagMaskSecondaryFn / NSFunctionKeyMask = 8388608 / 0x800000
NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced = 256 / 0x100
NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced = 256 / 0x100

3. If I set the 'Insert' key to default, ckb-next shows the key bound to the 'Miscellaneous' as Help.
<img width="221" alt="default for insert key" src="https://user-images.githubusercontent.com/32009758/47886646-7afeab00-de8f-11e8-8e92-de463ed7c45d.png">

4. If I set the 'Insert' key to another modifier e.g. 'Caps Lock' it works as expected.

5. If I set the 'Page Down' or any other key to the 'Function' modifier it gives me the same results as point 2. 

Why does it show the 'Insert' key as 'Help'? I think this is the cause of the problem, but what is causing it?
Does macOS think I have a different keyboard mapping from what ckb-next expects?
Is there anything else I can try?

**Comment by tatokis** [comment]
First of all, thank you for your detailed information.
I've been working on the input code, trying to fix the brightness key, so I'll look into this once I am done.

The default bindings do not affect bindings you set, so if it's bound by default as "Help", I don't think it matters. This is probably a different issue.

Looking at the example karabiner virtualhiddevice code, it doesn't mark Fn as a modifier. I am the only mac dev, and I don't have a mac, so please bear with me while I try to get it sorted.

**Comment by JimBartlett** [comment]
Thanks for getting back to me so quick! 👍 If you need anything else let me know. I'm a retired programmer in my 60's, so I'm a bit rusty, and also new to macOS, but I have a lot of time on my hands to help with test etc.

**Comment by tatokis** [comment]
You can ignore that error. It has something to do with Apple's APIs and I haven't been able to figure it out.
Basically, every time you unplug your keyboard and plug it back in, a new message is generated. Seems to be ghost devices. Either way, it's unrelated.

Regarding the Fn key, I used Karabiner's EventViewer (without the rest of Karabiner) to check what keycodes are generated by karabiner when a key is bound to Fn, and by ckb-next-daemon when a key is bound to Function.

Unfortunately, they both produce the exact same code, so I am confused how it works for karabiner and not ckb-next.
As a sidenote, make sure you don't have karabiner installed at the same time as ckb-next as they conflict due to how they both function. To uninstall karabiner use the button in the program itself, and don't just drag it to trash.

**Comment by JimBartlett** [comment]
Thanks, @tatokis for the update. Yes I deleted all of Karabiner, I've even tried another standalone install of macOS with ckb-next with same results.
I'm also confused as to why the Fn key works in Karabiner, but not ckb-next, since you are using Karabiner as the backend for ckb-next.
Is it possible to use ckb-next to control the RGB side and have Karabiner standalone control the key mapping?
Does your confusion lead you to investigate further, or can I help in any way?

**Comment by tatokis** [comment]
Unfortunately due to how the Corsair protocol works, we can't just control the lights. We need to handle key input too.

I think I have found something. In the meantime, can you check if double tapping the key that's bound to function on a supported application brings up voiceover?

**Comment by JimBartlett** [comment]
Ok, I enabled Dictation (I think you meant Dictation rather than VoiceOver) and told it to use the Fn key which is really my 'Insert' key which is bound to 'Function'.
Pressing Insert twice enables dictation in the Notes application. So I guess macOS is at least understanding that my Insert key is the Fn key!

**Comment by tatokis** [comment]
Yeah, I meant dictation.
Try compiling and running the code from the `mac-avtopcase` branch.

It should have these changes https://github.com/ckb-next/ckb-next/commit/0a9ca0759607d82a35366e20c64fd8d4b91d7126

**Comment by JimBartlett** [comment]
FWIW, this is what I get with and without ckb-next enabled respectively, using my Apple keyboard and typing fn and F10 together.
<img width="354" alt="screen shot 2018-11-03 at 2 34 23 pm" src="https://user-images.githubusercontent.com/32009758/47947705-917f3200-df75-11e8-8db5-3ea0e1037ecf.png">
<img width="350" alt="screen shot 2018-11-03 at 2 35 41 pm" src="https://user-images.githubusercontent.com/32009758/47947719-c095a380-df75-11e8-9683-bfd69512226f.png">

This is ckb-next with me typing Insert (Function) and F10 together.
<img width="353" alt="screen shot 2018-11-03 at 2 40 51 pm" src="https://user-images.githubusercontent.com/32009758/47947752-795be280-df76-11e8-92b1-63d84ec0638d.png">

Notice no F10 key in between the modifier keys

If I disable the modifier for the F10 key (Media Mute) then I get the same as my Apple keyboard when I type Insert and F10 together.
It is as though ckb-next code is not allowing a Function key that has a modifier, Media mute in this case, to be modified by another modifier key i.e the Insert (Function modifier). This is what I get when I unbind the F10 key from Mute to its default F10 and typing fn and F10 together.
<img width="350" alt="screen shot 2018-11-03 at 2 47 50 pm" src="https://user-images.githubusercontent.com/32009758/47947784-744b6300-df77-11e8-9230-dd82b854615c.png">

**Comment by tatokis** [comment]
I fail to understand why this happens.

This is mostly just a quick update to say that I haven't forgotten about this. I'll probably look into it more this weekend

**Comment by JimBartlett** [comment]
No problems @tasos, I'm readily available when you are ready to look further.

**Comment by tatokis** [comment]
I had a thought, that I haven't verified yet. It is possible karabiner detects Fn being pressed, and when so, switches the scancodes being sent to the OS.

On a mac, do you know what the default action of the keys without Fn is?
For example, on an apple keyboard, does pressing f2 without Fn change the brightness or does it send the F2 keycode?

**Comment by sjmagy** [comment]
Hi.  Sorry to butt in but I was perusing posts to research K95 Platinum support for Mac (since I had participated in Corsair's own mac closed-beta software evaluation, but their beta program ended earlier this year and where they left it it doesn't work under macOS Mojave).  Anyway, thought I'd provide a quick answer.  On native mac keyboards (laptops, for example, or Apple's own keyboards), F2 without the "fn" key held down increases display brightness in increments.  With the "fn" key held, I would assume it sends the regular "F2" key code?

As a point possibly worth mentioning -- on at least Mac laptops, there is a setting in macOS System Preferences > Keyboard, where you can check a box that says, "Use F1, F2, etc. keys as standard function keys (When this option is selected, press the Fn key to use the special features printed on each key)".  If memory serves, that setting disappears when you plug in an external keyboard (I don't have that setting on my MacPro with an external keyboard), but thought I'd mention it since I can't help but wonder if perhaps that may be implicated in complicating this issue?

**Comment by tatokis** [comment]
@sjmagy Thank you for clearing that up

Unfortunately that option doesn't show up on my Keyboard settings either, so I can't test it.

I'm starting to think we might have to somehow get USB packet captures from the apple keyboard to figure out exactly what it sends, however I have no idea how to do that. Wireshark supposedly can do it these days, but I haven't figured it out.

**Comment by JimBartlett** [comment]
Sorry for the delay in getting back to you @tatokis and thanks for your comments @sjmagy.
Confession time... I'm running macOS on a Gigabyte Z370 Aorus motherboard, so it's not a genuine Mac. Everything is working USB, sleep, powernap, hand-off, iMessage, etc. Just letting you know so that there is no confusion regarding it being a 'Hack'. 
Getting back to your last question Tasos, with my current K95 plugged in and running the latest master ckb-next 0.32-16-g418af41 **plus** my genuine Apple USB keyboard, the keyboard settings in System Preferences shows the 'Use F1, F2, etc. keys as standard function keys' option **regardless** of whether the Apple keyboard is plugged in.
<img width="780" alt="screen shot 2018-11-27 at 1 40 50 pm" src="https://user-images.githubusercontent.com/32009758/49055125-98365780-f24a-11e8-8d01-221256813625.png">
<img width="462" alt="screen shot 2018-11-27 at 1 41 12 pm" src="https://user-images.githubusercontent.com/32009758/49055132-9d93a200-f24a-11e8-857a-0fed3de41ce9.png">

**With the Apple keyboard and the focus on the Key Codes app:**

- If I select this option (turn it on), then all the keys act as their function F1 -sends a F1 Key Down & Up code... see below.
<img width="267" alt="screen shot 2018-11-27 at 1 51 58 pm" src="https://user-images.githubusercontent.com/32009758/49055444-a9339880-f24b-11e8-99f1-e1c895cc826d.png">

- If I select the fn key by itself I get this capture:
<img width="261" alt="screen shot 2018-11-27 at 2 03 34 pm" src="https://user-images.githubusercontent.com/32009758/49055843-3deac600-f24d-11e8-91ea-ae442433cece.png">

- If I select say fn & the F3 key, Mission control displays, and I only get the one Modfier event: 
<img width="260" alt="screen shot 2018-11-27 at 2 05 06 pm" src="https://user-images.githubusercontent.com/32009758/49055890-74c0dc00-f24d-11e8-9458-bc941ac8a800.png">

- If I select it so it performs the special functions it performs them e.g F3 displays Mission Control, all of the F1-F12 keys are not captured and displayed in the Key Codes app that I'm using. So my assumption is that the 'special function' key event code is **not** being released for other applications to use.

- If I use the fn modifier with say the F3 key, I get the following:
<img width="262" alt="screen shot 2018-11-27 at 2 18 27 pm" src="https://user-images.githubusercontent.com/32009758/49056301-56f47680-f24f-11e8-9e4b-2361a36facbb.png">

Currently, for all the special functions on my K95P I'm using the Binding/Program feature. E.g for Mission Control (F3) I have in the Launch program on key press: "open /Applications/Mission\ Control.app"
I have a gut feeling that if I can capture the exact keycodes for the 'Special Function' keys on a Mac keyboard and have them as an option in the 'Binding/Miscellaneous' drop-down, then this would finally solve this issue.  
I have the Wireshark app, and I know how to get it to capture USB packets on the macOS ass I used it to debug another USB app previously. I'll see if I can capture these 'Special keycodes'.
Would this be helpful to you Tasos?

**Comment by JimBartlett** [comment]
Nearly forgot. ATM I have set up 2 profiles one with F1-F12, and the other with the special functions. I just then flip between them depending on my needs, but I still prefer to have the fn key working. 👍
