### ISSUE TITLE
Cannot uninstall properly

### ISSUE THREAD

**Issue by danilodequeiroz** [ckb-next/ckb-next#287]
The uninstall procedures only disabled/ removed the daemon, but the cbk-next gui is still available on overview search on ubuntu 18.04.

**Comment by AaronTakizad** [comment]
I resolved this issue by removing `ckb-next-*` executables from `/usr/local/bin` (from memory?). I also found residual animations data in `/usr/libexec/ckb-animations`. Make sure to also remove the program from your startup applications, as this is also missed by the uninstaller.

**Comment by tatokis** [comment]
Assuming you mean just the desktop entry, I just tested it and the .desktop file was removed for me.
Are you sure you just didn't need to reboot/wait for the cache to get cleared?
Can you reproduce this?
