### ISSUE TITLE
Ckb next daemon running in the backround in macos high sierra

### ISSUE THREAD

**Issue by 5and3r** [ckb-next/ckb-next#290]
It runs in backround and if i force it quit it just relaunches himself. I have uninstalled it but it doesnt help. And it runs like it would be some system app. Pls help!
I posted this w/ my phone cuz my computer is overheating if i dont shut it down.

**Comment by tatokis** [comment]
Which version of ckb-next did you install?
ckb-next-daemon is the part that runs in the background that communicates with your devices.

If your computer is overheating, you should probably try to fix it first, as that's another issue.
That aside, ckb-next-daemon isn't supposed to use this many resources.

Someone else opened an issue about it, but they never responded when I asked for more info, and it doesn't happen for me.

To uninstall it completely you can run the following two commands in a terminal

```
sudo launchctl unload -w /Library/LaunchDaemons/org.next.ckb.daemon.plist
sudo rm /Library/Application\ Support/ckb-next-daemon
```

**Comment by tatokis** [comment]
Sorry, the correct commands are
```
sudo launchctl unload /Library/LaunchDaemons/org.ckb-next.daemon.plist
sudo rm /Library/Application\ Support/ckb-next-daemon
```

**Comment by 5and3r** [comment]
thanks, now i can use my computer normally again!! u r best.

**Comment by tatokis** [comment]
Closing because no one helped me try to fix it
