### ISSUE TITLE
Support for Portuguese ISO Layout

### ISSUE THREAD

**Issue by Madril** [ckb-next/ckb-next#297]
Is there a way for ckb-next to support the Portuguese (pt-PT) ISO layout?

**Comment by tatokis** [comment]
Is this on mac?
All we do is pass through keystrokes, and the layouts are purely visual, so it's up to the OS to handle it.

macOS doesn't seem to have support for the layout, so I don't think there's much we can do about it, and I'd rather not hack around the code with permanent key remaps.

**Comment by Madril** [comment]
It is on a Mac.
Got it working kinda fine now. Only < and § are switched.

**Comment by sidneywidmer** [comment]
@Madril I have the same problem with the Swiss layout. Did you find a fix for it? Everything works great but < and § are switched 🤔

**Comment by sidneywidmer** [comment]
Just figured it out 🙈 on MacOS just force rerun the Keyboard assistant and everything works as expected 👍
