### ISSUE TITLE
Unable to use cmd in macros

### ISSUE THREAD

**Issue by uimadurer** [ckb-next/ckb-next#305]
Hi,

I have tried to look it up but I could not find anything on the subject. I am trying to map a button on my Scimitar mouse to do cmd + l but I havent been able to make it work. Can someone please help ?

Here is the macro I am doing: +lcmd,+l,-l,-lcmd

Also when looking into keymap.c I could find all the keys except cmd.

Thank you for your help.

**Comment by tatokis** [comment]
It's lwin, not lcmd, since the keyboard has a windows key.
Here's an example https://github.com/ckb-next/ckb-next/issues/243#issuecomment-416373008
