### ISSUE TITLE
Inconsistent keyboard behavior

### ISSUE THREAD

**Issue by kizzmaul** [ckb-next/ckb-next#309]
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2652783/ckb-next-dev-detect-report.gz)
Hello!

This is my first time submitting any issues to git projects so please be gentle. First, I'd like to say that this software is amazing and off the note I know how some of the Windows players feel when they ask for a Windows version of this software (Corsairs own software is atrocious). 

However, I would like to talk about something else. I have noticed that sometimes my computer slows down considerably while using this software. It starts with the RGB lightning "losing frames", that is the colours start to update in ~1 second intervals instead of consistent updated. This affects the writing too, the keyboard doesn't register all of the key presses and/or register them in a wrong order. This is hard to replicate since it seems to happen quite randomly but if I close the CKB process from the tray icon the keyboard returns to normal behavior. 

Installing the latest git version from source was the first thing I did since it could have been the case that this problem was solved after my former installation but the problem persisted. I am happy to provide any information that will help with this problem. Hardware shouldn't be the issue since my system is quite high end and I am sure this isn't the intended behaviour. I am running a kernel version 4.19.5-101 but this issue was present in former kernels too.

**Comment by kizzmaul** [comment]
Thanks, I will try it. I should have explained more though, this issue emerges while the GUI tool is in the tray and not opened (I normally have it only on background in the tray). I only notice the effect after some uptime (after boot it works normally). I will keep the option unticked and report if this helps with the issue. Could it be possible that the Qt runtime is rendering the animation in the background even when the GUI is closed in the tray? Maybe this is distro-related, I am using Budgie desktop.

P.S. Is there a good practice (script?) on how to report generic system information?

**Comment by ZirconiumX** [comment]
On Thu, 6 Dec 2018, 12:06 kizzmaul <notifications@github.com wrote:

> Thanks, I will try it. I should have explained more though, this issue
> emerges while the GUI tool is in the tray and not opened (I normally have
> it only on background in the tray). I only notice the effect after some
> uptime (after boot it works normally).
>
... This probably sounds irrelevant, but does your system use an Intel
Skylake or later chip?

I will keep the option unticked and report if this helps with the issue.
> Could it be possible that the Qt runtime is rendering the animation in the
> background even when the GUI is closed in the tray? Maybe this is
> distro-related, I am using Budgie desktop.
>

I doubt it; I'm not the GUI person here, but I don't see why we would.

P.S. Is there a good practice (script?) on how to report generic system
> information?
>

The dev-detect script collects most of the information we need.

**Comment by kizzmaul** [comment]
I am using a Ryzen 7 2700X with Crosshair VII Hero motherboard with latest bios updates.

**Comment by ZirconiumX** [comment]
Hmm. This sounds like a new issue in this case.

@tatokis, any ideas?

**Comment by kizzmaul** [comment]
Also, I am using a Vega 56 GPU with the OSS amdgpu-driver. If this is a new issue, it might have gone unnoticed due to nVidia cards being much more popular (granted, AMD might be quite popular in the Linux space due to the current driver development trend but I would still assume that nVidia cards are more abundant nevertheless.)

**Comment by OvermindDL1** [comment]
I run AMD, both CPU and GPU with the OSS driver as well and no such issues for note just to be a data point.

**Comment by gravityfargo** [comment]
Stale.
