### ISSUE TITLE
Side Buttons Still dont work

### ISSUE THREAD

**Issue by Juniorin** [ckb-next/ckb-next#318]
I know this is a repeat but I still havent been able to fix the issue after reading others. I am not able to use my side buttons for my Corsair Harpoon RGB. I have tried creating a macro for my side buttons to +mouse4,-mouse4, but it still doesn't work.

**Comment by tatokis** [comment]
Make sure you're on version 0.3.2 and create a new profile. It'll have the correct bindings

**Comment by Juniorin** [comment]
I found out it wasn't the bindings it was because Geforce Now doesn't have supported drivers.
