### ISSUE TITLE
Failed to enable unit: Unit file ckb-next-daemon.service does not exist.

### ISSUE THREAD

**Issue by medwatt** [ckb-next/ckb-next#319]
I'm new to Linux as a whole, so I don't really know much of what I'm doing.

I have a Corsair Scimitar Pro mouse that I want to use in Manjaro while I learn how to use Linux.

I followed the instructions on [this](https://github.com/ckb-next/ckb-next/wiki/Linux-Installation) page how to install the application.

I was able to install the application. When trying to open it, I was asked to start the daemon by running: `sudo systemctl enable ckb-next-daemon`

I did that but got the error: "Failed to enable unit: Unit file ckb-next-daemon.service does not exist."

I searched for similar issues before posting here and came upon [this](https://github.com/ckb-next/ckb-next/issues/175) page.

As a temporary workaround, it was suggested I should run `sudo nohup ./ckb-next-daemon`. I did and was able to launch the application fine. However, this did not solve the issue when restarted. That post was made in May 2018 and it was suggested in the final post that this issue has been resolved with newer commits.

A [log](https://github.com/ckb-next/ckb-next/files/2711149/log.txt) file for the installation process is attached.

**Comment by tatokis** [comment]
Please pull in the latest changes from master. I reverted the commit that broke this, so it should work now.
