### ISSUE TITLE
ST100 Support

### ISSUE THREAD

**Issue by RobRoyce** [ckb-next/ckb-next#320]
I read in #156 that ST100 support is already enabled, but I'm unable to get it to work on my Mac. Any idea what might be going wrong?

> ckb-next-dev-detect - Wed Dec 26 19:11:04 PST 2018

> Kernel: Darwin Roberts-MacBook-Pro-2.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
> 
> OS Version:
> ProductName:	Mac OS X
> ProductVersion:	10.14.2
> BuildVersion:	18C54
> 
> USB Devices:
>                 Corsair ST100 USB 2.0 Hub:
> 
>                   Product ID: 0x0a36
>                   Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
>                   Version: 93.02
>                   Serial Number: v5.0
>                   Speed: Up to 480 Mb/sec
>                   Manufacturer: Corsair Components
>                   Location ID: 0x14612000 / 21
>                   Current Available (mA): 500
>                   Current Required (mA): 500
>                   Extra Operating Current (mA): 0
> 
> --
> --
>                     Corsair ST100 LED Driver:
> 
>                       Product ID: 0x0a34
>                       Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
>                       Version: 0.02
>                       Serial Number: 0730021189A429AFAECF885AC51B00F5
>                       Speed: Up to 12 Mb/sec
>                       Manufacturer: Corsair
>                       Location ID: 0x14612200 / 22
>                       Current Available (mA): 500
>                       Current Required (mA): 500
>                       Extra Operating Current (mA): 0
> 
> --
> --
>                     Corsair ST100 Headset Outpu?t:
> 
>                       Product ID: 0x0a32
>                       Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
>                       Version: 1.00
>                       Serial Number: v0.6
>                       Speed: Up to 12 Mb/sec
>                       Manufacturer: Corsa?ir Components Inc.
>                       Location ID: 0x14612100 / 24
>                       Current Available (mA): 500
>                       Current Required (mA): 500
>                       Extra Operating Current (mA): 0
> 
> --
> --
>                 Corsair ST100 USB 3.1 Hub:
> 
>                   Product ID: 0x0a33
>                   Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
>                   Version: 93.02
>                   Serial Number: v5.0
>                   Speed: Up to 5 Gb/sec
>                   Manufacturer: Corsair Components
>                   Location ID: 0x00112000 / 7
>                   Current Available (mA): 900
>                   Current Required (mA): 0
>                   Extra Operating Current (mA): 0
> 
> IOReg:
> +-o Corsair ST100 USB 3.1 Hub@00112000  <class AppleUSBDevice, id 0x100000b49, registered, matched, active, busy 0 (1 ms), retain 11>
>   | {
>   |   "sessionID" = 0x39b4f6e9d6
>   |   "iManufacturer" = 0x1
>   |   "bNumConfigurations" = 0x1
>   |   "idProduct" = 0xa33
>   |   "bcdDevice" = 0x9302
>   |   "Bus Power Available" = 0x1c2
>   |   "USB Address" = 0x7
>   |   "bMaxPacketSize0" = 0x9
>   |   "iProduct" = 0x2
>   |   "iSerialNumber" = 0x3
>   |   "bDeviceClass" = 0x9
>   |   "Built-In" = No
>   |   "locationID" = 0x112000
>   |   "bDeviceSubClass" = 0x0
>   |   "bcdUSB" = 0x310
>   |   "USB Product Name" = "Corsair ST100 USB 3.1 Hub"
>   |   "PortNum" = 0x2
>   |   "non-removable" = "no"
>   |   "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |   "bDeviceProtocol" = 0x3
>   |   "IOUserClientClass" = "IOUSBDeviceUserClientV2"
>   |   "IOPowerManagement" = {"DevicePowerState"=0x0,"CurrentPowerState"=0x3,"CapabilityFlags"=0x10000,"MaxPowerState"=0x4,"DriverPowerState"=0x3}
>   |   "kUSBCurrentConfiguration" = 0x1
>   |   "Device Speed" = 0x3
>   |   "USB Vendor Name" = "Corsair Components"
>   |   "idVendor" = 0x1b1c
>   |   "IOGeneralInterest" = "IOCommand is not serializable"
>   |   "USB Serial Number" = "v5.0"
>   |   "IOClassNameOverride" = "IOUSBDevice"
>   | }
>   | 
>   +-o Corsair Components@0  <class AppleUSBInterface, id 0x100000b53, !registered, !matched, active, busy 0 (0 ms), retain 4>
>       {
>         "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>         "bcdDevice" = 0x9302
>         "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>         "idProduct" = 0xa33
>         "bInterfaceSubClass" = 0x0
>         "bConfigurationValue" = 0x1
>         "locationID" = 0x112000
>         "USB Interface Name" = "Corsair Components"
>         "IOClassNameOverride" = "IOUSBInterface"
>         "bInterfaceProtocol" = 0x0
>         "idVendor" = 0x1b1c
>         "bAlternateSetting" = 0x0
>         "iInterface" = 0x1
>         "bInterfaceNumber" = 0x0
>         "bInterfaceClass" = 0x9
>         "bNumEndpoints" = 0x1
>       }
>       
> 
> +-o Corsair ST100 USB 2.0 Hub@14612000  <class AppleUSBDevice, id 0x100000b5f, registered, matched, active, busy 0 (1 ms), retain 14>
>   | {
>   |   "sessionID" = 0x39bff5dfe8
>   |   "iManufacturer" = 0x1
>   |   "bNumConfigurations" = 0x1
>   |   "idProduct" = 0xa36
>   |   "bcdDevice" = 0x9302
>   |   "Bus Power Available" = 0xfa
>   |   "USB Address" = 0x15
>   |   "bMaxPacketSize0" = 0x40
>   |   "iProduct" = 0x2
>   |   "iSerialNumber" = 0x3
>   |   "bDeviceClass" = 0x9
>   |   "Built-In" = No
>   |   "locationID" = 0x14612000
>   |   "bDeviceSubClass" = 0x0
>   |   "bcdUSB" = 0x210
>   |   "USB Product Name" = "Corsair ST100 USB 2.0 Hub"
>   |   "PortNum" = 0x2
>   |   "non-removable" = "no"
>   |   "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |   "bDeviceProtocol" = 0x2
>   |   "IOUserClientClass" = "IOUSBDeviceUserClientV2"
>   |   "IOPowerManagement" = {"DevicePowerState"=0x0,"CurrentPowerState"=0x3,"CapabilityFlags"=0x10000,"MaxPowerState"=0x4,"DriverPowerState"=0x3}
>   |   "kUSBCurrentConfiguration" = 0x1
>   |   "Device Speed" = 0x2
>   |   "USB Vendor Name" = "Corsair Components"
>   |   "idVendor" = 0x1b1c
>   |   "IOGeneralInterest" = "IOCommand is not serializable"
>   |   "USB Serial Number" = "v5.0"
>   |   "IOClassNameOverride" = "IOUSBDevice"
>   | }
>   | 
>   +-o AppleUSBInterface@0  <class AppleUSBInterface, id 0x100000b68, !registered, !matched, active, busy 0 (0 ms), retain 4>
>       {
>         "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>         "bcdDevice" = 0x9302
>         "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>         "idProduct" = 0xa36
>         "bInterfaceSubClass" = 0x0
>         "bConfigurationValue" = 0x1
>         "locationID" = 0x14612000
>         "IOClassNameOverride" = "IOUSBInterface"
>         "bInterfaceProtocol" = 0x1
>         "idVendor" = 0x1b1c
>         "bAlternateSetting" = 0x0
>         "iInterface" = 0x0
>         "bInterfaceNumber" = 0x0
>         "bInterfaceClass" = 0x9
>         "bNumEndpoints" = 0x1
>       }
>       
> 
> +-o Corsair ST100 LED Driver@14612200  <class AppleUSBDevice, id 0x100000b74, registered, matched, active, busy 0 (3 ms), retain 15>
>   | {
>   |   "sessionID" = 0x39d0f64f0a
>   |   "iManufacturer" = 0x1
>   |   "bNumConfigurations" = 0x1
>   |   "idProduct" = 0xa34
>   |   "bcdDevice" = 0x2
>   |   "Bus Power Available" = 0xfa
>   |   "USB Address" = 0x16
>   |   "bMaxPacketSize0" = 0x40
>   |   "iProduct" = 0x2
>   |   "iSerialNumber" = 0x3
>   |   "bDeviceClass" = 0x0
>   |   "Built-In" = No
>   |   "locationID" = 0x14612200
>   |   "bDeviceSubClass" = 0x0
>   |   "bcdUSB" = 0x201
>   |   "USB Product Name" = "Corsair ST100 LED Driver"
>   |   "PortNum" = 0x2
>   |   "non-removable" = "yes"
>   |   "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |   "bDeviceProtocol" = 0x0
>   |   "IOUserClientClass" = "IOUSBDeviceUserClientV2"
>   |   "IOPowerManagement" = {"DevicePowerState"=0x0,"CurrentPowerState"=0x4,"CapabilityFlags"=0x8000,"MaxPowerState"=0x4,"DriverPowerState"=0x4}
>   |   "kUSBCurrentConfiguration" = 0x1
>   |   "Device Speed" = 0x1
>   |   "USB Vendor Name" = "Corsair"
>   |   "idVendor" = 0x1b1c
>   |   "IOGeneralInterest" = "IOCommand is not serializable"
>   |   "USB Serial Number" = "0730021189A429AFAECF885AC51B00F5"
>   |   "IOClassNameOverride" = "IOUSBDevice"
>   | }
>   | 
>   +-o ckb-next-daemon  <class IOUSBDeviceUserClientV2, id 0x100000b78, !registered, !matched, active, busy 0, retain 5>
>   |   {
>   |     "IOUserClientCreator" = "pid 50, ckb-next-daemon"
>   |   }
>   |   
>   +-o Corsair ST100 LED Driver@0  <class AppleUSBInterface, id 0x100000b80, registered, matched, active, busy 0 (2 ms), retain 5>
>       {
>         "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>         "bcdDevice" = 0x2
>         "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>         "idProduct" = 0xa34
>         "bInterfaceSubClass" = 0x0
>         "bConfigurationValue" = 0x1
>         "locationID" = 0x14612200
>         "USB Interface Name" = "Corsair ST100 LED Driver"
>         "IOClassNameOverride" = "IOUSBInterface"
>         "bInterfaceProtocol" = 0x0
>         "idVendor" = 0x1b1c
>         "bAlternateSetting" = 0x0
>         "iInterface" = 0x2
>         "bInterfaceNumber" = 0x0
>         "bInterfaceClass" = 0x3
>         "bNumEndpoints" = 0x2
>       }
>       
> 
> +-o Corsair ST100 Headset Output@14612100  <class AppleUSBDevice, id 0x100000b9d, registered, matched, active, busy 0 (12 ms), retain 17>
>   | {
>   |   "sessionID" = 0x39df85608e
>   |   "iManufacturer" = 0x1
>   |   "bNumConfigurations" = 0x1
>   |   "idProduct" = 0xa32
>   |   "bcdDevice" = 0x100
>   |   "Bus Power Available" = 0xfa
>   |   "USB Address" = 0x18
>   |   "bMaxPacketSize0" = 0x8
>   |   "iProduct" = 0x2
>   |   "iSerialNumber" = 0x3
>   |   "bDeviceClass" = 0x0
>   |   "Built-In" = No
>   |   "locationID" = 0x14612100
>   |   "bDeviceSubClass" = 0x0
>   |   "bcdUSB" = 0x110
>   |   "USB Product Name" = "Corsair ST100 Headset Output"
>   |   "PortNum" = 0x1
>   |   "non-removable" = "yes"
>   |   "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |   "bDeviceProtocol" = 0x0
>   |   "IOUserClientClass" = "IOUSBDeviceUserClientV2"
>   |   "IOPowerManagement" = {"DevicePowerState"=0x0,"CurrentPowerState"=0x3,"CapabilityFlags"=0x10000,"MaxPowerState"=0x4,"DriverPowerState"=0x3}
>   |   "kUSBCurrentConfiguration" = 0x1
>   |   "Device Speed" = 0x1
>   |   "USB Vendor Name" = "Corsair Components Inc."
>   |   "idVendor" = 0x1b1c
>   |   "IOGeneralInterest" = "IOCommand is not serializable"
>   |   "USB Serial Number" = "v0.6"
>   |   "IOClassNameOverride" = "IOUSBDevice"
>   | }
>   | 
>   +-o AppleUSBInterface@0  <class AppleUSBInterface, id 0x100000bab, registered, matched, active, busy 0 (2 ms), retain 5>
>   |   {
>   |     "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |     "bcdDevice" = 0x100
>   |     "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>   |     "idProduct" = 0xa32
>   |     "bInterfaceSubClass" = 0x1
>   |     "bConfigurationValue" = 0x1
>   |     "locationID" = 0x14612100
>   |     "IOClassNameOverride" = "IOUSBInterface"
>   |     "bInterfaceProtocol" = 0x0
>   |     "idVendor" = 0x1b1c
>   |     "bAlternateSetting" = 0x0
>   |     "iInterface" = 0x0
>   |     "bInterfaceNumber" = 0x0
>   |     "bInterfaceClass" = 0x1
>   |     "bNumEndpoints" = 0x0
>   |   }
>   |   
>   +-o AppleUSBInterface@1  <class AppleUSBInterface, id 0x100000bac, registered, matched, active, busy 0 (3 ms), retain 5>
>   |   {
>   |     "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |     "bcdDevice" = 0x100
>   |     "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>   |     "idProduct" = 0xa32
>   |     "bInterfaceSubClass" = 0x2
>   |     "bConfigurationValue" = 0x1
>   |     "locationID" = 0x14612100
>   |     "IOClassNameOverride" = "IOUSBInterface"
>   |     "bInterfaceProtocol" = 0x0
>   |     "idVendor" = 0x1b1c
>   |     "bAlternateSetting" = 0x0
>   |     "iInterface" = 0x0
>   |     "bInterfaceNumber" = 0x1
>   |     "bInterfaceClass" = 0x1
>   |     "bNumEndpoints" = 0x0
>   |   }
>   |   
>   +-o AppleUSBInterface@2  <class AppleUSBInterface, id 0x100000bae, registered, matched, active, busy 0 (2 ms), retain 5>
>   |   {
>   |     "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>   |     "bcdDevice" = 0x100
>   |     "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>   |     "idProduct" = 0xa32
>   |     "bInterfaceSubClass" = 0x2
>   |     "bConfigurationValue" = 0x1
>   |     "locationID" = 0x14612100
>   |     "IOClassNameOverride" = "IOUSBInterface"
>   |     "bInterfaceProtocol" = 0x0
>   |     "idVendor" = 0x1b1c
>   |     "bAlternateSetting" = 0x0
>   |     "iInterface" = 0x0
>   |     "bInterfaceNumber" = 0x2
>   |     "bInterfaceClass" = 0x1
>   |     "bNumEndpoints" = 0x0
>   |   }
>   |   
>   +-o AppleUSBInterface@3  <class AppleUSBInterface, id 0x100000bb0, registered, matched, active, busy 0 (2 ms), retain 5>
>       {
>         "IOCFPlugInTypes" = {"2d9786c6-9ef3-11d4-ad51-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
>         "bcdDevice" = 0x100
>         "IOUserClientClass" = "IOUSBInterfaceUserClientV3"
>         "idProduct" = 0xa32
>         "bInterfaceSubClass" = 0x0
>         "bConfigurationValue" = 0x1
>         "locationID" = 0x14612100
>         "IOClassNameOverride" = "IOUSBInterface"
>         "bInterfaceProtocol" = 0x0
>         "idVendor" = 0x1b1c
>         "bAlternateSetting" = 0x0
>         "iInterface" = 0x0
>         "bInterfaceNumber" = 0x3
>         "bInterfaceClass" = 0x3
>         "bNumEndpoints" = 0x1
>       }
>       
> 
> Daemon log:
>     ckb-next: Corsair RGB driver 0.3.2
> [I] Root controller ready at /var/run/ckb0
> [I] Connecting Corsair ST100 LED Driver at /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> 
> [I] Caught signal 15
> [I] Closing root controller
> [I] Removed device path /var/run/ckb0
>     ckb-next: Corsair RGB driver 0.3.2
> [I] Root controller ready at /var/run/ckb0
> [I] Connecting Corsair ST100 LED Driver at /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> 
> [I] Caught signal 15
> [I] Closing root controller
> [I] Removed device path /var/run/ckb0
>     ckb-next: Corsair RGB driver 0.3.2
> [I] Root controller ready at /var/run/ckb0
> [I] Connecting Corsair ST100 LED Driver at /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> [I] Disconnecting /var/run/ckb1
> [I] Removed device path /var/run/ckb1
> [W] add_hid (usb_mac.c:795): Got unknown SINGLE_EP handle (I: 64, O: 64, F: 0)
> 
> GUI log:
> Path to settings: "/Users/Rob/Library/Preferences/com.ckb-next.ckb-next.plist"
> Looking for old settings in: "/Users/Rob/Library/Preferences/com.ckb.ckb.plist"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/gradient"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/heat"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/invaders"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/pinwheel"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/rain"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/random"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/ripple"
> Scanning "/Applications/ckb-next.app/Contents/Resources/ckb-next-animations/wave"
> objc[410]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff91d9b210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x113ad2dc8). One of the two will be used. Which one is undefined.
>

**Comment by tatokis** [comment]
Apparently it hasn't made it to release yet. Here's a fresh build with the latest changes.
http://ckb-next.info/mac/ckb-next_v0.3.2-33-g2fb5ba6_10.11-SDK.dmg

```
3d811e89ddde46b5a9140fb47e617eb5a0268c9b395fc536053701d7366c332b  ckb-next_v0.3.2-33-g2fb5ba6_10.11-SDK.dmg
```

**Comment by RobRoyce** [comment]
Awesome, works perfectly now. Thanks!
