### ISSUE TITLE
k95 Platinum mute button "Indicate mute" and Lock lights under performance tab do not work

### ISSUE THREAD

**Issue by bennybenjaman** [ckb-next/ckb-next#341]
Mute button : On/Off/Unknown does not display any color. On does not save the color from the color selection menu. 

***LOCK LIGHTS ARE NOT RGB. NO ISSUE WITH LOCK LIGHTS***

**Comment by ZirconiumX** [comment]
I believe this is #271.

**Comment by bennybenjaman** [comment]
Solved!
