### ISSUE TITLE
Question: How to do macros on OXS High Sierra?

### ISSUE THREAD

**Issue by tylersmith34** [ckb-next/ckb-next#348]
# Something else

I have a k95 RGB and an MBP running High Sierra.  I'm trying to configure macros with the G keys and I am struggling with a way to do it.  I've read that the G keys don't know about key redirects, so mapping left control to left command, left windows to left option, and left alt to left control are unknown to the macros.  MacOS doesn't know about alt and windows keys, what do I do to make macros work?  The G keys are the reason I bought this keyboard (when I had a Windows laptop for work, now I was switched to Mac) and I'd hate to lose the G keys, they're very powerful when programming.

**Comment by tylersmith34** [comment]
I tried the Google Group, no one has responded to my question.

**Comment by ZirconiumX** [comment]
> Something else
>
> I have a k95 RGB and an MBP running High Sierra. I'm trying to configure
> macros with the G keys and I am struggling with a way to do it. I've read
> that the G keys don't know about key redirects, so mapping left control to
> left command, left windows to left option, and left alt to left control are
> unknown to the macros.
>
This is correct; if you press left alt in a macro, you get left alt. While
it might be possible to change that in the daemon, the macro and rebinding
code is something we haven't touched.

> MacOS doesn't know about alt and windows keys, what do I do to make macros
> work?
>
No, but CKB knows about them, and the keys lalt and ralt are mapped to
option, and lwin and rwin are mapped to command.

> The G keys are the reason I bought this keyboard (when I had a Windows
> laptop for work, now I was switched to Mac) and I'd hate to lose the G
> keys, they're very powerful when programming.
>
Truthfully I haven't found I needed them with my Strafe RGB.

>

**Comment by tylersmith34** [comment]
When I map the lwin, lalt, lctrl keys to mac keys, they work fine, it's just as macros they don't work. I've tried software like karabiner and using the Mac keyboard preferences to change bindings but nothing affects the G keys. 

I'm a heavy IntelliJ user and the G keys are a lifesaver, enabling me to be significantly faster.

**Comment by ZirconiumX** [comment]
> When I map the lwin, lalt, lctrl keys to mac keys, they work fine,
>

They already *are* Mac keys.

>it's just as macros they don't work. I've tried software like karabiner

Karabiner is incompatible with CKB, so no, it won't work.

>and using the Mac keyboard preferences

The Mac keyboard preferences don't know what G-keys are, so no, it won't
work.

>to change bindings but nothing affects the G keys.

> I'm a heavy IntelliJ user and the G keys are a lifesaver, enabling me to
> be significantly faster.
>
I don't doubt that, but I'm confused what you're trying to do. What does
the macro record window say when you try to record, say, Command-C?

>

**Comment by tylersmith34** [comment]
The macro record window shows the windows names, lwin, lalt, lctrl rather than the mac names, so the macros don't do anything even though I've mapped in CKB.  Without CKB the OS recognizes the control, windows, and alt keys as if they were on an Apple produced keyboard (that's what I meant by the OS keyboard preferences, not the G keys).  If I write lcmd in the macro, the key modifier is ignored. I can get screenshots tomorrow.

**Comment by ZirconiumX** [comment]
CKB uses the Windows names, not the Mac names, because there's a Windows
key on your keyboard, not a command key.

**Comment by tylersmith34** [comment]
Ok that makes sense.  Here is a screenshot of the macro for G16.  I also attached the ckb report.  When I use this G key, nothing happens.  I'm pressing the left CTRL key which is mapped to left command.
![screen shot 2019-01-10 at 8 08 36 pm](https://user-images.githubusercontent.com/9055581/51008932-8e736580-1513-11e9-85d9-76610aee5f86.png)


[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2747802/ckb-next-dev-detect-report.gz)

![screen shot 2019-01-10 at 8 05 20 pm](https://user-images.githubusercontent.com/9055581/51008871-43595280-1513-11e9-879f-dc0e90932211.png)

**Comment by ZirconiumX** [comment]
I'm pretty sure command is lalt not lctrl. Try that.

**Comment by tylersmith34** [comment]
No, that creates ç.  I have this mapping:

| K95 key name (left side) | Mac key name |
| ---- | ---- |
Ctrl | Command
Windows | Control
Alt | Option

When I use `Record Macro` start button, `Ctrl` + `C` (K95 key names), it produces the screenshot from above `.+lctrl,+c,-lctrl,-c`

**Comment by ZirconiumX** [comment]
Ignore the mapping. Since we've already established CKB ignores it (for
better or worse), it's irrelevant.

I guess the only alternative key would be Windows. Try Win-C.

**Comment by ZirconiumX** [comment]
Given what you said before, Windows control maps to Apple control, and
Windows alt maps to Apple option.

**Comment by tylersmith34** [comment]
No not quite, Windows control maps to Mac Command, but you said that mapping is irrelevant but I think I see your point.  What threw me off is that `lwin` is making copy/paste work which is `command` + `c` on the Mac keyboard and that's not how I mapped `lwin`.  I thought I had tried `lwin` before, guess not.

**Comment by ZirconiumX** [comment]
Yes, because the key corresponding to Windows and the key corresponding to
Command are the same key. If you plug a Windows keyboard into a Mac, and
press Windows, you will get Command. If you plug an Apple keyboard into a
PC and press Command, you will get Windows.

**Comment by tylersmith34** [comment]
Right, I was starting to realizing that.  The mappings are really hard for me to ignore for some reason.  Thank you for shedding light on this for me!

**Comment by ZirconiumX** [comment]
You're welcome.
