### ISSUE TITLE
Line 51 Command not found

### ISSUE THREAD

**Issue by jesus20282** [ckb-next/ckb-next#349]
~/Desktop/ckb-next-master$ ./quickinstall 
./quickinstall: line 51: cmake: command not found
An error occurred,
press enter to exit.

I have this error but there's just another user with this problem (with line 21/23 I believe), I haven't found a solution the only thing I notice is that after:

sudo apt-get install build-essential libudev-dev qt5-default zlib

I get this:
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

I tried to solve and nothing, I use Ubuntu 16.04.5 LTS

**Comment by ZirconiumX** [comment]
You need CMake. We have build from source instructions [here](https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#build-from-source).

**Comment by jesus20282** [comment]
Thanks.
