### ISSUE TITLE
copy configurations (with animations) to new machine

### ISSUE THREAD

**Issue by ToadJamb** [ckb-next/ckb-next#351]
I have installed a new os and would like to port over my existing ckb-next configuration. The basic colors and such appear to be saved on the hardware (keyboard), but the animations and most of the other configuration does not appear to get saved and is therefore lost under the new os. I have access to both os's, so I can move/copy files around if I need to. I have looked around a fair bit and am unsure how this is intended to work. I'm hoping that someone with more knowledge/experience with ckb can provide guidance.

**Comment by ZirconiumX** [comment]
If you go into the mode selection drop-down menu at the bottom of it is an
option which says "Configure Profiles" or something along those lines. That
will let you export your animation as a .ckb file, which you can then
import on your new machine.
