### ISSUE TITLE
Esc key not working when ckb-next is running

### ISSUE THREAD

**Issue by ivan0013** [ckb-next/ckb-next#354]
# Bug report

## General information
The <kbd>esc</kbd> key is not working when ckb-next is running. If I close the application, the key works perfectly, but on the moment I run ckb, it stops working. 

By "the kay doesn't work" I mean that nothing happens when I press it. 

I'm running Kubuntu 18.04 and Plasma 5.12.6 and my keyboard is a K65 RGB

### Source
I built manually using quickinstall script

## Logs & crash reports
I can't see any other info than the generated log
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/2763860/ckb-next-dev-detect-report.gz)

## What is the program's current behavior?
system doesn't recognize the <kbd>esc</kbd> key press

## What is the expected behavior of the program?
Normal behaviour on <kbd>esc</kbd> key press

Thank you for the help

**Comment by tatokis** [comment]
Please join us on IRC. http://webchat.freenode.net/?channels=%23ckb-next&uio=d4

**Comment by ZirconiumX** [comment]
Hopefully you remembered to dump the old firmware before you upgraded?

**Comment by tatokis** [comment]
bump

**Comment by ivan0013** [comment]
Hi guys. Sorry about the delay. When I arrived home that afternoon, my brother was using the keyboard and, of course, he made the upgrade without asking. I've been trying to get the firmware from corsair customer service, but I always get the same answer "We don't provide old firmware versions". I was searching for the internet but I couldn't get it either. 

Of course, the firmaware upgrade was the solution to the problem.

Sorry for the inconvenience.

**Comment by tatokis** [comment]
> "We don't provide old firmware versions"

Yeah, that's expected.

Oh well; thank you anyway
