### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by hevanaa** [ckb-next/ckb-next#380]
On wiki page https://github.com/ckb-next/ckb-next/wiki/Linux-Installation

ckb-next is now available in stable Fedora 28 and 29 repositories:

https://bugzilla.redhat.com/show_bug.cgi?id=1670508

I consider myself no longer the maintainer of the package now when someone else took upon the task to request the inclusion of it in the official Fedora repository. You could update the wiki and remove my personal johanh/ckb repo (I won't probably update it anymore). If someone else want to maintain the CentOS/RHEL build they can copy it freely.

**Comment by hevanaa** [comment]
You can now install the package from the official Fedora repo with 'sudo dnf install ckb-next'. I guess it will also soon become available in Gnome Software in Fedora (when appstream data is updated).

**Comment by ZirconiumX** [comment]
I just updated the wiki page, hopefully it looks okay.
