### ISSUE TITLE
Indicator LED activation delay

### ISSUE THREAD

**Issue by pjbrazendale** [ckb-next/ckb-next#391]
System: Gentoo Linux
Kernel: 4.19.27-r1 Gentoo Sources
Device: Corsair K68 Mechanical LED Keyboard
Driver Version: ckb-next 0.4.0
Build Type: Using the ./quickinstall script
Init system: Open RC

Current Behaviour:

When using the keyboard when toggling numlock, caps lock or scroll lock there is a delay of about 4/5 seconds between pressing the key and the relevant LED toggling on the keyboard to reflect the status.

Expected Behaviour:

When toggling the numlock, caps lock or scroll lock key the associated status LED should update immediately with the press of the relevant key.

**Comment by ZirconiumX** [comment]
This is a known issue (see #377, though we've known about it for a year), and unfortunately will require some internal refactoring.

The main issue is that we have a indicator thread and the RGB thread, and they're fighting over the keyboard, resulting in delays until the indicator thread finally gets chance to update.
