### ISSUE TITLE
[Bug] [Linux] Corsair K68 Left Ctrl & Shift are the same

### ISSUE THREAD

**Issue by Cerberooo** [ckb-next/ckb-next#394]
# Bug report

## General information

Source: ckb-next (0.4.0-1) package in AUR 

## What is the program's current behavior?

When I start the ckb-next-daemon, the left ctrl and left shift keys behave the same.

Binding tab: 

![binding_1](https://user-images.githubusercontent.com/16780924/55404548-6a468400-5558-11e9-9377-981860b09e69.png)

When I change the modifier to left-ctrl this happens:

Binding tab for left-ctrl: 

![binding_ctrl](https://user-images.githubusercontent.com/16780924/55404720-cf01de80-5558-11e9-8676-391b54a712bc.png)

Binding tab for left-shift:

![binding_shift](https://user-images.githubusercontent.com/16780924/55404730-d5905600-5558-11e9-9a72-75db9fd45ae9.png)

[ckb-next-report-1554209745.zip](https://github.com/ckb-next/ckb-next/files/3034033/ckb-next-report-1554209745.zip)

**Comment by ZirconiumX** [comment]
cc @tatokis

**Comment by tatokis** [comment]
Please check that you don't have Ctrl bound to Shift in the settings tab.
![2d9751b80be8](https://user-images.githubusercontent.com/6003656/55450347-745b9780-55d7-11e9-9536-4308cd001f14.png)

**Comment by Cerberooo** [comment]
Solved it... thanks!
But why this was the default after a fresh install?

**Comment by tatokis** [comment]
I'm pretty sure it's not.

What probably happened here is that you accidentally scrolled while moving the cursor over the dropdowns and that changed the setting without you realising.

**Comment by Cerberooo** [comment]
You're probably right. Thanks for your help!
