### ISSUE TITLE
CMake Error While Installing cannot find target directory

### ISSUE THREAD

**Issue by TLable** [ckb-next/ckb-next#401]
---
# Corsair STRAFE RGB Keyboard.
---
## When I install I get no device detected. That was the same after 2 attempts I uninstalled to try older/newer version, after attemping other version I am having the install stop with a CMake error.
---
### Source

---

## It should finish installing quickinstall file, which I am greatful whom put the time and thankful for all the hard work to create a compiled builder. The version that works installs but misses my keyboard  driver and after clearing the sys of the older files and attempting install of all dependencies and new version of cbk-next-master the install stops with a CMake error: 
[ 50%] Built target mviz
[ 51%] Automatic MOC and UIC for target ckb-next
[ 51%] Built target ckb-next_autogen
[100%] Built target ckb-next
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/bin/ckb-next-dev-detect
-- Installing: /usr/local/bin/ckb-next-daemon
CMake Error at src/daemon/cmake_install.cmake:65 (file):
  file INSTALL destination: /usr/lib/systemd/system is not a directory.
Call Stack (most recent call first):
  src/cmake_install.cmake:43 (include)
  cmake_install.cmake:42 (include)

## Looking into CMake to have checked its dir is not the issue. It may be possible that its using the wrong version of a dependency or has missing dependencies. Or could be the driver.  

##Anyone know if there is a workaround for me. Thank you.
---

**Comment by tatokis** [comment]
Which distro are you running?
What does this command return?
```
ls -la /usr/lib/systemd/system
```

**Comment by TLable** [comment]
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

I return the line:
-rw-r--r-- 1 root root 201 Apr 19 23:54 /usr/lib/systemd/system

**Comment by tatokis** [comment]
What about
```
sudo cat /usr/lib/systemd/system
```

**Comment by TLable** [comment]
returns line:
[Unit]
Description=Corsair Keyboard Daemon

[Service]
ExecStart=/usr/bin/ckb-daemon
Restart=always
StandardOutput=syslog
StandardError=inherit
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by tatokis** [comment]
If you delete it `sudo rm /usr/lib/systemd/system` and then re-run quickinstall. What happens?
Does the file come back? `sudo cat /usr/lib/systemd/system`

**Comment by TLable** [comment]
Do you know keyboard shortcuts to search for /use/lib/systemd/system/

**Comment by tatokis** [comment]
If you run `sudo cat /usr/lib/systemd/system` it will either show its contents if it exists, or it will say No such file or directory.

**Comment by TLable** [comment]
I think I've got a dual architecture failsafe to stop important files from
being removed, cause I've added architecture 'i386' & '1386' and then I run
the line returns:
RM: cannot remove '/usr/lib/systemd/system/': Not a directory

**Comment by TLable** [comment]
Y es it is both not a directory when remove is used 'Not a directory' &
running a daemon when searched for contents
[Unit]
Description=Corsair Keyboard Daemon

[Service]
ExecStart=/usr/bin/ckb-daemon
Restart=always
StandardOutput=syslog
StandardError=inherit
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

**Comment by tatokis** [comment]
Please run the commands exactly as I type them.
Try:
```
sudo rm /usr/lib/systemd/system
sudo mkdir /usr/lib/systemd/system
```

Do note that there is no `/` in the end of either of those commands.

After that, quickinstall should work normally.

**Comment by TLable** [comment]
Could you tell me a shortcut to locating those files? For example if I
wanted to find cosmic dir.

Thank you Tasos. I ran both code for ckb the quickinstall next and is
working fine.

**Comment by TLable** [comment]
Have you used Origin in the past?

**Comment by TLable** [comment]
I attemnpted to remove the file with the suspect suspect architecture arch.(?), which also included:
i386
1386
System now seems to have cleared the calls of errors while updating.
