### ISSUE TITLE
System Extension Not Allowed still appearing in cbd-next even though Karbiner Elements is already installed.

### ISSUE THREAD

**Issue by Ninja73737** [ckb-next/ckb-next#402]
Do I have to uninstall Karbiner Elements to install this software properly? And if that is the case can I reinstall it afterwards? Also, I don't see a way in the karbiner elements software to back up my profile, I could be missing it but otherwise I will have to recreate all the rebindings I have set up. Let me know if there is an alternative.

**Comment by ZirconiumX** [comment]
CKB uses the kernel extension from Karabiner Elements, but conflicts with
Karabiner because otherwise both programs would grab the device. You need
to uninstall Karabiner Elements to allow CKB to use your keyboard. You
might also need to enable the kernel extension in System Preferences.

>

**Comment by Ninja73737** [comment]
I'm actually just using the software with a mouse. Is there any way the
software can both be used at once with separate devices? For instance if
I'm only controlling the internal keyboard with karabiner, and I'm using
ckb-next to control my mouse would that cause a conflict?

**Comment by ZirconiumX** [comment]
Yeah, because there's only the one driver, sadly.
