### ISSUE TITLE
STRAFE RGB not working after resume from sleep/suspend

### ISSUE THREAD

**Issue by aaronovz1** [ckb-next/ckb-next#403]
My Strafe RGB keyboard doesn't respond after the system goes into suspend and I wake it up using the mouse. Sometimes I can get it working again without rebooting by unplugging/replugging the USB cables and then using the mouse click on "Switch User" on the login prompt.

* Linux Mint 19
* Kernel 4.15 
* ckb-next 0.4.0

Is there any logs or other information I can provide?

**Comment by ZirconiumX** [comment]
This is a known issue with Linux, but we can't do anything about it. Let me find the issue.

**Comment by ZirconiumX** [comment]
[Here it is](https://github.com/ckb-next/ckb-next/issues/368#issuecomment-463428947).
