### ISSUE TITLE
[Bug Report] [Linux] [Sabre RGB] Blinking wite light and ckb-next crashes

### ISSUE THREAD

**Issue by nomis6432** [ckb-next/ckb-next#409]
I'm using arch Linux with plasma DE and installed ckb-next through the AUR.

I recently upgraded the firmware of my mouse (sabre RGB) to v3.04 and this worked fine but now after having suspended my pc (I don't think this was the first time I suspended/rebooted after upgrading the firmware but I can't say for sure) the rgb's of the mouse are blinking in wite and the mouse doesn't work. When I try to use ckb-next it says that there is a firmware upgrade available (v3.04) which I have already installed. When I opt to install the firmware update ckb-next [crashes with a Segmentation fault](https://pastebin.com/L3M9TtC0). [Here](https://pastebin.com/LxjfRa4w) are the logs. When I opt not to install the firmware upgrade I am unable to save any changes to the settings and the prompt with the firmware update keeps popping up. When I stop ckb-next-deamon I am able to move the cursor with my mouse but it's very choppy and unusable.

Is it possible to downgrade the firmware version to see if that's the problem?

**Comment by ZirconiumX** [comment]
Right, you have all the symptoms of a firmware upgrade failure, please join us in IRC by pressing the blue button on the README, so I can give you the older firmware and test it.
