### ISSUE TITLE
Export to iCUE

### ISSUE THREAD

**Issue by BrunoVox** [ckb-next/ckb-next#415]
I use both Ubuntu and Windows on my PC. The iCUE lacks a random preset, which you have implemented in CKB. I was wondering if it is possible to export a profile I made in Ubuntu to Windows. If it is possible, would iCUE import it without problems, even if it hasn't a random preset implemented?

**Comment by ZirconiumX** [comment]
Sadly not, the content and format is entirely different between the two,
and it would limit our development room. Sorry.
