### ISSUE TITLE
QObject error when changing modes via cli

### ISSUE THREAD

**Issue by prankousky** [ckb-next/ckb-next#417]
Hi,

I just tried scripting activation of different modes on my `K95 RGB Platinum`. When I `ckb-next --mode normal` or `ckb-next --mode vim`, I get `QObject::startTimer: Timers cannot have negative intervals`. 

However, the modes **do** change. I just don't understand why this message pops up. They happen *no matter* **which** mode I try and activate. But then the mode will change on my keyboard. 

Use case, I am trying to write a bash script determine which program I am currently using, and if it is one of the defined programs, will change my mode to it's appropriate value.
Is there something I need to change, or is this normal output (or: what output should I expect when changing modes like this)?

Thanks for your support.

**Comment by ZirconiumX** [comment]
It's a harmless warning; ignore it. It happens whenever you open up the
ckb-next GUI, which is what you are doing, but otherwise has no effect.

**Comment by fleischie** [comment]
Hehe. I was just thinking about that very thing. I don't think there is an obvious issue, that causes that warning.

But I will keep an eye open, whenever I need to debug the GUI next time around.

**Comment by tatokis** [comment]
There's nothing we can do about this. It's Qt emitting it.

This is the line that causes it https://github.com/ckb-next/ckb-next/blob/6d09c1c718a034f046bd91ffc994cb6dad40c903/src/gui/kbfirmware.cpp#L20
