### ISSUE TITLE
Scimitar Pro RGB, Mac Command button seems to executing with left click

### ISSUE THREAD

**Issue by davidbdeath** [ckb-next/ckb-next#428]
Scimitar Pro RGB Mac Command button seems to executing with left click. CKB-next version 4.
Happens after click on CKB in the menu bar.

**Comment by tatokis** [comment]
Can you generate and attach a report? 

Does this still happen if you make a new profile?

**Comment by davidbdeath** [comment]
I figured out my dumb mistake.
