### ISSUE TITLE
M65 mouse no beeing recognized

### ISSUE THREAD

**Issue by luanalbineli** [ckb-next/ckb-next#429]
Hi guys,

I've installed ckb-next on my Linux Mint 19.1, but unfortunately it not recognize my M65 (non rgb) mouse. Searching on the known issues, I've found the `usb.h` constant file, and I didn't found my idProduct: `0x1b05`.

I've also tried another usb ports (3.0), also unsuccessfully.

### Source
  * built manually using quickinstall script

## Logs & crash reports

Attach:
ckb-next-dev-detect - Tue Jun 11 15:43:30 -03 2019

Kernel: Linux luan-Predator-PH315-51 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

OS Version:
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa

USB Devices:
Couldn't open device, some information will be missing

Bus 001 Device 006: ID 1b1c:1b05 Corsair 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1b1c Corsair
  idProduct          0x1b05 
  bcdDevice            2.26
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      74
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0007  1x 7 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      47
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      25
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval               1

Dmesg on current boot:
Jun 11 15:41:55.479197 luan-Predator-PH315-51 kernel: usb 1-3: New USB device found, idVendor=1b1c, idProduct=1b05
Jun 11 15:41:55.479389 luan-Predator-PH315-51 kernel: usb 1-3: Product: Corsair M65 Gaming Mouse
Jun 11 15:41:55.479484 luan-Predator-PH315-51 kernel: usb 1-3: Manufacturer: Corsair
Jun 11 15:41:55.482074 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:1B1C:1B05.0001/input/input9
Jun 11 15:41:55.482176 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0001: input,hidraw0: USB HID v1.11 Mouse [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input0
Jun 11 15:41:55.482186 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:1B1C:1B05.0002/input/input10
Jun 11 15:41:55.482282 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0002: input,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input1
Jun 11 15:41:55.482292 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:1B1C:1B05.0003/input/input11
Jun 11 15:41:55.482388 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0003: input,hidraw2: USB HID v1.11 Device [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input2
Jun 11 15:43:09.645155 luan-Predator-PH315-51 kernel: usb 1-4: New USB device found, idVendor=1b1c, idProduct=1b05
Jun 11 15:43:09.646108 luan-Predator-PH315-51 kernel: usb 1-4: Product: Corsair M65 Gaming Mouse
Jun 11 15:43:09.646484 luan-Predator-PH315-51 kernel: usb 1-4: Manufacturer: Corsair
Jun 11 15:43:09.646852 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:1B1C:1B05.0007/input/input19
Jun 11 15:43:09.709205 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0007: input,hidraw0: USB HID v1.11 Mouse [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-4/input0
Jun 11 15:43:09.709937 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1B1C:1B05.0008/input/input20
Jun 11 15:43:09.769227 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0008: input,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-4/input1
Jun 11 15:43:09.769888 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.2/0003:1B1C:1B05.0009/input/input21
Jun 11 15:43:09.829261 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0009: input,hidraw2: USB HID v1.11 Device [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-4/input2

Dmesg on last boot:
Jun 10 10:51:41.498818 luan-Predator-PH315-51 kernel: usb 1-3: New USB device found, idVendor=1b1c, idProduct=1b05
Jun 10 10:51:41.498997 luan-Predator-PH315-51 kernel: usb 1-3: Product: Corsair M65 Gaming Mouse
Jun 10 10:51:41.499087 luan-Predator-PH315-51 kernel: usb 1-3: Manufacturer: Corsair
Jun 10 10:51:41.502978 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:1B1C:1B05.0001/input/input9
Jun 10 10:51:41.503076 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0001: input,hidraw0: USB HID v1.11 Mouse [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input0
Jun 10 10:51:41.503086 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:1B1C:1B05.0002/input/input10
Jun 10 10:51:41.503179 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0002: input,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input1
Jun 10 10:51:41.503189 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:1B1C:1B05.0003/input/input11
Jun 10 10:51:41.503285 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0003: input,hidraw2: USB HID v1.11 Device [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input2
Jun 11 15:39:12.921824 luan-Predator-PH315-51 kernel: usb 1-3: New USB device found, idVendor=1b1c, idProduct=1b05
Jun 11 15:39:12.928069 luan-Predator-PH315-51 kernel: usb 1-3: Product: Corsair M65 Gaming Mouse
Jun 11 15:39:12.928470 luan-Predator-PH315-51 kernel: usb 1-3: Manufacturer: Corsair
Jun 11 15:39:12.929066 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:1B1C:1B05.0007/input/input25
Jun 11 15:39:12.985874 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0007: input,hidraw0: USB HID v1.11 Mouse [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input0
Jun 11 15:39:12.986411 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:1B1C:1B05.0008/input/input26
Jun 11 15:39:13.045878 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0008: input,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input1
Jun 11 15:39:13.046534 luan-Predator-PH315-51 kernel: input: Corsair Corsair M65 Gaming Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:1B1C:1B05.0009/input/input27
Jun 11 15:39:13.105843 luan-Predator-PH315-51 kernel: hid-generic 0003:1B1C:1B05.0009: input,hidraw2: USB HID v1.11 Device [Corsair Corsair M65 Gaming Mouse] on usb-0000:00:14.0-3/input2

Daemon on current boot:
-- Logs begin at Mon 2019-06-10 00:17:12 -03, end at Tue 2019-06-11 15:43:14 -03. --
Jun 11 15:41:56.711515 luan-Predator-PH315-51 systemd[1]: Started Corsair Keyboards and Mice Daemon.
Jun 11 15:41:56.712824 luan-Predator-PH315-51 ckb-next-daemon[989]: ckb-next: Corsair RGB driver 0.4.0-27-g10e6b54
Jun 11 15:41:56.713037 luan-Predator-PH315-51 ckb-next-daemon[989]: [I] Root controller ready at /dev/input/ckb0

Daemon on last boot:
-- Logs begin at Mon 2019-06-10 00:17:12 -03, end at Tue 2019-06-11 15:43:14 -03. --
Jun 11 15:37:25.405215 luan-Predator-PH315-51 systemd[1]: Started Corsair Keyboards and Mice Daemon.
Jun 11 15:37:25.406383 luan-Predator-PH315-51 ckb-next-daemon[11634]: ckb-next: Corsair RGB driver 0.4.0-27-g10e6b54
Jun 11 15:37:25.406586 luan-Predator-PH315-51 ckb-next-daemon[11634]: [I] Root controller ready at /dev/input/ckb0
Jun 11 15:41:39.475581 luan-Predator-PH315-51 ckb-next-daemon[11634]: [I] Caught signal 15
Jun 11 15:41:39.475581 luan-Predator-PH315-51 ckb-next-daemon[11634]: [I] Closing root controller
Jun 11 15:41:39.475581 luan-Predator-PH315-51 ckb-next-daemon[11634]: [I] Removed device path /dev/input/ckb0
Jun 11 15:41:39.472485 luan-Predator-PH315-51 systemd[1]: Stopping Corsair Keyboards and Mice Daemon...
Jun 11 15:41:39.492177 luan-Predator-PH315-51 systemd[1]: Stopped Corsair Keyboards and Mice Daemon.

Dev nodes:
/dev/input/ckb0
/dev/input/ckb0/pid
989
/dev/input/ckb0/version
0.4.0-27-g10e6b54
/dev/input/ckb0/connected

Environment:
QT_QPA_PLATFORMTHEME=qt5ct
QT_ACCESSIBILITY=1
XDG_SESSION_DESKTOP=cinnamon
XDG_CURRENT_DESKTOP=X-Cinnamon
QT_BEARER_POLL_TIMEOUT=-1

Kernel command line:
BOOT_IMAGE=/boot/vmlinuz-4.15.0-51-generic root=UUID=640976a4-0f93-4f6c-848c-dee70720b392 ro quiet splash vt.handoff=1

## What is the program's current behavior?
It is showing a "No connected devices" message.

## What is the expected behavior of the program?
Show the M65 tab configuration?

**Comment by tatokis** [comment]
The M65 non RGB is a completely different device from the RGB one, with its own protocol.
It is not high on the priority list, and probably won't be supported for a while.

If you want to try something, replace the usb id in usb.h of the `M95` with yours and see if that does anything.

**Comment by luanalbineli** [comment]
Hi, tatokis, thanks for the reply.
This device is supposed to be supported, don't? At least it is listed in the Supported Hardware list.
About the change, is it just replace the usb id and run the `./quickinstall` script again? Or I need to compile something else?

**Comment by ZirconiumX** [comment]
We support the M65 RGB, M65 Pro RGB and M65 Elite RGB. The RGB there means
it uses a specific protocol that we support. The M65 non-RGB does not use
this protocol, so we cannot support it.

**Comment by luanalbineli** [comment]
Hi guys, thanks for your replies.

I've made the changes, as @tatokis sugested, and it partially worked. The DPI previously configured in the Windows driver was applied, but the configuration is "read only". The changes that I made in ckb does not reflect in the mice.

@ZirconiumX , about the support, the non RGB mice is listed as supported:
- M65:
  - non-RGB <-------------
  - PRO RGB

Anyway, it already helped me a lot, thanks.

**Comment by tatokis** [comment]
Yeah, that's a mistake. Apologies, I'll fix it ASAP.

Regarding the mouse, if it does in fact share the same protocol as the M95, you can try adding this quirk in your linux kernel cmdline (through your bootloader), and see if you can actually write the configuration to the mouse, like changing DPI.

`usbcore.quirks=1b1c:1b05:gn`

**Comment by Strazzom** [comment]
> If you want to try something, replace the usb id in usb.h of the `M95` with yours and see if that does anything.

I would like to report that I got the M65 working using this method. It does seem to use the same protocol, I can change the DPI successfully (it is somewhat janky though, it needs proper support). At the moment, I have it being recognized as the M95.

Saving the config to device causes it to stop working when I boot into Windows with it, and the mouse does not work unless the ckb-next program is started first. The DPI buttons are also misaligned (the highest one is interpreted as the sniper button).

**Comment by gravityfargo** [comment]
Stale
