### ISSUE TITLE
Not detecting USB/Keyboard in Mac OS Catalina beta

### ISSUE THREAD

**Issue by MikesTooLz** [ckb-next/ckb-next#431]
[ckb-next-report-1560474201.gz](https://github.com/ckb-next/ckb-next/files/3288594/ckb-next-report-1560474201.gz)
I installed the new Mac OS Catalina beta and CKB-Next no longer can detect my corsair mouse and keyboard. I know that this version of Mac OS is beta and just wanted to post this in here as a head up for you guys. Things I have already tried:

-Re-Installed
-Rebooted several times
-under (System Preverences > Security & Privacy > Input Monitoring) I tried adding ckb-next  in the allowed apps, then rebooted.
-unplugged and replugged USB devices and moved them around to different ports.

**Comment by tatokis** [comment]
Of course they broke things again.
Generate and attach a report, please

**Comment by MikesTooLz** [comment]
Report has been added, sorry about that.

**Comment by tatokis** [comment]
Can you send a screenshot of the input monitoring menu?

**Comment by MikesTooLz** [comment]
![Screen Shot 2019-06-13 at 9 15 32 PM](https://user-images.githubusercontent.com/5142569/59476797-69678380-8e20-11e9-8d13-09f7acdd8ca9.png)

**Comment by tatokis** [comment]
I meant `Security & Privacy > Input Monitoring`

**Comment by MikesTooLz** [comment]
![Screen Shot 2019-06-13 at 9 18 12 PM](https://user-images.githubusercontent.com/5142569/59476914-e09d1780-8e20-11e9-9f51-196ba97a8190.png)
[ckb-next-report-1560475132.gz](https://github.com/ckb-next/ckb-next/files/3288628/ckb-next-report-1560475132.gz)

OK, I added it back into the input monitoring and then quit/relaunched ckb-next here is the screen shot and another report.

**Comment by tatokis** [comment]
First, try unplugging and replugging one of your corsair devices.
I don't know how this works, but using the `+` can you add a specific program based on a path?
If so, try adding `/Library/Application Support/ckb-next-daemon` to the list of applications and then unplug/replug your devices again.

See if that helps

**Comment by MikesTooLz** [comment]
BINGO!!!!!

I added `/Library/Application Support/ckb-next-daemon` to the list, then unplugged / replugged keyboard & mice but nothing happened. I rebooted the system and now it'
![Screen Shot 2019-06-13 at 9 34 26 PM](https://user-images.githubusercontent.com/5142569/59477406-104d1f00-8e23-11e9-96ff-5cc62fba6102.png)
s working again.

**Comment by tatokis** [comment]
That's excellent.

Can you generate another report? I want to see if the error changed after you unplugged and replugged

**Comment by MikesTooLz** [comment]
[ckb-next-report-1560476235.gz](https://github.com/ckb-next/ckb-next/files/3288659/ckb-next-report-1560476235.gz)

Thanks a lot.
You got a PayPal address I can send a few bucks your way?

**Comment by tatokis** [comment]
You're welcome. I'll have to come up with something so that people in the future can know what to do in order to get it working, preferably before 10.15 comes out. The error code doesn't seem to have changed.

I'll leave this issue open

If you want, you can use `tatokis [ a t ] windowslive [ d o t ] com`. Of course replace the the at and the dot.

**Comment by MikesTooLz** [comment]
FYI, after todays beta update, I had to do this all over again.

**Comment by atylmo** [comment]
I'm also having issues with the beta. I'm using a KVM switch (which works fine with two Windows PCs) and in the previous betas I couldn't use the keyboard at all without rebooting while the KVM was switched to the Mac. Sometimes ckb-next was able to see it. With the current beta I can decently reliably use the keyboard, but ckb-next won't detect it. It shows up in System Information under USB, though.

I got it to work once by adding the daemon and then also running the commands from https://github.com/ckb-next/ckb-next/issues/49#issuecomment-428004748 but it stopped again.

My keyboard is an original STRAFE RGB.

**Comment by ItsEcholot** [comment]
![image](https://user-images.githubusercontent.com/2771251/65817700-ddc90580-e20a-11e9-8986-3e16ffc3900c.png)

I can't seem to find a way to add the `/Library/Application Support/ckb-next-daemon` to the Input Monitoring section in the latest beta version.

**Comment by tatokis** [comment]
Not even if you click on the lock? Maybe you can generate and attach a report?

**Comment by ItsEcholot** [comment]
Managed to get the + to appear after installing a software that correctly requests that permission (BetterTouchTool) and after adding the `ckb-next-daemon` there everything works again.

**Comment by tatokis** [comment]
I didn't realise we needed to somehow request permission in a specific way.
I thought it happened the moment an application tried to open an HID device.

I'll have a quick look to see if I can figure out how/why this happens.

**Comment by ItsEcholot** [comment]
Maybe because this is a root level daemon it behaves differently just a thought.

**Comment by tatokis** [comment]
I think this is exactly why it happens. I'll try to make a workaround, but I can't test it

**Comment by ItsEcholot** [comment]
Would be up for testing it if it helps

**Comment by tatokis** [comment]
Quick unrelated question. To those of you who have tested ckb-next in Catalina, how did you get it to run? Did you have to run any commands, or did it just work like normal?

From what I understand we need to pay apple to get out software "notarized" before it can run on Catalina (which might be the end of ckb-next for mac), and I am trying to figure out what is going on.

https://developer.apple.com/news/?id=09032019a

**Comment by ItsEcholot** [comment]
Besides this issue it worked like normal but maybe this is also because I already had it installed before I upgraded. The only thing I noticed that ckb sometimes wouldn't start the animations again after the keyboard got removed and then plugged in again (would display though that it's connected).

As far as I know the notarisation part only applies when you sign your application. And even then I think you can grant an exception in the security & privacy section of the Settings app when you run an unnotarised application.

**Comment by tatokis** [comment]
@ItsEcholot thank you for your response. I guess we'll have to find out.

In the meantime, I found out that the way to get the daemon to be authorised is to create a launch agent and start the agent as the current user. Then, the prompt pops up, and once you allow access, you have to restart the daemon running as root.

Since the daemon is designed to only run as root, I made a workaround that lets it start as a normal user, ask for hid permission, and then quit once it receives it.

I'll implement this in the GUI and it should be good to go.

![8965c4a54b7d](https://user-images.githubusercontent.com/6003656/66274416-24f86b80-e887-11e9-9710-a31f99c8fd37.png)

**Comment by Vermyndax** [comment]
I just installed Catalina and a fresh build of ckb-next, and surprise... I was bit by this one. Did a new release with this fix get pushed through yet?

**Comment by tatokis** [comment]
Still working on it. Will most likely have a new release tomorrow/soon-ish.

**Comment by tatokis** [comment]
@Vermyndax @ItsEcholot Please try this build http://ckb-next.info/mac/ckb-next_v0.4.1-30-gd4ed59e_10.12-SDK.dmg

```
4b0947dcb4e0b58624ad3cb63ae08d9c18f8af8eba83cf0203284715a7f9e336  ckb-next_v0.4.1-30-gd4ed59e_10.12-SDK.dmg
```

If it works okay, I'll merge the code to master and make a new release tomorrow.

**Comment by Vermyndax** [comment]
That worked for me, thanks!

**Comment by jeffqchen** [comment]
> @Vermyndax @ItsEcholot Please try this build http://ckb-next.info/mac/ckb-next_v0.4.1-30-gd4ed59e_10.12-SDK.dmg
> 
> ```
> 4b0947dcb4e0b58624ad3cb63ae08d9c18f8af8eba83cf0203284715a7f9e336  ckb-next_v0.4.1-30-gd4ed59e_10.12-SDK.dmg
> ```
> 
> If it works okay, I'll merge the code to master and make a new release tomorrow.

This one worked for me. Thanks for the quick respond.

**Comment by ItsEcholot** [comment]
> @Vermyndax @ItsEcholot Please try this build http://ckb-next.info/mac/ckb-next_v0.4.1-30-gd4ed59e_10.12-SDK.dmg
> 
> ```
> 4b0947dcb4e0b58624ad3cb63ae08d9c18f8af8eba83cf0203284715a7f9e336  ckb-next_v0.4.1-30-gd4ed59e_10.12-SDK.dmg
> ```
> 
> If it works okay, I'll merge the code to master and make a new release tomorrow.

Can confirm this works. ckb correctly requests the permission. The daemon restart command that gets executed seems to have a weird timing (>5 secs. after I plugged in the keyboard). Because of this delay I at first thought something went wrong or that I had to reboot manually. In the end it worked though.

**Comment by tatokis** [comment]
Unfortunately the GUI can only check if the daemon has permission every >10 seconds due to launchctl. That's why you are getting that delay. I could not work around it.

**Comment by ItsEcholot** [comment]
Ah I see makes sense. Well in that case it's for sure good enough for now

**Comment by tatokis** [comment]
Any idea how to clear the database of the allowed applications?

Just as I am about to release 0.4.2, I can't get the prompt to show up anymore, and ckb-next-daemon says there's already access when the application isn't even listed under Input Monitoring.

**Comment by tatokis** [comment]
Never mind that I guess. It started working now. No idea what changed.

**Comment by ItsEcholot** [comment]
That's actually all it took for me, removing the ckb-next-daemon from the Input Monitoring section. Not sure if I had to restart the daemon or replug the keyboard but it appeared after that.

**Comment by tatokis** [comment]
Just to verify. Please remove ckb-next-daemon from the list, then click the uninstall ckb-next button under settings.

Once you've done that, try this build and tell tell me if it works.
http://ckb-next.info/mac/ckb-next_v0.4.1-34-gea54480_10.12-SDK.dmg

```
c9d1b5e8a5977b8a87c6800be69c246b00b132f41bb9ef4514644ac8af7525c0  ckb-next_v0.4.1-34-gea54480_10.12-SDK.dmg
```

**Comment by ItsEcholot** [comment]
Worked perfectly! Good idea adding that information about having to wait for the daemon restart.

**Comment by Lemz97** [comment]
Im having the same issues, when i go into security and privacy the plus sign doesnt show in input monitoring

**Comment by tatokis** [comment]
Click the uninstall ckb-next button. Reboot, then download and install https://github.com/ckb-next/ckb-next/releases/download/v0.4.2/ckb-next_v0.4.2.dmg

**Comment by Lemz97** [comment]
ckb-next-daemon doesn't show in the security and privacy

**Comment by tatokis** [comment]
Can you generate and attach a report please?

**Comment by tatokis** [comment]
@ItsEcholot I thought you might be interested
![ec5a5d3a6aef](https://user-images.githubusercontent.com/6003656/66461515-debb2c00-ea81-11e9-9d8e-de29ea27327e.png)

**Comment by ItsEcholot** [comment]
Interesting it stayed in the list for me but now my device doesn't appear in ckb-next anymore not sure what changed over night...

[ckb-next-report-1570626964.gz](https://github.com/ckb-next/ckb-next/files/3707507/ckb-next-report-1570626964.gz)

Also not sure if this has anything to do with Catalina but it seems the stability was greatly reduced since I made the os update. It seems it doesn't recognise devices anymore after standby but I will investigate this further and generate a report when I encounter it again.

**Comment by kalanimatthews** [comment]
I have this exact problem. I did Catalina upgrade with no issue. I have 0.4.2  ckb. Today it no longer sees my keyboard and can't add to input monitoring like the above poster.
![Screen Shot 2020-02-25 at 4 13 04 PM](https://user-images.githubusercontent.com/57369192/75288160-be4dfd00-57e9-11ea-9844-170f297f1049.png)

**Comment by Ricardonacif** [comment]
Hey guys,

I have a fresh install of MacOS Catalina (10.15.3 (19D76)). The "Input Monitoring" tab on Security & Privacy also doesn't show anything. I've tried reinstalling it and some other things mentioned here, but no success. I've added a report.

Thanks,

[ckb-next-report-1584912166.gz](https://github.com/ckb-next/ckb-next/files/4366379/ckb-next-report-1584912166.gz)

**Comment by kalanimatthews** [comment]
@Ricardonacif , I just migrated to my new mac with 10.15.3. Had the same problems. This is what I did that fixed it: 
1. Open System Preferences > Security and Privacy > General. I unplug/replugged keyboard with Sys Pref window open and it asked for me to allow the software first in General window, so I did.
2. In System Preferences, switch to Security & Privacy > Privacy tab > Input Monitoring. Mine showed nothing.
3. Quit ckb-next and restart it. Now it popped up in the Input Monitoring window. I allowed it then had to log into the console screen launched by the script. 
4. Enjoy - this worked for me and is working like normal now.

**Comment by xguse** [comment]
For what its worth wrt @kalanimatthews note above:

Just unplugging and replugging as in the written step 1 was not enough for me. I had to go to System Prefs > Keyboard and click `Change Keyboard Type...` to get the rest of the process to work.

But it does seem to work! Thank GOD.

I am working at home and the damn wavy breathing effect was seriously detracting from my productivity. But then I am pretty ADD.

Anywho. Stay healthy y'all.
