### ISSUE TITLE
Script could not be loaded

### ISSUE THREAD

**Issue by patrickmay** [ckb-next/ckb-next#436]
My Strafe keyboard on my iMac frequently reverts to all white lights.  When I open ckb-next, I get the error 'The "Wave" script could not be loaded.  Please check your animation directory.'  The only way I've found to fix it is to completely reinstall ckb-next, but then it happens again.

**Comment by tatokis** [comment]
Please click the generate report button (in the settings tab) once this happens and attach the report to the issue

**Comment by sjthespian** [comment]
I just started seeing the same thing this morning after a reboot, the report is attached.
[ckb-next-report-1588452969.gz](https://github.com/ckb-next/ckb-next/files/4568919/ckb-next-report-1588452969.gz)
