### ISSUE TITLE
Leds not showing right color on profile switch on K95 Platinum

### ISSUE THREAD

**Issue by Termanater13** [ckb-next/ckb-next#438]
The issue is when I switch profiles on my keyboard via the software or by the profiles button. The issue does get fixed when I mess with the color settings for that profile, or I adjust the brightness. I have tried to recreate the issue in windows via ICUE software and I could not, this leads me to think its ckb-next as the issue. This issue may also just be a hardware issue unique to my keyboard. Current color of the leds also do not seem to have an effect on the issue since I have 2 profiles when I switch back and forth the leds should not change color and the issue pops up, even when the profile key is used with one profile is after the other.

LEDs that are the issue are TOPBAR 4, 5, 15, 16, and 17.
Camera settings were altered to make the issue more apparent since default point and click on my Samsung S8 made it hard to see it when it is quite obvious to the eye. while the left and right are in separate pictures the issue does happen at the same time.

Issue on left side
![LeftSideIssue](https://user-images.githubusercontent.com/10302218/60397529-27c32200-9b1c-11e9-8c33-0c64112f86c0.jpg)
left Side after adjusting brightness
![LeftSideFixed](https://user-images.githubusercontent.com/10302218/60397532-2c87d600-9b1c-11e9-9c87-b255bebe6674.jpg)
Right Side Issue
![RightSideIssue](https://user-images.githubusercontent.com/10302218/60397533-2f82c680-9b1c-11e9-8d85-2d9f07768d84.jpg)
Right Side after adjusting brightness
![RightSideFixed](https://user-images.githubusercontent.com/10302218/60397535-31e52080-9b1c-11e9-94ee-2d97f32890dc.jpg)

ckb-next version: 0.4.0-27-g10e6b54
k95 firmware: 3.21
Linux OS: Ubuntu 18.04

**Comment by tatokis** [comment]
It's most likely a hardware issue. iCUE uses hardware brightness control, whereas ckb-next does it in software.
Try setting the brightness in iCUE all the way up and then when selecting colour, make it darker than usual, to simulate a "lower brightness".

**Comment by tatokis** [comment]
Sorry, I completely misread your issue. It looks like an issue in the GUI possibly not detecting the colour changes.

Does this issue happen if you have an animation set?

**Comment by Termanater13** [comment]
> Does this issue happen if you have an animation set?
This happens when the profiles changes, and animations fix the colors when the animation first activates. after the animation activates the issue is gone. If I did not have an animation set I would see the issue all the time.

**Comment by wansti** [comment]
I'm having the exact same issue. Cycling brightness settings fixes it, switching to another profile brings it back.

**Comment by Creative-user-name** [comment]
You might have done this by now, but for anybody new reading this (as I mentioned in #718) I "solved" it by animating the top bar in the same colour as the static colour and even forgot, that that was a thing.

This should also work, if you have different colours through the top bar, just hit it with a breathing animation, you could even make any animation random animation and just set its opacity to 0%

**Comment by tatokis** [comment]
Some years and some frustration later, this should be fixed in master. It'd be appreciated if someone could verify it.
