### ISSUE TITLE
Device Support Request - M55 RGB PRO

### ISSUE THREAD

**Issue by Unaccounted4** [ckb-next/ckb-next#440]
Report:
[ckb-next-report-1562169446.gz](https://github.com/ckb-next/ckb-next/files/3355768/ckb-next-report-1562169446.gz)

Corsair M55 RGB PRO 

Keep on rocking!

**Comment by tatokis** [comment]
Unfortunately, the bad news is that despite this being a wired mouse, Corsair are using the new protocol that we don't have support for yet. It will probably be a while before we get it working. I think they'll be switching most new devices to it going forward, so we'll eventually have to support it.

That said, can you please run `sudo usbhid-dump -d 1b1c:1b70`

And after that, compile this https://github.com/ckb-next/getUsbString and run

```
sudo ./getUsbString 0x1b1c 0x1b70 4
```
and
```
sudo ./getUsbString 0x1b1c 0x1b70 5
```

Please paste the output of all of those here.

**Comment by Unaccounted4** [comment]
Here you go: 
`sudo usbhid-dump -d 1b1c:1b70
003:012:003:DESCRIPTOR         1562186967.142327
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 19 00 29 97 15 00 25 01 75 01
 95 98 81 02 05 08 19 01 29 03 25 01 75 01 95 03
 91 02 75 05 95 01 91 01 C0

003:012:002:DESCRIPTOR         1562186967.142570
 06 42 FF 09 02 A1 01 15 00 26 FF 00 75 08 95 40
 09 02 81 02 C0

003:012:001:DESCRIPTOR         1562186967.142859
 06 42 FF 09 01 A1 01 15 00 26 FF 00 75 08 95 40
 09 01 81 02 95 40 09 01 91 02 C0

003:012:000:DESCRIPTOR         1562186967.143125
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 20
 15 00 25 01 95 20 75 01 81 02 75 10 95 02 05 01
 09 30 09 31 16 01 80 26 FF 7F 81 06 75 08 95 01
 05 01 09 38 15 81 25 7F 81 06 C0 C0`

`sudo ./getUsbString 0x1b1c 0x1b70 4
Read 12 bytes
Raw (hex): 0c 03 56 00 30 00 33 00 30 00 30 00 
String: V0300`

`sudo ./getUsbString 0x1b1c 0x1b70 5
Read 10 bytes
Raw (hex): 0a 03 42 00 50 00 30 00 30 00 
String: BP00`

**Comment by Halamix2** [comment]
What could be done to help getting some kind of support?

**Comment by Wrizz** [comment]
Any updates on this? Would be greatly appreciated!

**Comment by Halamix2** [comment]
I was able to decode only what is in gist (mode, DPI, color), I don't know how to get x/y data (so basically I can change color and DPI but cannot use the mouse as a mouse) or how to integrate any of that into ckb-next

**Comment by Halamix2** [comment]
There is now incomplete and experimental Wireshark Dissector for Bragi: https://github.com/Halamix2/bragi_logs

**Comment by KatanaKa-bedrock** [comment]
I tried what @Unaccounted4 did, but it sadly didn't help.

**Comment by LuPro** [comment]
After seeing a thread about the new Ironclaw (#558) which also uses the bragi protocol and apparently had some preliminary test code for the bragi protocol added which allowed basic mouse functionality, I tried a lucky test if the bragi branch (or more like: the k95-xt branch, as for some reason git told me they are equal and forwarded me to that one?) would work for the M55; It did not :smile: 
I have 0 knowledge of the code base but stumbled my way around and did this:
- add a new macro for the device in `usb.h` (a macro `P_M55_RGB_PRO` with fitting product ID, as well as `IS_M55(kb)`)
- add device to `USES_BRAGI` macro in `usb.h`
- add said macro to `device_desc models[]` in `usb.c`
- add said macro to `product_str()` in `usb.c`

After compiling and running that my keyboard (K95 on old protocol) continued working, but the mouse broke - cursor was stuck and LEDs continued with their aggravating slowly-shifting rainbow :joy: 

Didn't really expect it to work as it's unfinished support for a new protocol made for a different device, but thought it was worth a shot - if you need anything I can help with (data, packets, testing, ...), please do tell, I'd love to support the endeavor of getting bragi properly supported (I'd love to (help) work on reverse engineering it myself and writing the code, but I have (almost) no prior experience with WireShark and frankly, too little time for a project of such a caliber).

**Comment by andrey-shigantsov** [comment]
I need this. Is implementation expected?

**Comment by GhostDog98** [comment]
Thought it might be useful to add some more data.
sudo usbhid-dump -d 1b1c:1b70
```
003:002:003:DESCRIPTOR         1629331488.953210
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 19 00 29 97 15 00 25 01 75 01
 95 98 81 02 05 08 19 01 29 03 25 01 75 01 95 03
 91 02 75 05 95 01 91 01 C0

003:002:002:DESCRIPTOR         1629331488.956204
 06 42 FF 09 02 A1 01 15 00 26 FF 00 75 08 95 40
 09 02 81 02 C0

003:002:001:DESCRIPTOR         1629331488.959208
 06 42 FF 09 01 A1 01 15 00 26 FF 00 75 08 95 40
 09 01 81 02 95 40 09 01 91 02 C0

003:002:000:DESCRIPTOR         1629331488.962211
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 20
 15 00 25 01 95 20 75 01 81 02 75 10 95 02 05 01
 09 30 09 31 16 01 80 26 FF 7F 81 06 75 08 95 01
 05 01 09 38 15 81 25 7F 81 06 C0 C0
```
And 
```
sudo ./getUsbString 0x1b1c 0x1b70 4
Read 12 bytes
Raw (hex): 0c 03 56 00 30 00 33 00 30 00 30 00 
String: V0300
```
```
sudo ./getUsbString 0x1b1c 0x1b70 5
Read 10 bytes
Raw (hex): 0a 03 42 00 50 00 30 00 30 00 
String: BP00
```
I might boot back into windows later and programmatically wireshark a bunch of options for the mouse. Will update if i get time.

**Comment by agoshigagoroba** [comment]
bump to this

**Comment by noneistaken** [comment]
Bump, I have this mouse too.

**Comment by n0n467** [comment]
The M55 mouse may be supported but I have an M55 RGB PRO and it's not detected.

**Comment by n0n467** [comment]
@Halamix2 I don't really know much about these things but would it be easy to add support for the M55 RGB PRO or is it to different from the M55 ?

**Comment by tatokis** [comment]
@n0n467 You probably need to update ckb-next. You have to run a ckb-next-git package (or manually build from git). Support for the mouse was added after 0.4.4 was released.

**Comment by n0n467** [comment]
@tatokis I already built the latest version from source but my mouse still isn't detected.

**Comment by tatokis** [comment]
If it's wireless, it's a different device and not yet supported. If not, generate a report and attach it.

**Comment by n0n467** [comment]
@tatokis how can I make a report ?

**Comment by n0n467** [comment]
Sorry, after uninstalling and reinstalling the same version, it started working.
Thank for your fast replies anyway.
