### ISSUE TITLE
Caps Lock

### ISSUE THREAD

**Issue by tad1073** [ckb-next/ckb-next#442]
## General information
There's a lag when enabling and disabling caps lock and the delay is not consistant.
### Source
How and where did you get this program, e.g.:
  * Built manually using quickinstall script.

**Comment by rotarypot** [comment]
this might be a duplicate of [issue 303](https://github.com/ckb-next/ckb-next/issues/303)

**Comment by Mario-119** [comment]
I have this same issue on my K70 RGB Mk2. It's not just the caps lock, also the num lock and the scroll lock.

**Comment by tatokis** [comment]
Duplicate of https://github.com/ckb-next/ckb-next/issues/391
