### ISSUE TITLE
Crsair Veangeance RGB Pro

### ISSUE THREAD

**Issue by s7relok** [ckb-next/ckb-next#444]
Hello,

I will soon have a pack of Corsair Veangeance RGB Pro RAM sticks.

Can you tell me what type of info you will need to help to build the support? 

Regards,

**Comment by michaelothing** [comment]
If you dual boot this ram will keep it's settings if set from windows icue unlike the rest of the products. I'm looking for a solution for the AIO water coolers.

**Comment by kmasaryk** [comment]
@michaelothing You're assuming people have Windows installed. I do not, nor do I have any plans to do so. It would be great to get this working with the Vengeance RGB sticks.

If your using an ASUS mb, it sounds like [OpenAuraSDK](https://gitlab.com/CalcProgrammer1/OpenAuraSDK) might work.

**Comment by michaelothing** [comment]
I assume nothing. I simply stated a fact that it holds settings from icue. I have signed in to windows once in the last year.

**Comment by gravityfargo** [comment]
closing in favor of #589
