### ISSUE TITLE
Can't keybind combination alt+s on mac

### ISSUE THREAD

**Issue by postcollective** [ckb-next/ckb-next#446]
Its entirely possible I don't know what I'm doing at all - using the GUI to bind keys to a Corsair Scimitar mouse. 

The goal is to bind Alt+s to the "1" side button on the mouse.

I'm able to bind single 'typing' values to the mouse buttons, but when I select a 'modifier' it erases the 'typing' value, and vice versa.

Next, I tried recording a macro, but only the mouse commands get recorded, and typing an alt+s just results in "ß" being recorded, which is not the value I'm looking for.  

Is there a solution for this to be found in the GUI?

**Comment by tatokis** [comment]
Apologies for the late reply.
Macro recording is currently not supported for non corsair keyboards.

If you are still interested, you can manually type a macro such as `+lalt,+s,-s,-lalt` and it will do what you want.
