### ISSUE TITLE
Mac OS Look up and Smart Zoom binding option

### ISSUE THREAD

**Issue by davidbdeath** [ckb-next/ckb-next#448]
It would be awesome if I could bind a mouse button to both the built-in Lookup and Smart zoom function in Mac OS. Typically these are only available to trackpad and magic mouse users. I use better touch tool to map them to a keyboard button then bind a button on my scimitar to the keyboard shortcut. I'd prefer to select them directly.

**Comment by tatokis** [comment]
I'm not entirely sure it's possible. We are not emulating trackpads, and I don't think Karabiner's kernel driver supports it for the magic mouse.

I'll have a quick look to see if it's possible.
