### ISSUE TITLE
M65 RGB Elite DPI Limit

### ISSUE THREAD

**Issue by robert78901** [ckb-next/ckb-next#452]
M65 Elite RGB in ckb-next 0.4.0 is limited to 12000 DPI rather than 18000 DPI

**Comment by tatokis** [comment]
Duplicate of https://github.com/ckb-next/ckb-next/issues/197

**Comment by tatokis** [comment]
This should be fixed now. Please have a look at https://github.com/ckb-next/ckb-next/issues/197#issuecomment-521842565
