### ISSUE TITLE
Configure Lift Height

### ISSUE THREAD

**Issue by Sur3** [ckb-next/ckb-next#457]
I've some problems with my Corsair Scimitar RGB being inaccurate and someone suggested I should reconfigure my Lift Height, as this can be set for the sensor at least in the windows driver software. Sadly this seems not possible in ckb-next yet?

**Comment by tatokis** [comment]
> Sadly this seems not possible in ckb-next yet?

What do you mean by that?

![liftheight](https://user-images.githubusercontent.com/6003656/63766907-de514200-c8d4-11e9-9eca-70e43bc36d66.JPG)
