### ISSUE TITLE
ckb 0.4.1 Requires Mac 10.14 or higher

### ISSUE THREAD

**Issue by a-chaudhari** [ckb-next/ckb-next#458]
I'm running High Sierra on my mac and I received an update notification from ckb-next this morning.  

After upgrading I've found I can no longer start the application.  I get an error that the application requires 10.14.  

This change wasn't documented anywhere so I'm assuming it is a bug.

Deleting the GUI application and reinstalling the 0.4.0 installer fixes the issue.

**Comment by tatokis** [comment]
Apologies. It is not meant to require 10.14.
We'll fix it ASAP

**Comment by tatokis** [comment]
You can downgrade for now and press `Remind me later` on the update message. It will only pop up once on startup.

I have also updated the changelog to alert people that I have removed the existing builds to prevent further issues from being opened.
https://github.com/ckb-next/ckb-next/commit/31157634976ea9aef69b0b4e899fe2bd1b693ff2

**Comment by tatokis** [comment]
The issue has now been fixed. You can either upgrade from 0.4.0, or install the 0.4.1 from here https://github.com/ckb-next/ckb-next/releases/download/v0.4.1/ckb-next_v0.4.1.dmg

**Comment by a-chaudhari** [comment]
Hello,  I tried installing 0.4.1 again with a fresh download and I still have the same issue.  I can't open the gui tool as it complains about requiring 10.14 

Downgrading resolves the issue.

**Comment by tatokis** [comment]
Unfortunately we made another mistake. Can you please try downloading again? It should be fixed properly now.
Apologies

**Comment by fleischie** [comment]
@a-chaudhari I re-uploaded new binaries, which should have the correct deployment target set up. (I couldn't test it for non-Mojave, though.)

Please try again now, and let us know, if the error still exists. 🙇
