### ISSUE TITLE
Add ST100 to Wiki's supported hardware list

### ISSUE THREAD

**Issue by xDazlD** [ckb-next/ckb-next#467]
## What is the ~~program's~~ wiki's current behaviour?
Doesn't list ST100 as supported
## What would you like it to do instead?
Show it as supported. I'm having no issues with it on ckb-next 0.4.1.
## Any other notes & comments?
![Photo of working ST100 on ckb-next](https://user-images.githubusercontent.com/32212089/64577153-278ca180-d36b-11e9-93aa-477a45aa63db.jpg)

**Comment by tatokis** [comment]
Done
