### ISSUE TITLE
Can this program be used or tested without having the actual hardware?

### ISSUE THREAD

**Issue by michaelsjackson** [ckb-next/ckb-next#474]
Before buying any of the supported hardware I would like to test what could be possible, so is this working without having the hardware? Some emulation mode? All colors should be displayed on that qwerty gui instead, for development purposes this could be very useful as well, e.g. when being elsewhere, on the train, where your rgb qwerty is not with you.

**Comment by tatokis** [comment]
https://github.com/ckb-next/FaKeyboard
You need to modprobe vhci-hcd, compile/get the usbip binary bundled with the kernel source, and then `sudo usbip attach -r 127.0.0.1 -b 1-1 ` after running one of the above. Best bet is to try mouse and kb, others may not work.
