### ISSUE TITLE
Ironclaw Wireless support

### ISSUE THREAD

**Issue by horen20wash** [ckb-next/ckb-next#483]
Hello,

It would be great to have support for Corsair Ironclaw wireless..

Thanks,
-Horen

**Comment by halfred888** [comment]
+1

**Comment by amore101** [comment]
Exactly! I tried ICUE and v0.4.2, they did not work. Thank you!

**Comment by gustabot42** [comment]
There is something a rookie could do to help with this?

**Comment by fierogtfan** [comment]
+1  I am also interested to learn how I can help contribute.

**Comment by pukingleopard** [comment]
I would like to help with this as well.

**Comment by MordicusEtCubitus** [comment]
Below is the attached file of my IRONCLAW RGB Wireless mouse as detected 
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/4365226/ckb-next-dev-detect-report.gz)

If it can help

**Comment by ZirconiumX** [comment]
I'm going to close this in favour of #558 because that issue has a bounty.
