### ISSUE TITLE
K95 - Linux Mint 19.2 - Music visualization not working

### ISSUE THREAD

**Issue by KevinF-R** [ckb-next/ckb-next#494]
How and where did you get this program?
-Package from PPA.

What is the program's current behavior? - Its either single color, or lacks of all color. Originally when i downloaded about a month ago it worked fine for aprox 3 days.

As i am not sure what would be useful, i'll leave it here and check for questions.

**Comment by Extarys** [comment]
Linux Mint 19.3 here. For me it works, but I need to put the sensibility to 100 and it looks like the lights are behind the music and not very responsive. It mostly capture my mic. Muting it, there is only CTRL on the light blinking while using spotify.

Anyway, I'm sure people are still working on it anyway so I'll just update it from time to time.
