### ISSUE TITLE
RGB lights shut off after update

### ISSUE THREAD

**Issue by Termanater13** [ckb-next/ckb-next#506]
I recently updated my install to the latest released version on manjaro linux via the AUR repository. the lights worked at first, then my menu key kept freaking out(I think that was a hardware issue due to a drop of water) then on next startup the leds do not work while ckb-next is running. I even removed the release version and installed the git version via the AUR and still having the same issue. As a trouble shooting measure I booted into windows(dual boot on system) to see if iCue would give me the same issue and it does not. The leds also work while ckb-next is not running.

keyboard: Corsair K95 RGB Platinum

**Comment by jrwest** [comment]
Ran into a similar issue twice with the same hardware on Ubuntu 20.04.1. Moving/removing `~/.config/ckb-next/ckk-next.conf` and restarting brought things back (with my saved configuration lost ofc).
