### ISSUE TITLE
Pipe creation fix

### ISSUE THREAD

**Issue by bennybenjaman** [ckb-next/ckb-next#507]
When creating a pipe under animations using /tmp/ckbpipe00*  if the user deletes said animation in ckb-next, the ckbpipe000 file will remain in the tmp folder until reboot. If  the user tries to recreate a new pipe animation and uses ckbpipe000 without deleting the original fifo file, the new animation will not be applied. The ckbpipe000 file needs to be deleted and recreated perform proper function.

**Comment by OvermindDL1** [comment]
Huh bot?
