### ISSUE TITLE
Mouse not being detected

### ISSUE THREAD

**Issue by psychedtitan** [ckb-next/ckb-next#508]
After downloading the catalina 10.15.1 update my mouse is no longer being recognized

**Comment by Fateliu** [comment]
equally

**Comment by rudo-rov** [comment]
Same here, 10.15.1.
Clean install of ckb-next 0.4.2. My Harpoon Wireless RGB is not recognized. The ckb-next-daemon does not prompt for the input monitoring.

**Comment by amore101** [comment]
My ironclaw wireless RGB is not recognized.

**Comment by ZirconiumX** [comment]
So, the OP hasn't actually specified which mouse they have, and all the "me too" replies already have open issues because they're not currently supported.
