### ISSUE TITLE
Minimized Startup

### ISSUE THREAD

**Issue by ProfessorStrawberry** [ckb-next/ckb-next#510]
## What is the program's current behaviour?
on reboot or cold start ckb is opening the window itself and the tray icon.
## What would you like it to do instead?
Have the tray icon start up, but keep the window minimized.
## Any other notes & comments?
I am using Arch with KDE.

BTW. I love your project.

**Comment by ZirconiumX** [comment]
You mean `ckb-next --background`?

**Comment by ProfessorStrawberry** [comment]
is that a feature already? because i cannot find it. or is it a startup command?

**Comment by tatokis** [comment]
This bug was fixed in git. Either wait for the next release or upgrade to the git package from AUR.

**Comment by ProfessorStrawberry** [comment]
Thank you!
