### ISSUE TITLE
Macro's not working Ubunt 19.10

### ISSUE THREAD

**Issue by davidbdeath** [ckb-next/ckb-next#518]
I tried this as a macro mapped to a button on my scimitar pro rgb and it does nothing. When i map in Mac OS it works fine.

+lctrl, +lbrace, -lbrace, -lctrl,

**Comment by tatokis** [comment]
There's nothing bound to `Ctrl [` on Ubuntu.

Linux has actual support for back and forward buttons on mice. Just bind the buttons to 
Mouse -> Special Button -> Backward/Forward

**Comment by davidbdeath** [comment]
1. you can create nearly any keyboard shortcut in Ubuntu.
2. Ctrl + [ is one of Fire Fox's default short cuts.

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly?redirectlocale=en-US&as=u&redirectslug=Keyboard+shortcuts&utm_source=inproduct
