### ISSUE TITLE
Add Solus package to the Wiki

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [ckb-next/ckb-next#525]
## Any other notes & comments?
The ckb-next is available in Solus, as `ckb`, as well as a devellopement version as `ckb-devel` (Same version for both currently, as far i´m aware)
https://dev.getsol.us/D7355
Despite that, It is not mentionned in the wiki : https://github.com/ckb-next/ckb-next/wiki/Linux-Installation

**Comment by ZirconiumX** [comment]
Added, thanks!
