### ISSUE TITLE
Brightness setting on K70 (non-RGB) affects mouse instead of keyboard

### ISSUE THREAD

**Issue by Polywoky** [ckb-next/ckb-next#533]
Hardware:

* Corsair K70 LUX Red LED
* Corsair CH-9304011-AP, SCIMITAR Pro RGB

When ckb-next is running my keyboard is stuck at full brightness, and when I try to change the brightness setting, either by pressing the brightness button on the keyboard or by changing it in ckb-next, the mouse brightness changes instead, and the keyboard is unaffected.

Changing the brightness setting for the keyboard affects the brightness setting for the mouse, the values seem to  be locked together.

When I quit from ckb-next the brightness button on the keyboard works as intended.

**Comment by tatokis** [comment]
> Changing the brightness setting for the keyboard affects the brightness setting for the mouse, the values seem to be locked together.

That's intentional. Use per-mode brightness under settings if you do not want that.

> When ckb-next is running my keyboard is stuck at full brightness, and when I try to change the brightness setting, either by pressing the brightness button on the keyboard or by changing it in ckb-next, the mouse brightness changes instead, and the keyboard is unaffected.

That should be fixed

Next time please follow the issue template and provide a report.
