### ISSUE TITLE
"Unable to seize USB handle, continuing anyway..." after using USB switcher

### ISSUE THREAD

**Issue by ellismichaelc** [ckb-next/ckb-next#536]
Hello,

I'm using 3 Corsair devices (flawlessly, up until this point) with my 2015 MBP and CKB-Next pre built. Version 0.4.2. I have also built my own and run it successfully, which did not solve the issue.

Devices:
-Scimitar Pro RGB
-K70 RGB
-MM800 RGB POLARIS

The issue started when I introduced a USB switcher. This simply moves the 3 devices to my other MBP which I use solely for work. Both computers have CKB-Next (same version), and both setups independently work properly. After a few switches back and forth between computers.. one of the Macbook's will start to fail to recognize the devices. It happens on both computers, not necessarily at the same time or in a way I can find a pattern. I can still use the keyboard and mouse just fine, but the colors do not assign and CKB-Next fails to recognize the Corsair devices. I end up just dealing with it and using the rainbow scrolling colors for hours. 

The only fix is restarting the respective computer. I've tried killing the daemon, restarting everything related, nothing fixes it. The only fix is to restart the computer. I've tried disconnecting the switcher, and connecting the devices straight to the computer. The only progress I've made on this issue, was killing ckb-next-daemon, and running it myself to see the output (on the computer that is failing to see the devices). 

The line I quoted in the title (in bold below) is the only useful piece of information I've found. The debug log I've attached was taken DURING the issue of not being able to see the devices in CKB-Next.

Thank you in advance,
-Mike

[ckb-next-report-1579636302.gz](https://github.com/ckb-next/ckb-next/files/4093462/ckb-next-report-1579636302.gz)

> ckb-next: Corsair RGB driver 0.4.2
[I] Root controller ready at /var/run/ckb0
[I] Connecting Corsair Gaming MM800 RGB POLARIS at /var/run/ckb1
[I] Connecting Corsair Gaming SCIMITAR PRO RGB Mouse at /var/run/ckb2
[I] Connecting Corsair K70 RGB Gaming Keyboard  at /var/run/ckb3
[I] ckb1: Adding HID handle with id 1
[I] ckb1: Adding HID handle with id 0
[I] ckb1 USB handles: 0: 0x0, 1: 0x0, 2:0x0, 3: 0x0
[I] ckb1 HID handles: 0: 0x7fcac4602b18, 1: 0x7fcac4601df8, 2:0x0, 3: 0x0
[I] Waiting for VirtualHIDKeyboard...
[I] VirtualHIDKeyboard ready
[I] Starting input thread for /var/run/ckb1
[I] Received identification packet: 0e 01 00 00 00 01 00 00 02 01 03 00 1c 1b 3b 1b 08 00 00 00 c2 ff 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[I] Setup finished for /var/run/ckb1
[I] ckb2: Adding HID handle with id 1
[I] ckb2: Adding HID handle with id 0
[I] ckb2 USB handles: 0: 0x0, 1: 0x0, 2:0x0, 3: 0x0
[I] ckb2 HID handles: 0: 0x7fcac4700208, 1: 0x7fcac4602d78, 2:0x0, 3: 0x0
[I] Waiting for VirtualHIDKeyboard...
[I] VirtualHIDKeyboard ready
[I] Starting input thread for /var/run/ckb2
[I] Received identification packet: 0e 01 00 00 01 01 00 01 14 03 01 01 1c 1b 3e 1b 01 01 01 30 c1 ff 40 01 46 00 01 01 00 00 00 00 00 00 00 00 01 00 00 01 00 00 02 01 00 01 aa 00 6c dc 02 00 00 00 00 00 00 00 00 00 00 00 00 00
[I] Setup finished for /var/run/ckb2
[I] ckb3: Adding HID handle with id 1
[I] ckb3: Adding HID handle with id 0
[I] ckb3 USB handles: 0: 0x0, 1: 0x0, 2:0x0, 3: 0x0
[I] ckb3 HID handles: 0: 0x7fcac440cf58, 1: 0x7fcac440c4e8, 2:0x0, 3: 0x0
[I] Waiting for VirtualHIDKeyboard...
[I] VirtualHIDKeyboard ready
[I] Starting input thread for /var/run/ckb3
[I] Received identification packet: 0e 01 00 00 01 01 00 01 08 03 11 00 1c 1b 13 1b 01 01 01 06 c0 ff 40 00 03 00 00 00 02 44 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77 77
[I] Setup finished for /var/run/ckb3
[I] Disconnecting /var/run/ckb2
[I] Terminating VirtualHIDKeyboard
[I] Terminating VirtualHIDPointing
[I] Removed device path /var/run/ckb2
[I] Stopping input thread for /var/run/ckb2
[I] Removed device path /var/run/ckb2
[I] Removed device path /var/run/ckb2
[I] Removed device path /var/run/ckb2
[I] Disconnecting /var/run/ckb1
[I] Terminating VirtualHIDKeyboard
[I] Terminating VirtualHIDPointing
[I] Removed device path /var/run/ckb1
[I] Stopping input thread for /var/run/ckb1
[I] Removed device path /var/run/ckb1
[I] Removed device path /var/run/ckb1
[I] Removed device path /var/run/ckb1
**[W] iterate_devices_usb (usb_mac.c:784): Unable to seize USB handle, continuing anyway...**
[I] Connecting Corsair Gaming MM800 RGB POLARIS at /var/run/ckb1
[I] ckb1: Adding HID handle with id 1
[I] ckb1: Adding HID handle with id 0
[I] ckb1 USB handles: 0: 0x0, 1: 0x0, 2:0x0, 3: 0x0
[I] ckb1 HID handles: 0: 0x7fcac446f028, 1: 0x7fcac4700238, 2:0x0, 3: 0x0
[I] Waiting for VirtualHIDKeyboard...
[I] VirtualHIDKeyboard ready
[I] Starting input thread for /var/run/ckb1
[I] Received identification packet: 0e 01 00 00 00 01 00 00 02 01 03 00 1c 1b 3b 1b 08 00 00 00 c2 ff 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[I] Setup finished for /var/run/ckb1
**[W] iterate_devices_usb (usb_mac.c:784): Unable to seize USB handle, continuing anyway...**
[I] Connecting Corsair Gaming SCIMITAR PRO RGB Mouse at /var/run/ckb2
[I] ckb2: Adding HID handle with id 1
[I] ckb2: Adding HID handle with id 0
[I] ckb2 USB handles: 0: 0x0, 1: 0x0, 2:0x0, 3: 0x0
[I] ckb2 HID handles: 0: 0x7fcac4731268, 1: 0x7fcac47000e8, 2:0x0, 3: 0x0
[I] Waiting for VirtualHIDKeyboard...
[I] VirtualHIDKeyboard ready
[I] Starting input thread for /var/run/ckb2
[E] process_input_urb (keymap.c:362): Unknown mouse data received in input thread 10 from endpoint 00
[E] process_input_urb (keymap.c:362): Unknown mouse data received in input thread 02 from endpoint 00
[I] Received identification packet: 0e 01 00 00 01 01 00 01 14 03 01 01 1c 1b 3e 1b 01 01 01 30 c1 ff 40 01 46 00 01 01 00 00 00 00 00 00 00 00 01 00 00 01 00 00 00 01 00 01 aa 00 6c dc 02 00 00 00 00 00 00 00 00 00 00 00 00 00
[I] Setup finished for /var/run/ckb2

**Comment by tatokis** [comment]
Unfortunately I don't really know what could be causing this. It's an inconvenience, but you should be able to just restart the daemon to fix it. There's a script bundled with the .app that you can run to restart it.

Looking at the logs, USB handles aren't being used at all, so it shouldn't be affecting it.
Perhaps it breaks because all the devices are switched at once?
