### ISSUE TITLE
K68 RGB Rapidfire

### ISSUE THREAD

**Issue by JKingweb** [ckb-next/ckb-next#537]
# Before you proceed

- Check if your device is listed in the [wiki](https://github.com/ckb-next/ckb-next/wiki/Supported-Hardware).
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
- If possible, try the latest code by building the software manually.
- File unrelated issues separately.

**Click the `Generate Report` button in the `Settings` tab of the ckb-next user interface and attach the generated report to this issue.**

---

I'm unclear whether it is a distinct device from the K68 RGB; the wiki would seem to suggest other Rapidfire boards are. It seems to work fine other than saving to hardware (which, again, the wiki suggests should be otherwise possible with the K68 RGB). It's more of a nice-to-have, though, since it works in software fine.

[ckb-next-report-1579649090.gz](https://github.com/ckb-next/ckb-next/files/4094371/ckb-next-report-1579649090.gz)

**Comment by ZirconiumX** [comment]
I do apologise for the delay in looking at this. In this particular case, the K68 RGB Rapidfire is identical to the K68 RGB, but for some reason the keyboard times out while ckb-next is trying to initialise it. You'd have to join us in IRC for us to try to fix that, or a file a new issue. As-is, though, I'll edit the supported devices list to mention the Rapidfire variant and close this.
