### ISSUE TITLE
Randomized macro delays

### ISSUE THREAD

**Issue by Sur3** [ckb-next/ckb-next#538]
Some games do cheat detection by timing user actions, it would be nice if you could define an interval instead of fixed delay between macro keys, so actions are done with a randomized delay based on the given interval.

**Comment by tatokis** [comment]
This is now supported, although not properly exposed in the UI yet.
In the delay field you can set min_max delays in microseconds.
For example, 100000_500000 for a random delay between 0.1 and 0.5 seconds
