### ISSUE TITLE
Failed to build.  Unsure what is useful to include here.

### ISSUE THREAD

**Issue by hydranmenace** [ckb-next/ckb-next#555]
I searched as best I knew how for my issue.  I do ./quickinstall and it gets roughly halfway done and then I see errors.  Not sure what logs to attach, so I guess I'll just paste in the output from ./quickinstall.  Any help would be appreciated.  

hydran@hydramax ~/Downloads/ckb-next $ ./quickinstall
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.24.1") 
-- ckb-next version: 0.4.2-50-gafd0e19 (Non-release)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/libc.so
-- Checking for module 'libudev'
--   Found libudev, version 242
-- Found UDEV: /usr/lib/libudev.so  
-- Searching for running ckb and/or ckb-next GUI
-- NOTE:
    Privileged access is required for operations upon the daemon at
    configure time as it is owned by root. If this is unacceptable,
    disable SAFE_INSTALL and prepare the filesystem manually.
-- systemd detected
-- Generating and importing ckb-next-daemon.service (systemd)
Password: 
inactive
Failed to get unit file state for ckb-daemon.service: No such file or directory
inactive
Failed to get unit file state for ckb-next-daemon.service: No such file or directory
-- Found QuaZip: /usr/lib/libquazip5.so  
-- Found PulseAudioSimple: /usr/lib/libpulse-simple.so  
-- Found PulseAudio: /usr/lib/libpulse.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'xcb'
--   Found xcb, version 1.13.1
-- Checking for module 'xcb-ewmh'
--   Found xcb-ewmh, version 0.4.1
-- Checking for module 'xcb-screensaver'
--   Found xcb-screensaver, version 1.13.1
-- Generating binary.qrc
-- Importing ckb-next-key.gpg
-- Generating image.qrc
-- Importing ckb-next-monochrome.png
-- Importing ckb-next.png
-- Importing icon_blank.png
-- Importing icon_mode.png
-- Importing icon_mode1.png
-- Importing icon_mode1_hardware.png
-- Importing icon_mode2.png
-- Importing icon_mode2_hardware.png
-- Importing icon_mode3.png
-- Importing icon_mode3_hardware.png
-- Importing icon_plus.png
-- Importing icon_profile.png
-- Importing icon_profile_hardware.png
-- Importing overlay_glaive.png
-- Importing overlay_harpoon.png
-- Importing overlay_ironclaw.png
-- Importing overlay_katar.png
-- Importing overlay_m65.png
-- Importing overlay_m95.png
-- Importing overlay_polaris.png
-- Importing overlay_sabre.png
-- Importing overlay_scimitar.png
-- Generating translation.qrc
-- Importing el.qm
-- Importing en_GB.qm
-- Generating and importing ckb-next.desktop
-- Generating and importing ckb-next.autostart.desktop
-- Importing demo profiles and generating text.qrc
-- Importing demoprofile.conf
-- Importing demoprofile_k55.ini
-- Importing demoprofile_m95.ini
-- Importing demoprofile_polaris.ini
-- Importing demoprofile_st100.ini
-- *** Have SIZEOF void * = 8, so 64-bit
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hydran/Downloads/ckb-next/build
Scanning dependencies of target gradient
Scanning dependencies of target pinwheel
Scanning dependencies of target ckb-next-daemon
Scanning dependencies of target KissFFT
Scanning dependencies of target pipe
Scanning dependencies of target invaders
Scanning dependencies of target rain
Scanning dependencies of target random
[  1%] Building C object src/animations/CMakeFiles/rain.dir/rain/main.c.o
[  2%] Building C object src/libs/kissfft/CMakeFiles/KissFFT.dir/kiss_fft.c.o
[  2%] Building C object src/animations/CMakeFiles/gradient.dir/gradient/main.c.o
[  4%] Building C object src/animations/CMakeFiles/pinwheel.dir/pinwheel/main.c.o
[  5%] Building C object src/animations/CMakeFiles/invaders.dir/invaders/main.c.o
[  5%] Building C object src/animations/CMakeFiles/pipe.dir/pipe/main.c.o
[  6%] Building C object src/animations/CMakeFiles/random.dir/random/main.c.o
[  7%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/command.c.o
[  8%] Linking C executable ../../bin/pipe
[  9%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device.c.o
[ 10%] Linking C executable ../../bin/pinwheel
[ 11%] Linking C executable ../../bin/random
[ 11%] Built target pipe
[ 13%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device_keyboard.c.o
[ 13%] Linking C executable ../../bin/gradient
[ 14%] Linking C executable ../../bin/invaders
[ 14%] Built target pinwheel
[ 15%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device_mouse.c.o
[ 15%] Built target random
Scanning dependencies of target heat
[ 15%] Linking C executable ../../bin/rain
Scanning dependencies of target ripple
[ 15%] Built target gradient
[ 16%] Building C object src/animations/CMakeFiles/heat.dir/heat/main.c.o
[ 17%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/device_vtable.c.o
[ 18%] Building C object src/animations/CMakeFiles/ripple.dir/ripple/main.c.o
[ 18%] Built target invaders
[ 19%] Building C object src/libs/kissfft/CMakeFiles/KissFFT.dir/kiss_fftr.c.o
[ 19%] Built target rain
Scanning dependencies of target wave
[ 20%] Building C object src/animations/CMakeFiles/wave.dir/wave/main.c.o
[ 21%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/devnode.c.o
[ 22%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/dpi.c.o
[ 23%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/dpi_legacy.c.o
[ 23%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/firmware.c.o
[ 24%] Linking C static library libKissFFT.a
Scanning dependencies of target life
[ 24%] Built target KissFFT
[ 24%] Building C object src/animations/CMakeFiles/life.dir/life/main.c.o
Scanning dependencies of target snake
[ 25%] Building C object src/animations/CMakeFiles/snake.dir/snake/main.c.o
[ 26%] Linking C executable ../../bin/heat
Scanning dependencies of target ckb-next-lrelease
Scanning dependencies of target mviz
[ 26%] Generating el.qm
[ 27%] Building C object src/animations/mviz/CMakeFiles/mviz.dir/main.c.o
Updating '/home/hydran/Downloads/ckb-next/build/src/gui/el.qm'...
    Generated 437 translation(s) (437 finished and 0 unfinished)
[ 27%] Built target heat
[ 29%] Linking C executable ../../bin/ripple
[ 29%] Generating en_GB.qm
[ 30%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/input.c.o
Updating '/home/hydran/Downloads/ckb-next/build/src/gui/en_GB.qm'...
    Generated 9 translation(s) (8 finished and 1 unfinished)
    Ignored 428 untranslated source text(s)
[ 30%] Built target ckb-next-lrelease
[ 31%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/keymap.c.o
Scanning dependencies of target ckb-next_autogen
[ 32%] Automatic MOC and UIC for target ckb-next
[ 33%] Linking C executable ../../bin/wave
[ 33%] Built target ripple
[ 34%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/keymap_patch.c.o
[ 34%] Built target wave
[ 35%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led.c.o
[ 36%] Linking C executable ../../bin/snake
[ 37%] Linking C executable ../../bin/life
[ 38%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led_keyboard.c.o
[ 39%] Linking C executable ../../../bin/mviz
[ 39%] Built target life
[ 39%] Built target snake
[ 40%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led_mouse.c.o
[ 41%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/led_mousepad.c.o
[ 42%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/main.c.o
[ 42%] Built target mviz
[ 42%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/notify.c.o
[ 43%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/profile.c.o
[ 44%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/profile_keyboard.c.o
[ 45%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/usb.c.o
[ 46%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/profile_mouse.c.o
[ 47%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/usb_linux.c.o
gmake[2]: *** No rule to make target '/usr/lib/libudev.so', needed by 'bin/ckb-next-daemon'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
[ 48%] Building C object src/daemon/CMakeFiles/ckb-next-daemon.dir/input_linux.c.o
gmake[1]: *** [CMakeFiles/Makefile2:225: src/daemon/CMakeFiles/ckb-next-daemon.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 48%] Built target ckb-next_autogen
gmake: *** [Makefile:152: all] Error 2
An error occurred,
press enter to exit.

**Comment by tatokis** [comment]
What distro is this?

` gmake[2]: *** No rule to make target '/usr/lib/libudev.so', needed by 'bin/ckb-next-daemon'. Stop.`
Does `/usr/lib/libudev.so` exist?

**Comment by ZirconiumX** [comment]
You need to install libudev; it's normally a package like libudev-dev on
Debian derivatives.

>

**Comment by hydranmenace** [comment]
Sabayon Linux. Gentoo based. I thought I had libudev because toward the beginning of the output it says 
-- Found Iconv: /usr/lib/libc.so
-- Checking for module 'libudev'
-- Found libudev, version 242
-- Found UDEV: /usr/lib/libudev.so
-- Searching for running ckb and/or ckb-next GUI

and I have 
hydran@hydramax /usr/lib $ ls *udev*
libgudev-1.0.so  libgudev-1.0.so.0  libgudev-1.0.so.0.2.0  libudev.so  libudev.so.0

**Comment by hydranmenace** [comment]
I made it work?  Sorry I am really new to linux.  Sort of.  I try it again every several years and things seem to change a lot.  It would seem that /usr/lib/libudev.so is a symlink that wasn't actually pointing to anything?  After some newbi-googling i did ln -s libudev.so.1.6.14 libudev.so which may or may not have been a horrible mistake.... but it did build and install.  Seems to be working fine.  Thanks to those who replied.  If my "fix" is a terrible idea, please let me know.

**Comment by tatokis** [comment]
Yeah, that sounds about right. Somehow your system had a broken libudev.
In theory, reinstalling it should fix the symlinks. I don't know, I've never used your distro.

Either way, good to hear you got it working.
