### ISSUE TITLE
WASD keys are always white

### ISSUE THREAD

**Issue by descendingnerdliness** [ckb-next/ckb-next#557]
K70RGB
While this seems to be a gaming feature, I find it disturbing that the WASD keys are always white.
The color seems to be changeable, but they never follow the rest of the keys in color changes.  
It would be vastly preferable, to me at least, if the  WASD keys follow the animations or are the same as the rest of the keys.

**Comment by ashirviskas** [comment]
@descendingnerdliness it's just the default profile. Just go there, delete it and create a one yourself to be whatever you want it to be.

**Comment by descendingnerdliness** [comment]
Thanks for the reply and this driver. 
I found that animation and all of the keys could be selected and then the 'Set keys' button pressed to have them all behave the same.
Thanks.
