### ISSUE TITLE
Suggestion: Pipe reset command

### ISSUE THREAD

**Issue by elig0n** [ckb-next/ckb-next#565]
## What is the program's current behaviour?
After sending some rgb commands to the pipe file the only way to restore initial color settings is by deleting the Pipe animation and readding it.

## What would you like it to do instead?
Maybe have some "reset" command or similar that will remove all pipe  settings that were passed since beginning

**Comment by ZirconiumX** [comment]
Pipe colours include alpha; if you don't want your animation to do
anything, set the alpha channel to zero and it becomes transparent.

**Comment by ZirconiumX** [comment]
You're... welcome?

**Comment by elig0n** [comment]
That did it, of course thanks !
