### ISSUE TITLE
Repositories broken for 20.04

### ISSUE THREAD

**Issue by PlazmaKG** [ckb-next/ckb-next#570]
I can't seem to install ckb-next via the repo on 20.04 LTS. Not sure if the repositories will be updated or not, but I really need this xD

: The repository 'http://ppa.launchpad.net/tatokis/ckb-next/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/tatokis/ckb-next-git/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by tatokis** [comment]
I scheduled builds and they should be released by now
