### ISSUE TITLE
Support for Corsair Virtuoso ?

### ISSUE THREAD

**Issue by Joseon** [ckb-next/ckb-next#579]
hey guys just wondering if corsair virtuoso headset will be supported? i saw that there's a WIP headset support but is that only for the void pro? is there anything  I could do to help?

**Comment by Googlelt** [comment]
This would be ideal. currently only getting audio through one side of the headset. and the volume is very low.

**Comment by cap-hector** [comment]
some news?

**Comment by Ravenslofty** [comment]
It's unlikely to be supported any time soon; the Void Pro gave us enough headaches (which is why it's been sat in a branch for a while).

**Comment by rvl** [comment]
Hi @Ravenslofty I'm possibly interested in trying to add (partial) support for the corsair virtuoso headset.
Would you be able point me to any work in progress and/or relevant information for headsets support?
What were the headaches for the Void Pro? Is the protocol quite different to that of keyboards for example?
Cheers.

**Comment by gravityfargo** [comment]
closing in favor of #785
