### ISSUE TITLE
Support for M55 Pro gaming mouse

### ISSUE THREAD

**Issue by djlav** [ckb-next/ckb-next#588]
I have a M55 Pro gaming mouse. My K55 keyboard works well within ubuntu 18.04 (specifically ubuntu gamepack), but I am unable to get the mouse to work with ckb-next. 

Will there be future support for this device? 

I have attached my report below of my configuration. 
[ckb-next-report-1589740451.gz](https://github.com/ckb-next/ckb-next/files/4640773/ckb-next-report-1589740451.gz)

**Comment by nortuzar** [comment]
I tried with pop_os 20.04 and nothing. It would be awesome to be able to get rid of windows with this

**Comment by revane** [comment]
See #440 .
