### ISSUE TITLE
Plans to add support for in-case lighting?

### ISSUE THREAD

**Issue by headassbtw** [ckb-next/ckb-next#602]
[ckb-next-report-1590850450.gz](https://github.com/ckb-next/ckb-next/files/4705823/ckb-next-report-1590850450.gz)
file has my kb, mouse, headset (dongle),AIO, and lighting node pro connected
Stumbled across this when on a quest to semi switch to linux(oculus and R6S holding me back), and was wondering if there were plans to support more than just keyboards and mice? In particular the void elite wireless, H115i RGB platinum, and Lighting node pro (I've seen that in another issue tho) I'm open to help test, it would be very nice if that was added.

**Comment by gravityfargo** [comment]
closing in favor of #639
