### ISSUE TITLE
K70 non-RGB does not have an update firmware option

### ISSUE THREAD

**Issue by Odzinic** [ckb-next/ckb-next#605]
## General information
Thanks for this great tool. I've been experiencing some typing issues with my K70R keyboard and was hoping to update the firmware with this tool. I've been trying to find the update option that I've seen in screenshots under the Device section but have been unable to find it.

### Source
How and where did you get this program, e.g.:
  PPA

## Logs & crash reports
[ckb-next-report-1591829985.txt](https://github.com/ckb-next/ckb-next/files/4761662/ckb-next-report-1591829985.txt)
![Screenshot_20200610_190131](https://user-images.githubusercontent.com/1714080/84327213-cdfd1180-ab4c-11ea-912b-1dd2899f9dd2.png)

## What is the program's current behaviour?
When I go into the Device tab there is not "Update" button for firmware

## What is the expected behaviour of the program?
There should be an Update button in the Device page

## Any other notes & comments?
I am unsure whether the keyboard is supported for firmware updates in ckb-next. If it's not, please close this issue.

**Comment by tatokis** [comment]
We do not support firmware updates on your device.
No one reverse engineered the update commands and implemented them.

Despite being called a K70 it has nothing to do with the monochrome and RGB variants of the other K70s.
