### ISSUE TITLE
Option to start minimized in system tray

### ISSUE THREAD

**Issue by mightymouth** [ckb-next/ckb-next#606]
Rather than have the application open a window have the option to open minimized in the system tray.

**Comment by ZirconiumX** [comment]
That would be `ckb-next -b`, right?

**Comment by mightymouth** [comment]
> That would be `ckb-next -b`, right?

Yes, but have a tick box option in the GUI.

**Comment by jannis3005** [comment]
> That would be `ckb-next -b`, right?

But this does already work, i think. It's just the GUI Switch that's missing

![image](https://user-images.githubusercontent.com/38779449/88522860-4cc3e600-cff7-11ea-940b-eb389004e919.png)

**Comment by mightymouth** [comment]
The option is there but it does nothing. it still always opens full screen at login.

**Comment by jannis3005** [comment]
> The option is there but it does nothing. it still always opens full screen at login.

What Distro + DE are you using? For me (Arch + KDE) it works perfectly and just starts in background

**Comment by mightymouth** [comment]
Kubuntu 20.04. I have tried on KDE Neon also which was the same which makes sense as it is essentially the same.

**Comment by tatokis** [comment]
KDE is ignoring the autostart entry and trying to restore the session. In doing so, it passes its own arguments that ckb-next ignores due to the way it's set up. There's a fix for this in master.
https://github.com/ckb-next/ckb-next/issues/510

**Comment by mightymouth** [comment]
I have installed master and it is indeed working as it should. thank you.
