### ISSUE TITLE
Where are profiles stored and how do I copy them?

### ISSUE THREAD

**Issue by CrushedPixl** [ckb-next/ckb-next#613]
I didn't export my profiles before reinstalling my OS. I have a full system backup, but I don't know which file to copy. I've tried copying `~/.config/ckb-next/ckb-next.conf` and restarting with `ckb-next -c && rc-service ckb-next-daemon restart && ckb-next`, but nothing seems to have changed.

Additionally, I tried to trace which files were accessed through `inotifywait -m -r -e OPEN / | grep ckb` without success. The only accessed files other than the config mentioned above were in `/dev/input/ckb0/` and  `/usr/lib/ckb-next-animations/` when switching profiles.

**Comment by tatokis** [comment]
It is `~/.config/ckb-next/`.
The problem is that you are replacing it with ckb-next (the GUI) running.

Close it, then replace it, then restart it.

**Comment by CrushedPixl** [comment]
This worked. Thanks!
