### ISSUE TITLE
Add support for K95 Platinum XT

### ISSUE THREAD

**Issue by teknofile** [ckb-next/ckb-next#614]
### Source
How and where did you get this program, e.g.:
Tried both the PPA for Ubuntu and also building from source.

## Logs & crash reports

Attach:
 * The generated report from the section above
 * Any additional crash reports you've managed to gather

## What is the program's current behaviour?
New K95 Platinum Gaming Keyboard. "No devices connected" when runnign ckb-next.

## What is the expected behaviour of the program?
It detects and lets me fidle with the keyboard.

## Any other notes & comments?
The keyboard still works as a HID device. 

[ckb-next-report-1593285313.gz](https://github.com/ckb-next/ckb-next/files/4841113/ckb-next-report-1593285313.gz)

![Screenshot-20200627131945-1002x1074](https://user-images.githubusercontent.com/7469656/85930360-ef623b00-b878-11ea-9153-59374f3dd9c2.png)

**Comment by tatokis** [comment]
You have a K95 Platinum XT which is not supported

**Comment by teknofile** [comment]
Ah, thanks. I didn't realize that there was a difference between the "Platinum" and "Platinum XT". Started looking at the code briefly this weekend and adding a new device ID didn't look too complicated. If it's just a matter of that, I could probably get that done and issue a PR.

**Comment by tatokis** [comment]
The XT uses the new protocol that we have not implemented.
It is not that simple sadly

**Comment by pinheadmz** [comment]
I also have a `Corsair Gaming K95 RGB PLATINUM Keyboard` on a Lenovo Y740 laptop. Tracking this issue! Might look into contributing if I can

**Comment by teknofile** [comment]
> The XT uses the new protocol that we have not implemented. There's some very slow work in progress.
> It is not that simple sadly

Well, that's stinky. 

Has any documentation already began about the new protocol?

**Comment by Ravenslofty** [comment]
We don't know for sure, but we expect significant overlaps with the
Ironclaw Wireless, as both identify as the same protocol version.

**Comment by ghost1347** [comment]
Damn I got an xt not knowing that made a difference

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/614
