### ISSUE TITLE
K55 RGB not allowing Calculator app to be bound to G Keys. 2nd time posting bc no answers.

### ISSUE THREAD

**Issue by NathanJava** [ckb-next/ckb-next#625]
Hello,

I've had my K55 RGB and Harpoon RGB on macOS for well over a year now and am satisfied except for a small issue with binding programs, especially to G keys.

I've researched this issue extensively and have not found a solution. However, my other G keys seem to be working, but for some reason CKB wont allow Calculator.app to be bound to a G key. I'm a Doctoral student in Finance and as such need a quick way to do calculations with my number pad, without leaving my keyboard. 
My software is up to date and until this has worked flawlessly 

This issue seems to be only affecting binding keys to programs. I am able to bind keys to Macros, Special Modifiers, Mouse Actions, and regular Keys.

After my first restart just a day after buying the keyboard I found I was unable to bind any program to G-keys. I'm still on the mode and profile I created where binds originally worked, but have tried creating new profiles, modes, resetting the key, unbinding-rebinding, but nothing works.

I've also uninstalled and re-installed the software to no avail. I'm absolutely sure I'm using the right command. Until now I've given up on this issue but I have a new job and the new binds would be immensely helpful for my productivity.
.
.
.
.

Generated Report
ckb-next-report-1589662049.gz

Source
How and where did you get this program, e.g.:

Program downloaded from this Github Repository using pre-built .dmg
Behavior
What is the program's current behaviour?

K55 not accepting keybinds to launch programs, though other binds are working. Otherwise ckb runs perfectly.
Any other notes & comments?

Is there an option to possibly reset the hardware while connected to CKB? If so would this be a viable option to fix the problem?
.
.
Thank you for your time and hard work,
Nate

**Comment by Ravenslofty** [comment]
Are you trying to select `Calculator.app` specifically?

Mac OS has a sleight of hand: `.app`s are actually folders. You can't execute a folder, but instead would have to select the executable inside the folder. Alternatively I think you could set it to run the external command `open path/to/Calculator.app`.
