### ISSUE TITLE
Question: next version

### ISSUE THREAD

**Issue by Blu3wolf** [ckb-next/ckb-next#632]
The latest tag is 0.4.2, from October last year. As new features have been implemented since then, perhaps a new version could be released with the current version of master? It seems a shame to have the version on the AUR be nearly 12 months out of date compared to the master branch here. 
I had a look for a set of milestones but only found 0.3.0. Have I missed something obvious?

**Comment by tatokis** [comment]
Most of the work was done within the past few weeks. I'm just waiting to see if anything important comes up, and if not, I'll cut a release soon.
There hadn't been anything new that would warrant a new release up until very recently.

>It seems a shame to have the version on the AUR be nearly 12 months out of date compared to the master branch here.

There's always
https://aur.archlinux.org/packages/ckb-next-git/
