### ISSUE TITLE
Gnome tray icon bug

### ISSUE THREAD

**Issue by SkavenNoises** [ckb-next/ckb-next#633]
Report:
[ckb-next-report-1597567094.gz](https://github.com/ckb-next/ckb-next/files/5080287/ckb-next-report-1597567094.gz)

### Source
- Package from AUR (Manjaro)

## What is the program's current behaviour?
Currently on launch of the app, be it auto-start or manually, the system tray icon is a garbled mess of pixels (See photo).
![Screenshot from 2020-08-16 10-35-19](https://user-images.githubusercontent.com/49200606/90330438-f79f4280-dfac-11ea-89fa-d86620442f0f.png)

On-top of this, the toggles in settings>behaviour currently do not function as intended.
- Hide tray icon - does not persist through re-log. Cycling toggle will fix the icon, but only during current log-in
- Monochrome tray icon - does not produce a monochrome tray icon. toggling will restore the rainbow coloured icon

- Selecting either of these settings after login+launch will toggle the pixilated mess into the standard rainbow coloured icon

## What is the expected behaviour of the program?
Toggle behaviour to correct and to persist through log-in cycles

**Comment by tatokis** [comment]
Can you quit ckb-next and then run it from a terminal and send the output? Ideally when the tray icon is broken as well.

**Comment by tatokis** [comment]
Also if possible, provide logs from your desktop environment as well.

**Comment by tatokis** [comment]
I was able to reproduce it in a VM, and I have pushed a workaround.
Please try again with the latest version.

**Comment by SkavenNoises** [comment]
Can confirm, behaviour works as intended now. Thank you for such a swift fix!
