### ISSUE TITLE
FIRMWARE archive?

### ISSUE THREAD

**Issue by phixion** [ckb-next/ckb-next#636]
## What is the program's current behaviour?
-
## What would you like it to do instead?
Is there a firware archive somewehre? Corsair is very closed about this matter, only the newest ones are provided both on the site and the forums. I am looking for a specific version for a sabre RGB (newest FW makes white LED look blueish). It might also be a nice addition to your software.

**Comment by tatokis** [comment]
There is no public archive, no. We can help you if you join our IRC room. It's linked in the readme.
