### ISSUE TITLE
Building ckb-next from mrdev024 fails with error

### ISSUE THREAD

**Issue by thespyboss** [ckb-next/ckb-next#637]
### Source
How and where did you get this program, e.g.:
Built manually from ./quickinstall
Package cloned from https://github.com/mrdev023/ckb-next.git
Referenced from #453 

## What is the program's current behaviour?
Fails at 49% with error
## What is the expected behaviour of the program?
I have all the dependancies installed and this had successfully installed on another computer with Manjaro Budgie
## Any other notes & comments?
Look at image inserted. that is the error i am getting
![Screenshot from 2020-09-16 18-38-19](https://user-images.githubusercontent.com/42257053/93544636-90b6d580-f92c-11ea-94f0-8137fafc3dc3.png)
![Screenshot from 2020-09-17 17-27-47](https://user-images.githubusercontent.com/42257053/93544671-a4fad280-f92c-11ea-8b40-256e0b77a9f1.png)

**Comment by OrsanZ** [comment]
I've ran into this issue too. You should be able to fix it by rebasing whatever branch your want to compile onto ckb-next/master.

**Comment by thespyboss** [comment]
@OrsanZ How do i do that? Im not the best with git and using git. Can u give like a basic description on how to?

**Comment by thespyboss** [comment]
Also after doing some research, This is being installed from another repo. This isnt from a branch in ckb-next. Its from mrdev024's repo and i can't rebase the ckb-next:master into mrdev024:master.

**Comment by tatokis** [comment]
Until I can get all the branches rebased, you can apply this patch on top.
https://github.com/ckb-next/ckb-next/commit/a9f41cd8b8f5b04c0c66c6d94f96a9725943831e.patch
