### ISSUE TITLE
Quazip shared library file changed name after 1.0, ckb-next doesn't start anymore

### ISSUE THREAD

**Issue by selplacei** [ckb-next/ckb-next#648]
The application does not start, giving the following error in the terminal:

`ckb-next: error while loading shared libraries: libquazip5.so.1: cannot open shared object file: No such file or directory`

The error started appearing after upgrading `quazip` from 0.9.1 to 1.0 earlier today (Oct 9) and restarting the PC. ckb-next starts normally and works fine if a new symlink from `libquazip1-qt5.so.1.0` to `libquazip5.so.1` is created in `/usr/lib`.

This happens on Arch Linux, using the `ckb-next` package from the AUR. `quazip` is from the official `extra` repository.

**Comment by Kyriella** [comment]
Same issue here with the same circumstances (Arch Linux, etc.) and the posted solution worked too. Thanks for the tip!

**Comment by wylel** [comment]
Same here. However, the solution posted works for making it start, it does not detect my device anymore.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/646

**Comment by Rysher** [comment]
I can confirm this issue, exact same circumstance (arch linux, ckb installed from AUR, problem started after upgrading packages), and I can also confirm the solution that @selplacei offered.
However, i am not clear on why this was marked as duplicate, and if so, why wasn't the duplicate issue linked?

Regardless, if anyone else encounters this issue, here is a layman's guide to the solution
``
cd /usr/lib
sudo ln -sf libquazip1-qt5.so.1.0 libquazip5.so.1
``

ckb should be successfully launched now

**Comment by AaronBottegal** [comment]
It was commented directly above. It IS linked.

**Comment by Rysher** [comment]
@AaronBottegal 
right! thank you! I feel stupid now for failing to notice it. my previous comment will be edited
