### ISSUE TITLE
Add mouse Harpoon RGB WIRELESS

### ISSUE THREAD

**Issue by Dylan3250** [ckb-next/ckb-next#655]
Hello,

Excuse me for disturbing you, I would like to congratulate you on this project already ! It works really well and it saves lives !

Then, my mouse remains on h24 RGB, would it be possible to add the HARPOON RGB WIRELESS gaming mouse?

Thank you in advance,
You are the best !

**Comment by Ravenslofty** [comment]
Hi, we already have #346 for this.
