### ISSUE TITLE
Request for support for mice M55 RGB PRO Ambidextrous

### ISSUE THREAD

**Issue by Dutzsg** [ckb-next/ckb-next#657]
I was wondering if there is a chance to add support for this model, I have checked the support list and apparently it isn't there, thanks!

![image](https://user-images.githubusercontent.com/66588754/98599816-d42d2080-2299-11eb-8e49-820d5c68d836.png)

**Comment by Ravenslofty** [comment]
We have #440 for this, unless this is somehow a different device.
