### ISSUE TITLE
Not working with Strafe RGM on Arch Linux

### ISSUE THREAD

**Issue by mwknox186** [ckb-next/ckb-next#659]
I've recently switched to linux and I couldn't get my keyboard to work.

REPORT:
ckb-next-dev-detect - Thu Nov 12 10:48:45 EST 2020

Kernel: Linux max-pc 5.9.6-arch1-1 #1 SMP PREEMPT Thu, 05 Nov 2020 21:00:46 +0000 x86_64 GNU/Linux

OS Version:
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

USB Devices:
Couldn't open device, some information will be missing

Bus 002 Device 008: ID 1b1c:1b20 Corsair STRAFE RGB Gaming Keyboard
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1b1c Corsair
  idProduct          0x1b20 STRAFE RGB Gaming Keyboard
  bcdDevice            2.05
  iManufacturer           1 
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      67
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     112
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      25
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

Dmesg on current boot:
Nov 12 10:06:37.951445 max-pc kernel: usb 2-5: New USB device found, idVendor=1b1c, idProduct=1b20, bcdDevice= 2.05
Nov 12 10:06:37.951814 max-pc kernel: usb 2-5: Product: Corsair STRAFE RGB Gaming Keyboard
Nov 12 10:06:37.951910 max-pc kernel: usb 2-5: Manufacturer: Corsair
Nov 12 10:06:40.791425 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:1B1C:1B20.0001/input/input20
Nov 12 10:06:40.848103 max-pc kernel: hid-generic 0003:1B1C:1B20.0001: input,hidraw0: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input0
Nov 12 10:06:40.848312 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input21
Nov 12 10:06:40.908117 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input22
Nov 12 10:06:40.908189 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input23
Nov 12 10:06:40.908205 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input24
Nov 12 10:06:40.908222 max-pc kernel: hid-generic 0003:1B1C:1B20.0002: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input1
Nov 12 10:45:03.494570 max-pc kernel: audit: type=1130 audit(1605195903.488:137): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=ckb-next-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 12 10:45:04.511208 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:1B1C:1B20.0005/input/input32
Nov 12 10:45:04.567874 max-pc kernel: hid-generic 0003:1B1C:1B20.0005: input,hidraw0: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input0
Nov 12 10:45:05.187862 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0006/input/input33
Nov 12 10:45:05.244534 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0006/input/input34
Nov 12 10:45:05.244634 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0006/input/input35
Nov 12 10:45:05.244676 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0006/input/input36
Nov 12 10:45:05.244705 max-pc kernel: hid-generic 0003:1B1C:1B20.0006: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input1
Nov 12 10:48:21.634565 max-pc kernel: usb 2-5: New USB device found, idVendor=1b1c, idProduct=1b20, bcdDevice= 2.05
Nov 12 10:48:21.634997 max-pc kernel: usb 2-5: Product: Corsair STRAFE RGB Gaming Keyboard
Nov 12 10:48:21.635148 max-pc kernel: usb 2-5: Manufacturer: Corsair
Nov 12 10:48:22.464540 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:1B1C:1B20.0007/input/input38
Nov 12 10:48:22.521196 max-pc kernel: hid-generic 0003:1B1C:1B20.0007: input,hidraw0: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input0
Nov 12 10:48:23.141194 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0008/input/input39
Nov 12 10:48:23.197870 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0008/input/input40
Nov 12 10:48:23.197994 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0008/input/input41
Nov 12 10:48:23.198023 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0008/input/input42
Nov 12 10:48:23.198050 max-pc kernel: hid-generic 0003:1B1C:1B20.0008: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input1
Nov 12 10:48:24.194554 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:1B1C:1B20.0009/input/input43
Nov 12 10:48:24.251195 max-pc kernel: hid-generic 0003:1B1C:1B20.0009: input,hidraw0: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input0
Nov 12 10:48:24.871250 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.000A/input/input44
Nov 12 10:48:24.928574 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.000A/input/input45
Nov 12 10:48:24.928650 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.000A/input/input46
Nov 12 10:48:24.928693 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.000A/input/input47
Nov 12 10:48:24.928734 max-pc kernel: hid-generic 0003:1B1C:1B20.000A: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input1

Dmesg on last boot:
Nov 07 16:40:07.981603 max-pc kernel: usb 2-5: New USB device found, idVendor=1b1c, idProduct=1b20, bcdDevice= 2.05
Nov 07 16:40:07.981909 max-pc kernel: usb 2-5: Product: Corsair STRAFE RGB Gaming Keyboard
Nov 07 16:40:07.982007 max-pc kernel: usb 2-5: Manufacturer: Corsair
Nov 07 16:40:10.794897 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:1B1C:1B20.0001/input/input20
Nov 07 16:40:10.851561 max-pc kernel: hid-generic 0003:1B1C:1B20.0001: input,hidraw0: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input0
Nov 07 16:40:10.851724 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input21
Nov 07 16:40:10.908229 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input22
Nov 07 16:40:10.908282 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input23
Nov 07 16:40:10.908301 max-pc kernel: input: Corsair Corsair STRAFE RGB Gaming Keyboard as /devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.1/0003:1B1C:1B20.0002/input/input24
Nov 07 16:40:10.908314 max-pc kernel: hid-generic 0003:1B1C:1B20.0002: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [Corsair Corsair STRAFE RGB Gaming Keyboard] on usb-0000:00:14.0-5/input1

Daemon on current boot:
-- Logs begin at Sat 2020-11-07 15:56:19 EST, end at Thu 2020-11-12 10:48:36 EST. --
Nov 12 10:45:03.493376 max-pc systemd[1]: Started Corsair Keyboards and Mice Daemon.
Nov 12 10:45:03.495146 max-pc ckb-next-daemon[92297]: ckb-next: Corsair RGB driver 0.4.2
Nov 12 10:45:03.495350 max-pc ckb-next-daemon[92297]: [I] Root controller ready at /dev/input/ckb0
Nov 12 10:45:03.598851 max-pc ckb-next-daemon[92297]: [I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
Nov 12 10:45:03.889209 max-pc ckb-next-daemon[92304]: modprobe: FATAL: Module uinput not found in directory /lib/modules/5.9.6-arch1-1
Nov 12 10:45:03.889382 max-pc ckb-next-daemon[92297]: [F] os_inputopen (input_linux.c:67): Failed to load uinput module
Nov 12 10:45:03.889382 max-pc ckb-next-daemon[92297]: [I] Disconnecting /dev/input/ckb1
Nov 12 10:45:05.241752 max-pc ckb-next-daemon[92297]: [I] Removed device path /dev/input/ckb1
Nov 12 10:48:23.303499 max-pc ckb-next-daemon[92297]: [I] Connecting Corsair STRAFE RGB Gaming Keyboard at /dev/input/ckb1
Nov 12 10:48:23.572107 max-pc ckb-next-daemon[92641]: modprobe: FATAL: Module uinput not found in directory /lib/modules/5.9.6-arch1-1
Nov 12 10:48:23.572286 max-pc ckb-next-daemon[92297]: [F] os_inputopen (input_linux.c:67): Failed to load uinput module
Nov 12 10:48:23.572286 max-pc ckb-next-daemon[92297]: [I] Disconnecting /dev/input/ckb1
Nov 12 10:48:24.924856 max-pc ckb-next-daemon[92297]: [I] Removed device path /dev/input/ckb1

Daemon on last boot:
-- Logs begin at Sat 2020-11-07 15:56:19 EST, end at Thu 2020-11-12 10:48:36 EST. --
-- No entries --

Dev nodes:
/dev/input/ckb0
/dev/input/ckb0/pid
92297
/dev/input/ckb0/version
0.4.2
/dev/input/ckb0/connected

Environment:
XDG_SESSION_DESKTOP=KDE
QT_BEARER_POLL_TIMEOUT=-1
XDG_CURRENT_DESKTOP=KDE
DISPLAY=:0
QT_AUTO_SCREEN_SCALE_FACTOR=0

Kernel command line:
BOOT_IMAGE=/vmlinuz-linux root=UUID=041304b7-2de8-461f-8aae-65eb0b57bc92 rw

**Comment by Ravenslofty** [comment]
> Nov 12 10:48:23.572107 max-pc ckb-next-daemon[92641]: modprobe: FATAL: Module uinput not found in directory /lib/modules/5.9.6-arch1-1

Did you update your kernel recently? Try rebooting.

**Comment by mwknox186** [comment]
That worked, Thanks!
