### ISSUE TITLE
mviz: vertical mode

### ISSUE THREAD

**Issue by disconsented** [ckb-next/ckb-next#66]
Currently, music visualization is horizontal which leads it to being not very noticeable instead I would like the option to make it [vertical ](https://www.youtube.com/watch?v=yrJLmKHvC9A)

**Comment by kpande** [comment]
how'd you make it vertical there? would love this.

**Comment by disconsented** [comment]
Corsair effects engine

On 18 Feb 2018 3:10 pm, kpande <notifications@github.com> wrote:

how'd you make it vertical there? would love this.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/commit/db1eb4ea442ec4b1d0291a1b8b2abc382ee99423
