### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by likefiftyninjas** [ckb-next/ckb-next#665]
I was able to have ckb-next work on my computer for a little while. Now it does not work at all. I have uninstalled and reinstalled it. The message I get when I attempt to open it from the command line is:
`ckb-next: error while loading shared libraries: libquazip5.so.1: cannot open shared object file: No such file or directory
`
Any help would be greatly appreciated. Thanks.

**Comment by tatokis** [comment]
Rebuild the package. https://github.com/ckb-next/ckb-next/issues/646
