### ISSUE TITLE
Upper edge lightbar (across entire keyboard) is not individually configurable

### ISSUE THREAD

**Issue by egberts** [ckb-next/ckb-next#666]
The lightbar that spans across the top edge of Corsair Gaming K95 RGB Platinum keyboard is not LED-individual configurable to either intensity nor color.

Appears to be more related to inability to dynamically update the lightbar, but it will save the settings via Hardware Save and next time daemon gets reloaded, then the change becomes apparent.   

*  It saves into profile/mode settings
* cannot dynamically update the color
* Can finally affect the desired colors at next daemon restart.

[ckb-next-report-1605990106.gz](https://github.com/ckb-next/ckb-next/files/5578326/ckb-next-report-1605990106.gz)

## General information
I am using the #656 pull (ahead of master). (d7bd30026a80a5b50e42e086e978ea55e8efd4bf)

### Source
How and where did you get this program, e.g.:
  * Checked out d7bd30026a80a5b50e42e086e978ea55e8efd4bf from #520 and #656.
  * Built manually using quickinstall script

## Logs & crash reports

None

## What is the program's current behaviour?

Using the GUI of d7bd30026a80a5b50e42e086e978ea55e8efd4bf, the top-row entire-edge lightbar is not individually controlable.  

* We are able to give it a preprogrammed pattern
* Just not able to individually control each LED on the lightbar.

## What is the expected behaviour of the program?

* Have the ability to selectively change color and/or intensity of each LED of the entire lightbar.

## Any other notes & comments?

* Guidance on how to use tools to test and probe keyboards would be helpful at this point.

**Comment by Ravenslofty** [comment]
You *can* individually change the LEDs on the lightbar (ckb-next's patterns just focus on lights). Just select the lights in the lighting tab.

**Comment by egberts** [comment]
Ok.  I get this.   When selecting individual LED in the GUI, sometimes the colors don’t get updated or is hard to see such changes.  Perhaps a bit thicker line showing as over-exaggerated horizontal bar?

**Comment by egberts** [comment]
This is just an aesthetic issue.  

I would like to make the top row in GUI a tad bit bigger as to let us know that they are CLICKABLE.  

Perhaps with a black line surrounding each clickable LED region. 

My two cents.

**Comment by egberts** [comment]
lower non-functional esthetic priority.  GUI-issue.

**Comment by egberts** [comment]
Closing this as originally fixed. 

Just a note that while it may be hard to see, it is in fact settable and changeable
.
