### ISSUE TITLE
Misspelling In Installer (Minor Issue)

### ISSUE THREAD

**Issue by dmutters** [ckb-next/ckb-next#683]
"Stopping" is misspelled in several places.  This is probably only a problem for people, like me, who are annoyed by spelling errors, and doesn't seem to affect the installer's ability to function.

/tmp/ckb-next/ckb-next-0.4.3$ grep stoppping * -R
build/src/daemon/cmake_install.cmake:  message(STATUS "systemd: stoppping ckb-next-daemon")
build/cmake_uninstall.cmake:            message(STATUS "${init_system}: stoppping ${daemon}")
build/cmake_uninstall.cmake:            message(STATUS "${init_system}: stoppping ${daemon}")
cmake/cmake_uninstall.cmake.in:            message(STATUS "${init_system}: stoppping ${daemon}")
cmake/cmake_uninstall.cmake.in:            message(STATUS "${init_system}: stoppping ${daemon}")
src/daemon/CMakeLists.txt:                    install(CODE "message(STATUS \"${CKB_NEXT_INIT_SYSTEM}: stoppping ${daemon}\")")
src/daemon/CMakeLists.txt:                    install(CODE "message(STATUS \"${CKB_NEXT_INIT_SYSTEM}: stoppping ${daemon}\")")
src/daemon/CMakeLists.txt:                install(CODE "message(STATUS \"${CKB_NEXT_INIT_SYSTEM}: stoppping ${daemon}\")")

**Comment by tatokis** [comment]
Didn't notice them. Thank you!
