### ISSUE TITLE
CKB-next gui closes when clicking  "+ New profile" in the Device Profiles window

### ISSUE THREAD

**Issue by dmbekker** [ckb-next/ckb-next#685]
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
Done
- If possible, try the latest code by building the software manually.
Did not build manually.
- File unrelated issues separately.

**Click the `Generate Report` button in the `Settings` tab of the ckb-next user interface and attach the generated report to this issue.**

### Source
ppa:tatokis/ckb-next

## Logs & crash reports

[ckb-next-report-1608903975.gz](https://github.com/ckb-next/ckb-next/files/5742028/ckb-next-report-1608903975.gz)

dmesg shows a segfault right when I click "+ New Profile"
```

[Dec25 14:53] ckb-next[20719]: segfault at 30 ip 000056055f049213 sp 00007ffea3258900 error 4 in ckb-next[56055efa3000+20e000]
[  +0,000004] Code: c3 66 0f 1f 44 00 00 53 48 8b 47 70 48 89 f3 48 89 b7 80 00 00 00 c6 40 50 01 48 89 70 10 c6 87 d8 00 00 00 01 e8 1d 0f 0a 00 <48> 8b 7b 30 5b e9 43 fb 00 00 90 66 90 8b 87 dc 00 00 00 c3 90 0f
[Dec25 14:54] ckb-next[21238]: segfault at 30 ip 00005582bf578213 sp 00007ffc77216b30 error 4 in ckb-next[5582bf4d2000+20e000]
[  +0,000005] Code: c3 66 0f 1f 44 00 00 53 48 8b 47 70 48 89 f3 48 89 b7 80 00 00 00 c6 40 50 01 48 89 70 10 c6 87 d8 00 00 00 01 e8 1d 0f 0a 00 <48> 8b 7b 30 5b e9 43 fb 00 00 90 66 90 8b 87 dc 00 00 00 c3 90 0f
```

## What is the program's current behaviour?
When clicking the Profile-dropdown and selecting "Manage profiles" the "Device Profiles" window opens.  I click "+ New Profile". After clicking the program closes  without any error messages

The only profile currently listed is the default Demo profile. 

## What is the expected behaviour of the program?
When clicking "+ New Profile" I expect the program to not close and let me create a new profile. 

## Any other notes & comments?
Happens right after installing ckb-next. Haven't used the program before.

Running Linux Mint 19.3 on kernel 5.4.0-42-generic  with a corsair K70 RGB Mk.2  keyboard. 

Program version:
```
$ ckb-next --version
qt5ct: using qt5ct plugin
ckb-next 0.4.3
```

**Comment by tatokis** [comment]
Thanks for the report. Looks like this bug slipped through in the last release.
I just fixed it and it's in the ckb-next-git PPA https://launchpad.net/~tatokis/+archive/ubuntu/ckb-next-git
