### ISSUE TITLE
add icue nexus 

### ISSUE THREAD

**Issue by tournade** [ckb-next/ckb-next#691]
Hello to you

I would like if possible to have the touch screen support for the cosair icue nexus

thanks in advance
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/5784548/ckb-next-dev-detect-report.gz)

**Comment by tournade** [comment]
Hello to you

I would like if possible to have the touch screen support for the cosair icue nexus

thanks in advance

**Comment by simonhf** [comment]
+1

**Comment by gravityfargo** [comment]
closing in favor of #906
