### ISSUE TITLE
Command line/Program control of lighting

### ISSUE THREAD

**Issue by craeftsmith** [ckb-next/ckb-next#694]
I'd like to be able to have different programs control the lights on the keyboard.  For example, some code that detects motion in my webcam and makes the keyboard glow a certain way.  Is there a way to call this program from other programs?

Example usage:

$ cam_detect | cbk-next <action file>

Does this capability exist?

**Comment by Ravenslofty** [comment]
This is exactly the purpose of the ckb-next [pipe animation](https://github.com/ckb-next/ckb-next/wiki/Animations#pipe). You give it a command to execute, and it will create a pipe that you can write RGB data to.
