### ISSUE TITLE
K60 RGB PRO (CH) [1b1c:1ba0]

### ISSUE THREAD

**Issue by F-Hauri** [ckb-next/ckb-next#705]
## CORSAIR K60 RGB PRO Mechanical Gaming Keyboard

Just tested today, with latest version.

This KBD with USB id: `1b1c:1ba0` seem not same keyboard than `#697` (`1b1c:1b8d`)

**Click the `Generate Report` button in the `Settings` tab of the ckb-next user interface and attach the generated report to this issue.**

I've manually runned `./ckb-next-dev-detect` from disant ssh session. (desktop is not mine, I'm buildild install while user is working on;)

So the report will miss X related infos. I hope this is not harmful.

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/6177847/ckb-next-dev-detect-report.gz)

**Comment by YeisonHunt** [comment]
OMG, this is to support the K60 RBG PRO SE?

**Comment by F-Hauri** [comment]
SE is not CH_FR, but look like to be same...

**Comment by khris190** [comment]
[ckb-next-report-1623221483.gz](https://github.com/ckb-next/ckb-next/files/6621660/ckb-next-report-1623221483.gz)
this is SE

**Comment by jblievremont** [comment]
Note that French K60 RGB PRO (AZERTY layout, P/N: CH-910D019-FR) seems to have the same device ID (`1b1c:1ba0`) - see [ckb-next-report-1627594405.gz](https://github.com/ckb-next/ckb-next/files/6903781/ckb-next-report-1627594405.gz).

For someone with some knowledge of system programming and limited knowledge of C and C++, what could help move this forward? I have a Windows 10 box on which I can capture USB traffic if necessary.

**Comment by lotar1954** [comment]
What is the status of K60 RGB PRO? Are there any news?

**Comment by Ravenslofty** [comment]
Supported as of #798.
