### ISSUE TITLE
X key is more red than all the other keys when using ckb-next

### ISSUE THREAD

**Issue by buzzkillingtonne** [ckb-next/ckb-next#710]
### Source
How and where did you get this program, e.g.:
  * Package from AUR
  * built and installed using yay
Issue is also noticed in the ckb-next-git package. it is also noticed in Manjaro 21.x, EndeavourOS, and Arch.

## Logs
[ckb-next-report-1619399438.gz](https://github.com/ckb-next/ckb-next/files/6373633/ckb-next-report-1619399438.gz)

## What is the program's current behaviour?
The X key shows more red than any other key. this key is closer to #ff7d7d when all keys are set to #ffffff for color. this affects every other color.

## What is the expected behaviour of the program?
Colors should be the same no matter the key unless there are hardware issues

## Any other notes & comments?
I have tested this keyboard in the Corsair program in Windows to be sure the keyboard is not an issue, the keys show correct colors in the Corsair application, this leads me to believe the X key is capable to displaying the correct colors.

**Comment by tatokis** [comment]
Does it also happen if you set the keyboard at full brightness in the Corsair software, under settings?
