### ISSUE TITLE
Wired Harpoon issues

### ISSUE THREAD

**Issue by djijitsu** [ckb-next/ckb-next#712]
I wanted to be able to turn off the RGB on my wired Harpoon mouse. I installed ckb-next using terminal in Linux Mint Ulyssa and the mouse immediately stopped functioning. If I recall correctly I tried uninstalling the PPA, but I only gained control of some of the mouse buttons, but not the cursor. I tried reinstalling and brought up the ckb manager that says 'no device connected'.
I also think there were some interference with the laptop touch pad upon installation, but thankfully it got function back after a reboot.

Would appreciate some advice on how I should proceed to get a functioning mouse ASAP!

[ckb-next-report-1619713723.gz](https://github.com/ckb-next/ckb-next/files/6400235/ckb-next-report-1619713723.gz)

**Comment by Ravenslofty** [comment]
Please join us in IRC, you can find the freenode button in the readme.

**Comment by tatokis** [comment]
Your mouse is in bootloader mode. You either need to reinstall the firmware through ckb if possible, or plug it in to a computer with corsair's software to recover it.

**Comment by djijitsu** [comment]
> Please join us in IRC, you can find the freenode button in the readme.

okay, thanks.



> Your mouse is in bootloader mode. You either need to reinstall the firmware through ckb if possible, or plug it in to a computer with corsair's software to recover it.

Thank you! Is there any way to reinstall the firmware manually through ckb?

**Comment by djijitsu** [comment]
I got great help from the IRC channel! Thanks alot!
