### ISSUE TITLE
Cannot remove ckb-next

### ISSUE THREAD

**Issue by Crateria** [ckb-next/ckb-next#714]
Hi,

I've followed the instructions to uninstall and it isn't working. I'm still kind of a Linux noob so I can't really think outside of the box with removing this aside from being provided instructions. I have Xubuntu/XFCE 4.14. All terminal commands provided do not remove anything.  I have no use for ckb-next because the Corsair devices I have are not supported, so I don't have a need to have this on my system. 

Please help me remove this.

Thank you.

**Comment by tatokis** [comment]
In order for us to help you, you need to tell us how you installed it, and what steps you followed in an attempt to uninstall it.
