### ISSUE TITLE
Corsair K55 RGB PRO Gaming Keyboard not detected

### ISSUE THREAD

**Issue by yochananmarqos** [ckb-next/ckb-next#720]
### Source
Tried both AUR packages on Manjaro GNOME unstable branch: `ckb-next` 0.4.4-1 and `ckb-next-git` 1:0.4.4.r6.g190ffeed-1

## Logs & crash reports

```
❯ ckb-next
QObject::startTimer: Timers cannot have negative intervals
Path to settings: "/home/yochanan/.config/ckb-next/ckb-next.conf"
Scanning "/usr/lib/ckb-next-animations/gradient"
Scanning "/usr/lib/ckb-next-animations/heat"
Scanning "/usr/lib/ckb-next-animations/invaders"
Scanning "/usr/lib/ckb-next-animations/life"
Scanning "/usr/lib/ckb-next-animations/mviz"
Scanning "/usr/lib/ckb-next-animations/pinwheel"
Scanning "/usr/lib/ckb-next-animations/pipe"
Scanning "/usr/lib/ckb-next-animations/rain"
Scanning "/usr/lib/ckb-next-animations/random"
Scanning "/usr/lib/ckb-next-animations/ripple"
Scanning "/usr/lib/ckb-next-animations/snake"
Scanning "/usr/lib/ckb-next-animations/wave"
Disconnecting from X
XCB EWMH Thread Quitting...
```
`lsusb`
```
Bus 001 Device 005: ID 1b1c:1ba4 Corsair CORSAIR K55 RGB PRO Gaming Keyboard
```

```
❯ systemctl status ckb-next-daemon.service
● ckb-next-daemon.service - Corsair Keyboards and Mice Daemon
     Loaded: loaded (/usr/lib/systemd/system/ckb-next-daemon.service; disabled; vendor preset:>
     Active: active (running) since Wed 2021-06-02 16:57:38 MDT; 37min ago
   Main PID: 49931 (ckb-next-daemon)
      Tasks: 2 (limit: 38327)
     Memory: 456.0K
        CPU: 13ms
     CGroup: /system.slice/ckb-next-daemon.service
             └─49931 /usr/bin/ckb-next-daemon

Jun 02 16:57:38 serval systemd[1]: Started Corsair Keyboards and Mice Daemon.
Jun 02 16:57:38 serval ckb-next-daemon[49931]: ckb-next: Corsair RGB driver 0.4.4-6-g190ffeed
Jun 02 16:57:38 serval ckb-next-daemon[49931]: [I] Root controller ready at /dev/input/ckb0
```

[ckb-next-report-1622673875.gz](https://github.com/ckb-next/ckb-next/files/6587912/ckb-next-report-1622673875.gz)

## What is the program's current behaviour?
No devices connected.

## What is the expected behaviour of the program?
~~It should detect it as support is claimed.~~ Turns out the K55 and K55 PRO have different PIDs, the PRO needs to be added, apparently.

The keyboard works out of the box, I just wanted to be able to change the RGB settings. The fast rainbow pulse or whatever you call the default is distracting.

**Comment by Synfoxic** [comment]
Is it known if the K55 RGB PRO Keyboard will be added? Just bought it today and was a little confused, as it did not detect it....
Although I could live with the fact, that I have no software for it. That's a price I am willing to pay for Linux :D 
but it would be really nice though, if it was added. Unfortunately I have absolutely no experience in this to do something myself :(

**Comment by s3boun3t** [comment]
me too, i have a new corsair K55 rgb pro xt and it is not detected with ckb-next-git (0.4.4-77-g03d683c)

lsusb
Bus 001 Device 004: ID 1b1c:1ba1 Corsair CORSAIR K55 RGB PRO XT Gaming Keyboard

**Comment by Sganus** [comment]
The same problem for me...

**Comment by scott-o-ev** [comment]
Any word on the update for this issue? I'm having a similar problem with the Corsair CORSAIR K55 RGB PRO Gaming Keyboard.

Thanks.

**Comment by nikokio** [comment]
Hello,

Same here, I bought a K55 RGB Pro because K55 is supposed to be supported here but not this model (ToT). I should have check the issues first :p

Bus 001 Device 006: ID 1b1c:1ba4 Corsair CORSAIR K55 RGB PRO Gaming Keyboard

Thanks

**Comment by vdvb** [comment]
idem ditto
also bought a K55 RGB Pro , thought it was supported
Thx in advance

**Comment by SackyMusa** [comment]
Hello team, unfortunately it's the same for me. My K55 RGB PRO is not recognized by ckb-next. It's a pity, since I've completely switched to Manjaro Linux, and will stay with it. 
Would be very happy to hear from you !!!

**Comment by tatokis** [comment]
You can try what I mentioned here and see if you can get anywhere https://github.com/ckb-next/ckb-next/issues/721#issuecomment-983445570

**Comment by tatokis** [comment]
Sorry, the correct comment is this one https://github.com/ckb-next/ckb-next/issues/721#issuecomment-981554481

**Comment by DIYGuy01** [comment]
> Sorry, the correct comment is this one [#721 (comment)](https://github.com/ckb-next/ckb-next/issues/721#issuecomment-981554481)

a simple replacement in usb.h of id's doesn't help. After installation keyboard is not working at all.

```
//#define P_K55                0x1b3d
#define P_K55                0x1ba4 //K55 RGB PRO
```

**Comment by marciprete** [comment]
same problem here, brand new K55 but no luck.

**Comment by idc77** [comment]
What can we do to help?

**Comment by marciprete** [comment]
I've changed the id of the P_K55 with the output from lsusb. The keyboard is recognized and the GUI shows the map, but unfortunately nothing happens when I type, it looks like the key signals are not received nor interpreted. 
I'm not a C++ programmer, so I don't know what to do to debug. 
Let me know if I can do something to help

**Comment by localtux** [comment]
I also have this keyboard since today, unfortunately the workaround does not work with the usb.h. I would be happy if this keyboard is officially supported.

**Comment by K-Lorenz** [comment]
So no fix, but if you want to get the annoying watercolor/rainbow to go away you can set the colors in hardware mode.
Holding FN + 1-5 cycles the colors of the 5 zones. 
Holding FN + 6-0 enables the animation color themes.

You can also set makros: https://youtu.be/_gOF_CiBGQo

I know this doesn't really help, but for the time being...

**Comment by rmoorecpcc** [comment]
I bought this keyboard a month or so ago and been liking it, at least it does have hardware based color and macro controls but would be nice if ckb-next supported it, That said I did get the source to compile with -DCMAKE_BUILD_TYPE=Debug (had to tinker with the code to add qt6 libraries, and disable the translation files on ubuntu22). Not sure if this will help but there were some bragi errors on the console from launching the daemon:

```
# ./ckb-next-daemon 
ckb-next: Corsair RGB driver 0.5.0-69-gc7d0417
[I] Root controller ready at /dev/input/ckb0
[I] Adding device with vendor = 0x1b1c, product = 0x1ba4, path = /dev/bus/usb/001/005, syspath = /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6
[I] Connecting CORSAIR K55 RGB PRO Gaming Keyboard at /dev/input/ckb1
[I] Claiming interfaces. name=CORSAIR K55 RGB PRO Gaming Keyboard, firmware=0101, ep_str= 3
[I] ckb1: Claiming 3 interfaces
[I] Starting input thread for /dev/input/ckb1
[I] Found EP 0x81 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/ep_81
[I] Endpoint path /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/ep_81 has wMaxPacketSize 16
[I] Found EP 0x82 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/ep_82
[I] Endpoint path /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/ep_82 has wMaxPacketSize 64
[I] Found EP 0x83 at /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.2/ep_83
[I] Endpoint path /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.2/ep_83 has wMaxPacketSize 64
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x15. Device said it's not supported.
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x16. Device said it's not supported.
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x96. Device said it's not supported.
[W] bragi_get_property (bragi_common.c:13): Failed to get property 0x2. Device said it's not supported.
[I] ckb1: Pairing id: 00 00 00 00 00 00 00 00 
[I] Setup finished for /dev/input/ckb1
```

**Comment by JanNowak94** [comment]
Also can someone mark support correctly on supported devices?  I just did buy one thinking that it was supported by ckb-next (I was wise enough for checking compatibility but not wise enough to check issues).

Also this is keyboard default is mess - G1-G6 return 1-6 by default... which means you cannot remap them by hwdb and no you cannot do that under windows - iCUE does not seem to have way to save binds into hardware memory for this device.

**Comment by tatokis** [comment]
Use a `-git` package.

**Comment by tatokis** [comment]
For anyone encountering issues with the lighting on this device, please check https://github.com/ckb-next/ckb-next/issues/913#issuecomment-1487872185
