### ISSUE TITLE
No device connected, but generate log says otherwise

### ISSUE THREAD

**Issue by ninjamanthing** [ckb-next/ckb-next#737]
my k60 rgb pro doesn't show up as a connected device in the program, but when i generate a log, it shows up. am i just dumb or is there something missing?

i am using manjaro linux

**Comment by Ravenslofty** [comment]
Well, ckb-next doesn't presently support the K60 RGB Pro, so we don't touch it.

**Comment by Ravenslofty** [comment]
I'm going to close this as a duplicate of #697.
