### ISSUE TITLE
Event manager doesn't work

### ISSUE THREAD

**Issue by maplepy** [ckb-next/ckb-next#744]
## General information

CKB does not switch profiles on autostart and has to be close (quit) and reopened to work and/or the user have to manually click on another profile for it to switch automatically based on events 

### Source
How and where did you get this program, e.g.:
  * Package from AUR

## Logs & crash reports

[ckb-next-report-1631441438.gz](https://github.com/ckb-next/ckb-next/files/7149394/ckb-next-report-1631441438.gz)

## What is the program's current behaviour?
CKB won't switch profiles depending on the program on the first run (autostart)

## What is the expected behaviour of the program?
Changing profile depending on the program setup in "manage events"

## Any other notes & comments?
Why can't it load properly the first time and switch profiles automatically without having to quit the program and reopen it

**Comment by ClemGlacee** [comment]
#702 was the same issue but it never got fixed apparently

**Comment by ClemGlacee** [comment]
I have no issue or errors when closing ckb-next (checked in the terminal)
```Disconnected from PulseAudio 6
Disconnecting from X
XCB EWMH Thread Quitting...
```


Although this is being spammed in the terminal when ckb is opened
```qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile
qt.gui.icc: Unsupported ICC profile class 70727472
QPngHandler: Failed to parse ICC profile```

**Comment by SteffanoP** [comment]
Same Issue here, even if I delay the application start...

**Comment by jdpnielsen** [comment]
I'm running Gnome 3.38.4-1ubuntu3~21.04.1.

Output is:
```
$ echo $XDG_SESSION_TYPE
echo $XDG_SESSION_DESKTOP
x11
ubuntu
```

**Comment by ClemGlacee** [comment]
OS: EndeavourOS Linux x86_64
Kernel: 5.14.16-arch1-1
DE: Plasma 5.23.2‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zeparu** [comment]
running into this issue too right now, at first i thought the automatic profile switching didnt work at all, but manually restarting ckb-next after it was auto-started, makes it work

**Comment by tatokis** [comment]
Sorry, I really haven't had any time to look into this. Is there a way for someone to get a log from the gui during a start when it's broken? (For example from /var/log/syslog on ubuntu.)

**Comment by zeparu** [comment]
this here is a full journalctl log from starting it with the auto-start, to creating a new color mode and setting up the dynamic switching rule https://pastebin.com/eBFUNcAi

**Comment by tatokis** [comment]
Should be fixed in the latest code from master (https://github.com/ckb-next/ckb-next/commit/27d0547d09e481ade933bfb3292498bbbe2e7087)

**Comment by zeparu** [comment]
i can install `ckb-next-git` and see tomorrow if itll work properly

**Comment by zeparu** [comment]
can confirm, that its working properly with switching now, when ckb-next was started with the auto start feature

**Comment by tatokis** [comment]
I ended up rewriting some of the window detection code. Can you please test again?

> when is the next release scheduled?

It's not. There are a lot of things that still need to be taken care of.

**Comment by tatokis** [comment]
Thank you for testing!

**Comment by maplepy** [comment]
Do you have an ETA so I can download that program back?
