### ISSUE TITLE
Corsair K60 RGB PRO CH-910D019-NA

### ISSUE THREAD

**Issue by lotar1954** [ckb-next/ckb-next#751]
The keyboard is not detected by the ckb-next software (latest build included).

`Bus 002 Device 007: ID 1b1c:1ba0 Corsair CORSAIR K60 RGB PRO Mechanical Gaming Keyboard
`

Please let me know if you need further info. In addition to this, if you need a tester for the K60 RGB PRO, count me in. 

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/7270439/ckb-next-dev-detect-report.gz)

**Comment by Synfoxic** [comment]
there is already an opened issue for this: https://github.com/ckb-next/ckb-next/issues/720#issue-909961273

**Comment by Synfoxic** [comment]
> > there is already an opened issue for this: [#720 (comment)](https://github.com/ckb-next/ckb-next/issues/720#issue-909961273)
> 
> No, that's about K55.
> 
> For K60, there are #697, #705, #722

sorry, my bad

**Comment by MatthiasSeu** [comment]
Are there any new news regarding K60 support?

**Comment by akintelligentmedia** [comment]
There is some work in progress #796!

**Comment by akatran** [comment]
There is some work in progress https://github.com/ckb-next/ckb-next/pull/796!

**Comment by gravityfargo** [comment]
Support was added with #798
