### ISSUE TITLE
Display "Refresh Rate" instead of "FPS"

### ISSUE THREAD

**Issue by coatlessali** [ckb-next/ckb-next#756]
## What is the program's current behaviour?
Displays "Frame Rate/FPS" under "Hardware".
## What would you like it to do instead?
Display "Refresh Rate" instead.
## Any other notes & comments?
I wasn't exactly sure where to put this or if there's a reason for the terminology FPS instead of refresh rate, when it seems refresh rate would be more accurate to RGB lighting.

**Comment by Ravenslofty** [comment]
Well, a frame is a complete image, and that's what ckb-next sends to the device in question. Especially with stuff like the `snake` and `invaders` animations I think it's hard to argue it *isn't* a frame of video.

Plus I think it's generally more intuitive to users to call it "frames per second" than "refresh rate" in terms of what the option does.
