### ISSUE TITLE
Corsair K100 

### ISSUE THREAD

**Issue by GermanKingYT** [ckb-next/ckb-next#765]
# Before you proceed

- Check if your device is listed in the [wiki](https://github.com/ckb-next/ckb-next/wiki/Supported-Hardware).
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues).
- If possible, try the latest code by building the software manually.
- File unrelated issues separately.

**Click the `Generate Report` button in the `Settings` tab of the ckb-next user interface and attach the generated report to this issue.**

---

Enter the name of your device here and attach the report generated above.

**Comment by GermanKingYT** [comment]
[ckb-next-report-1638029240.gz](https://github.com/ckb-next/ckb-next/files/7612011/ckb-next-report-1638029240.gz)

**Comment by bG9sIHVyIGhvbW8** [comment]
#651
