### ISSUE TITLE
Corsair Ironclaw RGB not showing up

### ISSUE THREAD

**Issue by LiveFromMommysBasement** [ckb-next/ckb-next#768]
### Source
AUR and yay

## Logs & crash reports
[ckb-next-report-1638140860.gz](https://github.com/ckb-next/ckb-next/files/7614606/ckb-next-report-1638140860.gz)

## What is the program's current behaviour?
It cannot detect my Corsair Ironclaw RGB mouse

## What is the expected behaviour of the program?
To detect and control the mouse

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/558
