### ISSUE TITLE
Issue Cleanup

### ISSUE THREAD

**Issue by rmrfforewardslashstar** [ckb-next/ckb-next#779]
Hello! 
Super happy this project exists. I'm new to the C language, but I want to support if I can. I see there are many stale issues currently open and I figure listing out a few that should be closed might help! macOS support is dropped, so it might be privy to close the issues or throw a uniform tag on them if a MacOS savvy contributor pops in.

I see there are issue tags for specific hardware models but they're not actively assigned. I'd love to help with that if I can!

Parent Issue:
Issue #660 "Dropping support for macOS"

Possible Closures:
On waking from sleep: "no devices connected" #5
GUI Gets Cut Off #11
Ship license with the product #16
License change due to violations #17
CKB Next App with VoiceOver Accessibilities on MacOS #20
K68 RGB unresponsive at CKB launch. #170
Daemon tries to use keyboards in BIOS mode on macOS #189
ckb next not detecting my mouse anymore #232 (according to submitter's attached report file)
Add dropdown for pollrate selection in the GUI #272
MacOS X 100% CPU usage and heat issue #280
Corsair K95 RGB Platinum Cannot Find 'FN' on macOS #284
Support for Portuguese ISO Layout #297
CapsLock RGB indication changes before CapsLock is activated by the system #303

Cheers!

**Comment by tatokis** [comment]
Apologies for the stupidly late reply, but thank you for this. It is really appreciated, since as you can tell, I really struggle to manage the issue tracker at this point.
I have closed the issues you pointed out and labelled them accordingly.

If you can find any other ones, please let me know and I'll close them.
