### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by BloodyIron** [ckb-next/ckb-next#782]
With the changes that have happened since the March 2021 release, can we please see a new release come out so that the updates can eventually roll out to us using repos? :)

**Comment by BloodyIron** [comment]
@tatokis ?

**Comment by tatokis** [comment]
If you want to speed up the release, you can start by building the latest code from git, fixing the warnings in the daemon and making PRs.

It's basically only me here, and I don't presently consider it acceptable to make a release when there are basic features that need to be implemented.
The daemon can't read the firmware version from new devices. There's no support for pollrates <1ms. The daemon gets stuck in an endless loop if it can't talk to bragi devices. It's not been decided what to do with experimental devices on release. And so on, and so on.

**Comment by tatokis** [comment]
As a sidenote, I've created a milestone. I'll try to get the release out in the upcoming weeks, but I can't promise anything.
https://github.com/ckb-next/ckb-next/milestone/3

**Comment by BloodyIron** [comment]
Yay! Hit my repos, thanks again! :D
