### ISSUE TITLE
Ironclaw RGB not able to rebind profile cycle button

### ISSUE THREAD

**Issue by Srdjan-V** [ckb-next/ckb-next#786]
### Source
How and where did you get this program, e.g.:
  * Package from AUR
  * ckb-next-git

## Logs & crash reports
[ckb-next-report-1643159095.gz](https://github.com/ckb-next/ckb-next/files/7938256/ckb-next-report-1643159095.gz)

## What is the program's current behaviour?
After rebinding the profile cycle button to middle mouse button or print screen (maybe others) it simply does nothing.

## Any other notes & comments?
I have tried this in virtualbox through passthrough, but this bug also existed about 6 months ago when i tried linux on my pc.

**Comment by jdmj** [comment]
Same for the Nightsword. Weirdly, one function "Profile Up" button can be remapped to is brightness control.

**Comment by tatokis** [comment]
Should be fixed in ckb-next-git.
