### ISSUE TITLE
Outdated wiki

### ISSUE THREAD

**Issue by fracasula** [ckb-next/ckb-next#799]
In [this page](https://github.com/ckb-next/ckb-next/wiki/Linux-Installation) for OpenSuse there is a missing packet.

What you are reporting is to do the following:
```
sudo zypper install gcc gcc-c++ make cmake linux-glibc-devel zlib-devel libqt5-qtbase-devel systemd-devel libpulse-devel quazip-qt5-devel libudev-devel libqt5-linguist-devel git libdbusmenu-qt5-devel

git clone https://github.com/ckb-next/ckb-next.git
cd ckb-next
./quickinstall
```

But then you would get:
```
CMake Error at src/gui/CMakeLists.txt:287 (message):
  XCB-EWMH was not found.  Either install it or pass -DUSE_XCB=0 to disable
  active window detection.
```

You're missing this packet: `sudo zypper in xcb-util-wm-devel`.

I'm running on the latest OpenSuse Tumbleweed (rolling release).

**Comment by tatokis** [comment]
Thank you.

It's probably also missing libxcb-devel and xcb-util-wm-devel. Can you verify that those packages exist in the repositories to add them as well?

**Comment by tatokis** [comment]
Thank you.

It's probably also missing libxcb-devel and xcb-util-devel. Can you verify that those packages exist in the repositories to add them as well?

**Comment by fracasula** [comment]
I had `libxcb-devel` already installed and the package name is correct if you want to add it.
In regards to `xcb-util-devel`, also the package name is correct and exists in the repos but I didn't have to install it (and the drivers are working).

Thanks for all this by the way, I can finally configure my K95 on Linux :slightly_smiling_face:

**Comment by tatokis** [comment]
Awesome! Just edited the page in the wiki.

**Comment by fracasula** [comment]
I ended up building on a new system and I got this error:

```
--   Found xcb-screensaver, version 1.14
CMake Error at src/gui/CMakeLists.txt:275 (message):
  XCB-Screensaver or Qt5 X11Extras was not found.  Either install them or
  pass -DUSE_XCB=0 to disable idle detection.
```

Solved by installing `libqt5-qtx11extras-devel` :+1:

**Comment by tatokis** [comment]
Thanks. Added that as well
