### ISSUE TITLE
Documentation / HOWTO Question

### ISSUE THREAD

**Issue by ctassell** [ckb-next/ckb-next#810]
Hi Folks,

  I'm using ckb-next on Ubuntu Linux with a K63 wired.  It works pretty well (the keyboard sometimes crashes when I come out of sleep mode and I have to remove the USB cable and plug it back in) but I find that the LEDs are a little bright even on the lowest 33% setting.  It seems that there is a way to turn off the lighting of individual keys, but I can't figure out how to do it in the UI.  Can anyone point me to some docs or explain how to do it?  Right now when I open up the UI a couple of the keys seem to have a black circle with a yellow outline, and those keys don't light up.  I'd like to have *all* the keys set like that, except for the media keys and the 3x2 Insert/Home/etc block.

**Comment by pjreed** [comment]
If you set a key's RGB color to black (0,0,0), that should stop it from lighting up.  That works for me, although I'm building from source rather than using the latest binary release; you might try building it yourself that if you're still having issues.

**Comment by ctassell** [comment]
Thanks, that worked perfectly.  I was even able to dim the 33% lighting by putting the colour code to 50.
