### ISSUE TITLE
Modify GUI and daemon to handle sub-1ms pollrates

### ISSUE THREAD

**Issue by tatokis** [ckb-next/ckb-next#814]
Currently the interface parses an int as a pollrate, with 1 meaning 1ms. This obviously doesn't work for faster ones.
Ideally there will be a non-breaking way of implementing this, with this possibly having to convert it to a float, at least in the interface.

A new flag/feature will also have to be added to signify if the device supports it, of perhaps a "max pollrate" file. Bragi has the ability to return what the max pollrate is.

Also, with the introduction of the new fwversion numbers, the pollrate devnode code should be changed to also signify that if the pollrate file is blank, then the feature is not supported, removing it the pollrate flag from features.

**Comment by Grocel** [comment]
Higher than 1000 Hz polling rates are becoming a real thing apparently.

These devices could need them:
- Sabre Pro & Sabre RGB Pro Championship mice: https://github.com/ckb-next/ckb-next/issues/709
- K100 Keyboard: https://github.com/ckb-next/ckb-next/issues/651
