### ISSUE TITLE
Error Loading ckb

### ISSUE THREAD

**Issue by thesnowfury** [ckb-next/ckb-next#818]
Hi getting this after installing ckb

ckb-next: error while loading shared libraries: libquazip1-qt5.so.1.0.0: cannot open shared object file: No such file or directory

any ideas?

**Comment by thesnowfury** [comment]
Nevermind, QuaZip got updated, downgraded to 1.0 and all working again

**Comment by tatokis** [comment]
What program did you use to install ckb-next? pamac? yay?

**Comment by zeparu** [comment]
dont even need to downgrade, i just symlinked it to libquazip1-qt5.so.1.0.0, still works fine

issue shouldn't be closed imo, maintainers should upgrade / change the dependency with libquazip

**Comment by thesnowfury** [comment]
> What program did you use to install ckb-next? pamac? yay?

I used pacman to install a while ago but it broke when I did a system update (sudo pacman -Syu)

**Comment by vrpsunited** [comment]
> dont even need to downgrade, i just symlinked it to libquazip1-qt5.so.1.0.0, still works fine
> 
> issue shouldn't be closed imo, maintainers should upgrade / change the dependency with libquazip

Good idea - did you simply create a file with the name of the old lib and inside the path to the new lib?
:D
