### ISSUE TITLE
ckb-next: error while loading shared libraries: libquazip1-qt5.so.1.0.0

### ISSUE THREAD

**Issue by fracasula** [ckb-next/ckb-next#822]
Hi there, after the latest OpenSuse Tumbleweed update I started to get this error.

What I have is:
* `libquazip1-qt5-1_3_0`
* `quazip-qt5-devel`

Is seems that `ckb-next` is looking for version 1.0.0 while the minimum that I can install is the 1.3.0.

To make it work I simply did: `sudo ln -s /usr/lib64/libquazip1-qt5.so /usr/lib64/libquazip1-qt5.so.1.0.0`.

So now I got this in my `/usr/lib64`:
```
lrwxrwxrwx 1 root root    23 Apr 18 00:25 libquazip1-qt5.so -> libquazip1-qt5.so.1.3.0
lrwxrwxrwx 1 root root    28 May  2 09:32 libquazip1-qt5.so.1.0.0 -> /usr/lib64/libquazip1-qt5.so
-rwxr-xr-x 1 root root  207K Apr 18 00:25 libquazip1-qt5.so.1.3
lrwxrwxrwx 1 root root    21 Apr 18 00:25 libquazip1-qt5.so.1.3.0 -> libquazip1-qt5.so.1.3
```

The application is now working fine. 
Not sure how easy it would be to fix on your end but I thought I'd let you know that on 1.3.0 I haven't had any issue so far.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/646#issuecomment-705986601
