### ISSUE TITLE
No package for jammy

### ISSUE THREAD

**Issue by joe-mojo** [ckb-next/ckb-next#826]
## What is the program's current behaviour?
Official Ubuntu ppa doesn't contain package for jammy

## What would you like it to do instead?
I would like a build for jammy

## Any other notes & comments?
I'm trying impish package while you do that ;)

**Comment by tatokis** [comment]
I published it, but the one from the repos is considered newer either way. I remember now why I didn't do it in the first place and was waiting for 0.5.0.
I'll have to bump up the epoch on the next build.

**Comment by tatokis** [comment]
I decided against changing the epoch, however it no longer makes any difference.
