### ISSUE TITLE
K60 RGB french layout not recognized 

### ISSUE THREAD

**Issue by S1ss3l** [ckb-next/ckb-next#850]
- Check if your device is listed in the [wiki](https://github.com/ckb-next/ckb-next/wiki/Supported-Hardware). (It is)
- Search in open and closed [Issues](https://github.com/ckb-next/ckb-next/issues). (Did that)
- If possible, try the latest code by building the software manually. (Did that too)
Here's my report :
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/8991012/ckb-next-dev-detect-report.gz)
I took a look at every issue I could find related to my keyboard but from what I gathered, I shouldn't have that problem.
I assumed the 0xYYYY in the src/daemon/usb.h file were product ID so I tried to swap the one for my keyboard to the one I had in the report but to no avail.
I'm really sorry if I'm doing something dumb, this is my first time ever opening an issue.

Edit : If I may add, I'm very much a newbie but if someone can give me pointer, I'm willing to fix the issue by myself.

**Comment by tatokis** [comment]
Keyboard ended up being a monochrome variant. Fixed by https://github.com/ckb-next/ckb-next/commit/38420fd8e2fa3163c73d652e06b14d5bda575c0d
