### ISSUE TITLE
Can't customize RGB of Katar Pro XT 

### ISSUE THREAD

**Issue by AFCMS** [ckb-next/ckb-next#857]
Katar Pro XT is listed as supported in the wiki, and I am able to use the key binding feature.

But then the mouse wheel is always green, even if I put some animations.

(If someone try to make a fix I am able to build and test it if you want)

**Comment by tatokis** [comment]
Under performance, turn off "Use DPI Indicator"

**Comment by AFCMS** [comment]
Oh thanks xD

It was quite confusing because I made changes in the lightning tab and they don't appear on the mouse, and I almost never change my DPI so I didn't notice a color change when switching DPI.
