### ISSUE TITLE
Support for the Corsair Dark Core RGB Pro Mouse in Wireless Mode

### ISSUE THREAD

**Issue by jitoxx** [ckb-next/ckb-next#867]
I found your project and i would ask if you can add support for the Corsaie Dark Core RGB Pro Wireless Mouse to configure DPI and the RGB-Light. For the moment, it's working on USB-Mode only.

**Comment by EwanMac3** [comment]
I would love to see this added as well. For some reason, the forward and back mouse buttons type out 2 and 1 as numbers on a keyboard when connected wirelessly, but work fine when wired with ckb-next.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/pull/855 More testing would be appreciated (especially the middle button issue mentioned in the comments near the end).
