### ISSUE TITLE
Corsair CORSAIR SABRE RGB PRO Gaming Mouse (1b79) Support

### ISSUE THREAD

**Issue by RyanBlakeIT** [ckb-next/ckb-next#885]
It looks like this mouse is showing as supported but the software isn't letting me manage it.

Including the report as requested:
[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/9650936/ckb-next-dev-detect-report.gz)

**Comment by Grocel** [comment]
Has been posted already, but 👍 from me:

https://github.com/ckb-next/ckb-next/issues/709

**Comment by RyanBlakeIT** [comment]
> Has been posted already, but 👍 from me:
> 
> #709

Sorry about that and thank you!

**Comment by tatokis** [comment]
@RyanBlakeIT really sorry for this. It was mistakenly added as supported. I'll fix the wiki.
Once I'm done with the K100 I'll get to adding this mouse.
