### ISSUE TITLE
K95 platinum profile switch key

### ISSUE THREAD

**Issue by delooper** [ckb-next/ckb-next#92]
Greetings, 

I acquired a K95 platinum this morning and was happy to discover ckb-next.  I'm running Ubuntu 16.04, and installed ckb-next via the git repo.  The only feature of the K95 I know of that I have not been able to use is the "profile switch key".  Is this presently not supported in ckb-next?  Is there anything I could do to help?  

I don't have much experience writing drivers but I do have quite a bit of coding and debugging experience. 

Thanks for all the effort! It's much appreciated.

-ryan

**Comment by ZirconiumX** [comment]
Would you mind clarifying what you mean by "profile switch key"? Do you
mean the MR button?

**Comment by tatokis** [comment]
@delooper We should perhaps try and get it renamed to something more obvious then, however have you tried binding it?
![dc3d232b2e45](https://user-images.githubusercontent.com/6003656/36195356-dff049fc-1175-11e8-932c-845ba233b1e1.jpg)

**Comment by ZirconiumX** [comment]
Right, hardware animations, like on the K95 Platinum, are currently
unsupported because we don't have the infrastructure in place for it. To do
so would require us to rewrite the animation API, which assumes real-time
software control, and right now that's fairly low priority.

ckb-next doesn't really have any packet capture facilities; we tend to use
wireshark. I believe the daemon will print a warning when it receives an
unknown keypress though.

**Comment by delooper** [comment]
Ah, thank you!  Yes, in that menu it would be the MR key.  

Apologies for being new to this. 

I tried binding the MR key as "Switch to mode (next) wrap-around".  After applying and "save to hardware" the MR key continues to do nothing.  I have 4 rather different modes in the  main (left side of window) list.

**Comment by tatokis** [comment]
@delooper First of all, Save to hardware isn't supported for your model, so please do not use it.
Second, as @ZirconiumX said, the daemon prints a warning when it receives an invalid keypress.
Please run ckb-dev-detect, which will collect any output from it, and upload it here.

**Comment by ZirconiumX** [comment]
"Save To Hardware" on the K95 Platinum, and on v3 firmwares, is currently
broken. It requires a fix for switching message types, but I think there's
currently a pull request for that.

**Comment by delooper** [comment]
Thanks for all the comments.  Here is the output of ckb-dev-detect in case it's helpful -- perhaps it's redundant at this point. 

[ckb-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1723310/ckb-dev-detect-report.gz)

**Comment by tatokis** [comment]
@delooper Can you control the LEDs on that button using ckb?
Run `cat /dev/input/ckb1/notify1` and press the button. It should tell you what it thinks it is.

**Comment by delooper** [comment]
No, it looks like I can't.   

When I press the MR key the notify1 file produces:

key +#70
key -#70

**Comment by ZirconiumX** [comment]
Hmmm, looks like we need to add that key to the daemon.

**Comment by tatokis** [comment]
Closed by https://github.com/ckb-next/ckb-next/commit/d79bf1880a5b4f6af60395a33d69e9435374b682

**Comment by delooper** [comment]
Thanks for all the help.  Glad this is resolved now.
