### ISSUE TITLE
CKB-Next suddenly stopped working, even after rebuilt

### ISSUE THREAD

**Issue by TheKarion** [ckb-next/ckb-next#922]
### Describe your situation in detail.

Not launching, rebuilt the package and tried both -git and ckb-next, I'm using the chaotic aur tho.

### Additional Details

Was working for about 2 months till a few days ago when it suddenly stopped.

### Generated Report (if applicable)

[ckbnexterror.txt](https://github.com/ckb-next/ckb-next/files/10483778/ckbnexterror.txt)

**Comment by tatokis** [comment]
You need to contact chaotic AUR to rebuild the package.

**Comment by TheKarion** [comment]
On it, thank you

**Comment by Technetium1** [comment]
@TheKarion Done: https://github.com/chaotic-aur/interfere/commit/e0448fc9c8aa7d2f0891bdbd80e721eec7dc3d5c
