### ISSUE TITLE
Switched profilesAndOrMode based on current selected window.

### ISSUE THREAD

**Issue by NicTanghe** [ckb-next/ckb-next#924]
### Enhancement Details

I`d like the ability to allowdiferent profiles to be used depending on what window is in focus.

Example bind mousekeys to nex previous  tab in firefox.
bind them to poly extrude and paste in Houdini.
And bind these keys to use items when DOTA2 is in focus.

**Comment by tatokis** [comment]
![mode_event_manager](https://user-images.githubusercontent.com/6003656/214697082-711166ae-f90e-451c-b71b-eb35ad2816f6.png)
