### ISSUE TITLE
Volume increases after every key press

### ISSUE THREAD

**Issue by lukawarren** [ckb-next/ckb-next#936]
### Affected Devices

Strafe RGB

### Linux Distribution

Fedora 37

### Installation Method

official Fedora repos

### ckb-next version

ckb-next 0.5.0

### What did you expect?

When I'm using my keyboard, everything works fine most of the time. All keys work as expected.
However, sometimes when I change the volume, the following happens:

- I press the function key
- I press volume up or volume down
- The volume changes as expected
- However, any subsequent key presses will repeat this action

For example, if this bug occurs and I increase the volume,  every single key press afterwards will also increase the volume!

It's difficult to reproduce because it only happens for me very occasionally - maybe once every few hours. I've noticed that it usually happens when watching YouTube videos after I've been browsing for a while, so perhaps it's down to high CPU load?

### Did you try anything that may have helped?

Closing ckb-next resolves this issue.
It does not occur on Windows.
A few years ago I used ckb-next on Manjaro, and it didn't occur there either.

### Additional Details

Add any additional details here.

### Generated Report

[ckb-next-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/10885004/ckb-next-dev-detect-report.gz)

**Comment by tatokis** [comment]
It's a firmware bug.
https://github.com/ckb-next/ckb-next/issues/40#issuecomment-375141122

Try resetting the keyboard: unplug it, hold down Esc, and with the Esc key held down, plug it in and keep it pressed for a few seconds.
