### ISSUE TITLE
K70 MK.2 RGB 'Save to hardware' greyed out

### ISSUE THREAD

**Issue by Lowrida** [ckb-next/ckb-next#937]
### Describe your situation in detail.

Before i installed ckb-next i had 3 profiles, now i have only one left and i can't store any newly made profiles to the keyboard. So every time i boot my system i get a rainbow wave and can't change it to something else or adjust brightness. Very annoying when in bios or not logged into linux!

How can i store my own profiles to the device?

K70 MK.2 RGB
Linux Mint 20.3 Cinnamon

### Additional Details

Add any additional details here.

### Generated Report (if applicable)

Drag your generated report here if it's applicable.

**Comment by Lowrida** [comment]
Anyone who knows how to do this?

**Comment by Lowrida** [comment]
I guess nobody knows...

**Comment by Ravenslofty** [comment]
It's greyed out because we haven't implemented it in ckb-next yet.

**Comment by Lowrida** [comment]
Ah ok. But why are my other profiles gone? Standard there were three of them..

**Comment by gravityfargo** [comment]
I don't know enough about the code to answer why the other profiles are gone, but I'd like to comment we can't give a timeline for any particular feature. This project is volunteer-run, and those that contribute to the code base do so on their own time.

**Comment by Lowrida** [comment]
Almost a year later i wonder if this is implemented?

**Comment by gravityfargo** [comment]
From my previous comment:
> I'd like to comment we can't give a timeline for any particular feature. This project is volunteer-run, and those that contribute to the code base do so on their own time.

You did not include a generated report, so I can't tell which specific product ID you are referring to, but the three product IDs listed in the wiki for the K70's indicate:
> hardware playback not supported. Settings will be saved to software only.

All that said, you are welcome to contribute code and submit a pull request. I am closing this issue.
