### ISSUE TITLE
Ubuntu 22.04 ckb-next not detecting keyboard/mouse

### ISSUE THREAD

**Issue by ipoese** [ckb-next/ckb-next#942]
### Describe your situation in detail.

I have two new devices:
- Corsair CORSAIR M55 RGB PRO Gaming Mouse
- Corsair CORSAIR K55 RGB PRO XT Gaming Keyboard

the `ckb-next` is installed from the ubuntu repositories:
```
ThinkPad-T14-Gen-1:~$ dpkg -l "ckb*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version          Architecture Description
+++-==============-================-============-=====================================
ii  ckb-next       0.4.4+dfsg.1-0.1 amd64        driver for Corsair keyboards and mice
```
The installed version is:
```
ThinkPad-T14-Gen-1:~$ ckb-next --version
ckb-next 0.4.4
```

but when i start up `ckb-next`, no device is detected:
![image](https://user-images.githubusercontent.com/21309442/226622583-86669430-fd56-49ff-8689-ce1cc844e325.png)

I am a bit at a loss right now how to proceed from this point forward.

### Additional Details

I don't know if it makes a difference, but the keyboard/mouse are plugged into a dock. However, attaching them directly to the Laptop does not make a difference.

### Generated Report (if applicable)

Report from [ckb-next-dev-detect](https://github.com/ckb-next/ckb-next/files/11028936/ckb-next-dev-detect-report.gz)

**Comment by JanNowak94** [comment]
@ipoese that is a fossil version -  current version is 0.5 - and it does not yet support K55 - you need git (master) for that.
Use: https://launchpad.net/~tatokis/+archive/ubuntu/ckb-next-git
@tatokis Could you close;
