### ISSUE TITLE
wiki/Supported-Hardware add minimal version of driver with support.

### ISSUE THREAD

**Issue by JanNowak94** [ckb-next/ckb-next#943]
### Enhancement Details

As in title - this should lower frequency of questions .. Probably ...

### Additional Details

Add any additional details here.

**Comment by JanNowak94** [comment]
I needed patebin it (github "something went really wrong").
https://pastebin.com/HqHkg8cf
There is issue with Strafe Strafe MK.2 - it seems to use same device id as RGB - so I cannot check when it was added.
Preview:

\* = hardware playback not supported. Settings will be saved to software only.

If your device isn't on this list, it isn't currently supported by ckb-next. Pull requests welcome.

If your device is listed as *Experimental*, this means that support for it is not enabled by default, and is  incomplete, or possibly even broken. If you wish to proceed, you can read [here](https://github.com/ckb-next/ckb-next/wiki/Linux-Installation#enabling-support-for-experimental-devices) on how to enable support for it.

Please open a bug report if you find one of these variants incompatible or an Enhancement issue if your variants is compatible.
## Keyboards

| FAMILY   | MODEL                      | Status            | DEVICE ID   | From version |
|----------|----------------------------|-------------------|-------------|--------------|
|**K55**   | RGB                        | *Supported        | 1b3d        | 3.0          |
|          | RGB PRO                    | *Supported        | 1ba4        | git          |
|          | RGB PRO LITE               |                   |             |              |
|          | RGB PRO XT                 | *Supported        | 1ba1        | git          |
|**K57**   | Wireless                   | *Experimental     |             |              |
|**K60**   | RGB PRO Low Profile        | *Supported        | 1bad        | 5.0          |
|          | RGB PRO SE                 | *Supported        | 1b8d        | 5.0          |
|          | RGB PRO                    | *Supported        | 1ba0        | 5.0          |
|          | PRO (Monochrome)           | *Supported        | 1b83        | git          |
|          | VENGEANCE                  |                   |             |              |
|**K63**   | Compact                    | Supported         | 1b40        | 3.0          |
|          | Wireless                   | *Experimental     |             | 5.0          |
|          | Wireless Special Edition   | *Experimental     |             | 5.0          |
|**K65**   | Mini                       |                   |             |              |
|          | LUX                        | Supported         | 1b37        | 3.0          |
|          | RapidFire                  | Supported         | 1b39        | 3.0          |
|          | Compact                    |                   |             |              |
|          | VENGEANCE                  |                   |             |              |
|**K66**   | RGB                        | Supported         | 1b41        | 3.2          |
|**K68**   | RGB                        | Supported         | 1b4f        | 3.0          |
|          | RAPIDFIRE                  | Supported         | 1b3f        | 3.0          |
|**K70**   | RGB                        | Supported         | 1b13        | 3.0          |
|          | TKL CHAMPION SERIES        | Requested #745    | 1b73        |              |
|          | PRO                        |                   |             |              |
|          | MK.2 Low Profile           | *Supported        | 1b55        | 4.0          |
|          | MK.2 Low Profile RAPIDFIRE | *Supported        | 1b55        | 4.0          |
|          | MK.2                       | *Supported        | 1b49        | 3.1          |
|          | MK.2 SE                    | *Supported        | 1b6b        | 3.1          |
|          | LUX                        | Supported         | 1b36        | 3.0          |
|          | LUX RGB                    | Supported         | 1b33        | 3.0          |
|          | RGB RAPIDFIRE              | Supported         | 1b38        | 3.0          |
|          | RAPIDFIRE                  | Supported         | 1b3a        | 3.0          |
|**K90**   | VENGEANCE                  | Supported         | 1b02        | 3.0          |
|**K95**   | PLATINUM                   | *Supported        | 1b2d        | 3.0          |
|          | PLATINUM SE                |                   |             |              |
|          | PLATINUM XT                | *Supported        | 1b89        | 5.0          |
|          | RGB                        | Supported         | 1b11        | 3.0          |
|**K100**  | RGB Optical-Mechanical     | Requested #839    | 1b7c        |              |
|          | RGB Mechanical             |                   | 1b7d        |              |
|**STRAFE**| NonRGB1                    | Supported         | 1b15        | 3.0          |
|          | NonRGB2                    | Supported         | 1b44        | 3.0          |
|          | RGB                        | Supported         | 1b20        | 3.0          |
|          | MK.2                       | Supported         |             | ?            |

## Mice
| Family       | MODEL                   | STATUS              | Device ID    | From version |
|--------------|-------------------------|---------------------|--------------|--------------|
| M55          | PRO                     | *Supported          | 1b70         | 5.0          |
| M65          | RGB                     | Supported           | 1b12         | 3.0          |
|              | PRO                     | Supported           | 1b2e         | 3.0          |
|              | ELITE                   | *Supported          | 1b5a         | 4.0          |
| M95          | VENGEANCE               | Supported           | 1b06         | 4.0          |
| Sabre        | RGB LASER               | Supported           | 1b19         | 3.0          |
|              | RGB OPTICAL             | Supported           | 1b14         | 3.0          |
|              | RGB OPTICAL             | Supported           | 1b32         | 3.0          |
|              | RGB                     | Supported           | 1b2f         | 3.0          |
|              | PRO CHAMP Ultra-Light   | Requested #709      |              |              |
|              | PRO CHAMP               | Requested #709      |              |              |
| Scimitar     | RGB                     | Supported           | 1b1e         | 3.0          |
|              | ELITE                   | *Supported          | 1b8b         | 4.3          |
|              | PRO                     | *Supported          | 1b3e         | 3.0          |
| HARPOON      | RGB                     | Supported           | 1b3c         | 3.0          |
|              | PRO                     | Supported           | 1b75         | 4.2          |
|              | Wireless                | *Experimental       | 1b5e & 1b65  | 5.0          |
| GLAIVE       | RGB                     | *Supported          | 1b34         | 3.0          |
|              | PRO                     | *Supported          | 1b74         | 5.0          |
| KATAR        | RGB                     | Supported           | 1b22         | 3.0          |
|              | PRO XT Ultra-Light      | Supported           | 1bac         | 5.0          |
|              | PRO Ultra-Light         | Supported           | 1b93         | 5.0          |
|              | PRO Wireless            | Requested #658      | 1b94         |              |
| IRONCLAW     | RGB                     | *Supported          | 1b5d         | 4.2          |
|              | Wireless                | *Experimental       | 1b4c & 1b66  | 5.0          |
| NIGHTSWORD   | RGB                     | Supported           | 1b5c         | 4.2          |
| DARK CORE    | RGB                     | *Experimental       | 1b35 & 1b64  | 5.0          |
|              | SE                      | *Experimental       | 1b4b & 1b51  | 5.0          |
|              | PRO SE                  | *Experimental       | 1b7e & 1b7f  | 5.0          |

## Other Devices
| FAMILY  | MODEL         | Purpose         | STATUS                      | Device ID   | From version |
|---------|---------------|-----------------|-----------------------------|-------------|--------------|
|ST100    |Premium        |Headphone Stand  | Supported                   | 0a34        | 3.0          |
|LT100    |               |Ambient Lighting | Requested #664              | 0c23        |              |
|MM700    |POLARIS        |Mousepad         | Requested #842              |             |              |
|MM800    |POLARIS        |Mousepad         | *Experimental               | 1b3b        | 3.0          |
|H150i    |Elite Capellix |AIO Cooler       | See Commander Core          |             |              |
|VIRTUOSO |RGB WIRELESS SE|Headset          | Requested #785              |             |              |
|VOID     |PRO RGB        |Headset          | Requested #735              | 0a14        |              |
|         |Slipstream     |Wireless Reciever| Requested #785              | 0a3e        |              |
|         |Commander Core |Controller Hub   | Requested #833              | 0c1c        |              |
|         |Commander PRO  |Controller Hub   | Requested #689              | 0c10        |              |

**Comment by gravityfargo** [comment]
I've updated the wiki since your last post. I push my changes to [a gist of mine](https://gist.github.com/gravityfargo/2fbce071791a4ea015b27a33a4abf534) before I make the changes on the wiki proper. 

I've been mulling over some way to make 
> * = hardware playback not supported. Settings will be saved to software only.

more obvious, and

> "Please note that version listed below is the absolute minimum required. It is not the recommended version for your device.".

would be in that same mindset. 

When I have the will for it I'll make some pretty graphics and whatnot. Anyway, I'll work on these changes when @tatokis or another person more qualified than me gives the thumbs up.

**Comment by tatokis** [comment]
@JanNowak94 Thank you very much for this. Really appreciated.
The Strafe RGB MK.2 is `0x1b48`. No device shares a usb id with another one.

@gravityfargo
Maybe change Status to STATUS as well.

A few nitpicks:
1. I think `From version` would sound better as either `Since`, `Since version`, or if not too long, `Supported since`.
2. Instead of `git`, maybe put `0.5.1 (git)`.

Other than that, I fully agree with:

> At worst this documentation is still better - it does tell user absolute minimum that he should expect anything from.

So go ahead and make any changes you deem appropriate. If something is incorrect, we'll fix it later down the line.

> "Please note that version listed below is the absolute minimum required. It is not the recommended version for your device.".

Maybe if possible also clarify that this can be dependent on the firmware version on the device itself. Usually though, once a device is added to a release, it functions adequately. Otherwise it's stuck in experimental hell.

**Comment by gravityfargo** [comment]
I have made changes have been made to the wiki
