### ISSUE TITLE
Fan / Pump Controlling

### ISSUE THREAD

**Issue by AmEndewastaken** [ckb-next/ckb-next#955]
### Enhancement Details

Do you plan on Controlling Fans and Pumps for a watercooling system?

### Additional Details

Add any additional details here.

**Comment by gravityfargo** [comment]
With the exception of the older H115i AIOs (and probably a few more), the Pump All-in-Ones are controlled by the Commander Core or Commander Pro, which support has been requested for. See: #833 and #689

As for the fans, they go through the Commander Core/Pro or Lighting Link Hubs, which support has been requested for. See: #639
