### ISSUE TITLE
Corsair K83 Wireless 

### ISSUE THREAD

**Issue by Thronalgius** [ckb-next/ckb-next#958]
### What kind of device is it?

Keyboard

### What is the name of the device?

K83 Wireless

### Link to Corsair's Product Page

https://www.corsair.com/ww/en/K83-FAQ

### Additional Details

Add any additional details here.
Theitr is no RGB on this keyboard, so I'm only interested in the software update and getting the special (FN) key to work, and remap some key shortcuts so its the same for my windows machine (as I use it between windows and linux) 

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
Please create a new issue and attach a generated report.  Instructions can be found in the issue form.
