### ISSUE TITLE
ckb-next on fedora 38 with corsair k95  rgb platnium xt

### ISSUE THREAD

**Issue by stevef9432203** [ckb-next/ckb-next#961]
### Affected Devices

corsair k95  rgb platnium xt

### Linux Distribution

fedora 38

### Installation Method

sudo dnf install ckb-next

### ckb-next version

same release as github ver

### What did you expect?

After installing K95 is dead and if I plug 2nd usb kbd in, Ckb-next screen never loads. To  fix 
sudo dnf remove ckb-next and reboot. Then Kbd works again

### Did you try anything that may have helped?

Remove software and reboot

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.

**Comment by tatokis** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2192159
