### ISSUE TITLE
k70 mini pro wireless

### ISSUE THREAD

**Issue by luthiwd** [ckb-next/ckb-next#969]
### Affected Devices

k70 mini pro wireless

### Linux Distribution

Ubuntu 22.04.2 LTS

### Installation Method

Tasos Sahanidis

### ckb-next version

ckb-next	0.5.0-1

### What did you expect?

I can use keyboard but not configurate.

### Additional Details

Add any additional details here.

### Generated Report

[ckb-next-report-1686118146.gz](https://github.com/ckb-next/ckb-next/files/11673098/ckb-next-report-1686118146.gz)

**Comment by gravityfargo** [comment]
Duplicate of #970
