### ISSUE TITLE
ckb consumes up to 100% of the CPU

### ISSUE THREAD

**Issue by sashko** [ckb-next/ckb-next#97]
# Devices information

[ckb-dev-detect-report.gz](https://github.com/ckb-next/ckb-next/files/1731342/ckb-dev-detect-report.gz)

---

# Bug report

- [x] Yes
- [ ] No

### Source
e6f3ff446a6899be09d2391cd46573285a1f3360

### Branch
master

## What is the program's current behavior?
ckb always consumes 20-100% of CPU.

![screenshot from 2018-02-15 17-16-32](https://user-images.githubusercontent.com/71181/36267526-62d7038e-1274-11e8-9736-12fd9ba05b61.png)

![screenshot from 2018-02-16 13-37-41](https://user-images.githubusercontent.com/71181/36308501-48b502a0-1321-11e8-8df5-6d1c5bdb003a.png)

---

# Something else

I would be more than happy profiling it using Valgrind or whatever you want if needed.

**Comment by ZirconiumX** [comment]
... Huh. What're your hardware specs?

Our usual suggestions for this kind of thing are to lower the animation
frame rate and to disable "show animated" in the GUI.

**Comment by sashko** [comment]
@ZirconiumXi7-6560U and 16Gb RAM

**Comment by sashko** [comment]
i7-6560U and 16Gb RAM.

I have just played with different animation profiles and do not seem to make any difference: always get 20-40% CPU usage, which is crazy!

**Comment by ZirconiumX** [comment]
Did you try disabling "show animated"? With that turned off, I can use CKB even on a raspberry pi.

**Comment by sashko** [comment]
Disabling "show animated" seems to drop average CPU consumption by about 25%, which is not nearly enough.

**Comment by ZirconiumX** [comment]
Next, go into "more settings" and lower the frame rate, if it's above about
30fps.

**Comment by tatokis** [comment]
@sashko If you try a profile without any animations, do you still get high CPU usage? This could be a bug.

**Comment by sashko** [comment]
It was set to 30. Lowering it to 10 dropped CPU usage to ~8%.

**Comment by sashko** [comment]
@tatokis profile without animation and FPS = 30 has ~15% CPU usage. Lowering FPS to 10 drops it to 5-7%

**Comment by ZirconiumX** [comment]
I think you should drop by IRC; I have a hunch here, but we'll be able to
test it faster there, rather than in GitHub.

**Comment by ZirconiumX** [comment]
I'm tagging it as this, because even though @sashko can reproduce it, I think this might be meltdown related, and so we would need a Skylake system to verify.

**Comment by light2yellow** [comment]
30 FPS, spatial dithering disabled, "show animated" disabled - rainbow takes ~2% on an old i3. So, can't reproduce either. The daemon takes ~5% for me (combined), it looks same for you.
![](https://imgur.com/c8X5Dp5.jpg)
![](https://imgur.com/0nudYQS.jpg)

**Comment by sashko** [comment]
@light2yellow you're checking the wrong process: it's not the ckb-deamon that is consuming CPU but the ckb app

**Comment by tatokis** [comment]
@sashko top one is the GUI.
I can't reproduce on an i7-4600U either, getting around the same usage as @light2yellow, fresh from master.

**Comment by ZirconiumX** [comment]
So, @tatokis noticed that the GUI sends even blank frames to the daemon, which would result in a lot of syscalls, which are noticeably more expensive on Skylake upward. As a long-term guide, we should detect and avoid sending blank frames to the daemon, and likewise avoid sending duplicate frames, which could perhaps kill two birds with one stone.

**Comment by sashko** [comment]
Glad it has helped you find a bottleneck (hopefully the one I've bumped into).

Just curious: why process name is 'ckb' in my case and 'ckb-next' in @light2yellow's case?

**Comment by tatokis** [comment]
@sashko Sadly I don't think much can be done in your case.
Also, see #65
