### ISSUE TITLE
Nexus is not detected

### ISSUE THREAD

**Issue by Helmchen-Lord** [ckb-next/ckb-next#977]
### Affected Devices

Nexus

### Linux Distribution

Fedora

### Installation Method

Fedora software

### ckb-next version

ckb-next 0.5.0

### What did you expect?

Corsair Nexus should be recognized after plugging it in.

### Did you try anything that may have helped?

Have rebooted after installation and tried to disconnect and connect the device.

### Additional Details

Add any additional details here.

### Generated Report

[ckb-next-report-1688305238.gz](https://github.com/ckb-next/ckb-next/files/11929682/ckb-next-report-1688305238.gz)

**Comment by gravityfargo** [comment]
The Nexus isn't currently supported and has been requested in #906
