### ISSUE TITLE
iCUE H150i ELITE CAPELLIX Liquid CPU Cooler (Commander Core)

### ISSUE THREAD

**Issue by SMGttv** [ckb-next/ckb-next#988]
### What kind of device is it?

Control Modules (Commander PRO)

### What is the name of the device?

CORSAIR iCUE COMMANDER Core

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/cpu-coolers/cw-9060048-ww/icue-h150i-elite-capellix-liquid-cpu-cooler-cw-9060048-ww

### Additional Details

The link to the device I posted goes to the AIO that I have. The commander core came with the AIO as it controls the AIO and all connected fans. This would be the reason I would classify this as a control module since it is the commander core that the PC interfaces with.

OpenRGB supports this device now. Would love to see it supported by CKB-Next.
 

### Generated Report

[ckb-next-dev-detect-report.txt](https://github.com/ckb-next/ckb-next/files/12255904/ckb-next-dev-detect-report.txt)

**Comment by gravityfargo** [comment]
By the product page, it looks like this device uses the regular Commander Core, which has been previously requested. You should subscribe to the original issue so you'll get notifications if progress is made. 

See: https://github.com/ckb-next/ckb-next/issues/833
