### ISSUE TITLE
Please add support for iCUE H100i Elite CAPELLIX XT

### ISSUE THREAD

**Issue by kindagonzo** [ckb-next/ckb-next#992]
### What kind of device is it?

AIO Coolers

### What is the name of the device?

Corsair iCUE H100i Elite CAPELLIX XT

### Link to Corsair's Product Page

https://www.corsair.com/us/en/p/cpu-coolers/cw-9060068-ww/icue-h100i-elite-capellix-xt-liquid-cpu-cooler

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
With the exception of the older H115i AIOs (and probably a few more), most of the pump All-in-Ones are controlled by the Commander Core or Commander Pro, which support has been requested for. By the product page, this one uses the Commander Core.

 See: https://github.com/ckb-next/ckb-next/issues/833

**Comment by kindagonzo** [comment]
@gravityfargo thank you!
