### ISSUE TITLE
Profile Automatic Window Detect Not Working With Wayland

### ISSUE THREAD

**Issue by praxis-alpha** [ckb-next/ckb-next#999]
### Affected Devices

K70 RGB MK.2 SE, M65 RGB ELITE

### Linux Distribution

Arch

### Installation Method

AU R

### ckb-next version

ckb-next 1:0.6.0.r29.gb2188fac-1

### What did you expect?

Profiles to automatically change based on events, such as window title or program path; when using Wayland.
When X11 is used, all events defined work as indicated.

### Did you try anything that may have helped?

Update system, reboot system, reinstall ckb-next package.

### Additional Details

Add any additional details here.

### Generated Report

Drag your generated report here.

**Comment by gravityfargo** [comment]
If this issue persists, please create a new issue with a generated report. Instructions for doing so are in the issue form.
